// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.35.0
// source: pkg/corepb/common.proto

package corepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaginationToken_Type int32

const (
	PaginationToken_NEXT     PaginationToken_Type = 0
	PaginationToken_PREVIOUS PaginationToken_Type = 1
)

// Enum value maps for PaginationToken_Type.
var (
	PaginationToken_Type_name = map[int32]string{
		0: "NEXT",
		1: "PREVIOUS",
	}
	PaginationToken_Type_value = map[string]int32{
		"NEXT":     0,
		"PREVIOUS": 1,
	}
)

func (x PaginationToken_Type) Enum() *PaginationToken_Type {
	p := new(PaginationToken_Type)
	*p = x
	return p
}

func (x PaginationToken_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaginationToken_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_corepb_common_proto_enumTypes[0].Descriptor()
}

func (PaginationToken_Type) Type() protoreflect.EnumType {
	return &file_pkg_corepb_common_proto_enumTypes[0]
}

func (x PaginationToken_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaginationToken_Type.Descriptor instead.
func (PaginationToken_Type) EnumDescriptor() ([]byte, []int) {
	return file_pkg_corepb_common_proto_rawDescGZIP(), []int{0, 0}
}

type PaginationToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PaginationToken_Type   `protobuf:"varint,1,opt,name=type,proto3,enum=com.evrblk.grackle.corepb.PaginationToken_Type" json:"type,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationToken) Reset() {
	*x = PaginationToken{}
	mi := &file_pkg_corepb_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationToken) ProtoMessage() {}

func (x *PaginationToken) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationToken.ProtoReflect.Descriptor instead.
func (*PaginationToken) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_common_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationToken) GetType() PaginationToken_Type {
	if x != nil {
		return x.Type
	}
	return PaginationToken_NEXT
}

func (x *PaginationToken) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type LeaseId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint64                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	NamespaceId   uint32                 `protobuf:"varint,2,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	LeaseId       uint64                 `protobuf:"varint,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseId) Reset() {
	*x = LeaseId{}
	mi := &file_pkg_corepb_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseId) ProtoMessage() {}

func (x *LeaseId) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseId.ProtoReflect.Descriptor instead.
func (*LeaseId) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_common_proto_rawDescGZIP(), []int{1}
}

func (x *LeaseId) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *LeaseId) GetNamespaceId() uint32 {
	if x != nil {
		return x.NamespaceId
	}
	return 0
}

func (x *LeaseId) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

type Lease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *LeaseId               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProcessId     string                 `protobuf:"bytes,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lease) Reset() {
	*x = Lease{}
	mi := &file_pkg_corepb_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_common_proto_rawDescGZIP(), []int{2}
}

func (x *Lease) GetId() *LeaseId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Lease) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *Lease) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Lease) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_pkg_corepb_common_proto protoreflect.FileDescriptor

const file_pkg_corepb_common_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/corepb/common.proto\x12\x19com.evrblk.grackle.corepb\"\x8c\x01\n" +
	"\x0fPaginationToken\x12C\n" +
	"\x04type\x18\x01 \x01(\x0e2/.com.evrblk.grackle.corepb.PaginationToken.TypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x1e\n" +
	"\x04Type\x12\b\n" +
	"\x04NEXT\x10\x00\x12\f\n" +
	"\bPREVIOUS\x10\x01\"f\n" +
	"\aLeaseId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x04R\taccountId\x12!\n" +
	"\fnamespace_id\x18\x02 \x01(\rR\vnamespaceId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\x04R\aleaseId\"\x98\x01\n" +
	"\x05Lease\x122\n" +
	"\x02id\x18\x01 \x01(\v2\".com.evrblk.grackle.corepb.LeaseIdR\x02id\x12\x1d\n" +
	"\n" +
	"process_id\x18\x02 \x01(\tR\tprocessId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAtB&Z$github.com/evrblk/grackle/pkg/corepbb\x06proto3"

var (
	file_pkg_corepb_common_proto_rawDescOnce sync.Once
	file_pkg_corepb_common_proto_rawDescData []byte
)

func file_pkg_corepb_common_proto_rawDescGZIP() []byte {
	file_pkg_corepb_common_proto_rawDescOnce.Do(func() {
		file_pkg_corepb_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_corepb_common_proto_rawDesc), len(file_pkg_corepb_common_proto_rawDesc)))
	})
	return file_pkg_corepb_common_proto_rawDescData
}

var file_pkg_corepb_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_corepb_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_corepb_common_proto_goTypes = []any{
	(PaginationToken_Type)(0), // 0: com.evrblk.grackle.corepb.PaginationToken.Type
	(*PaginationToken)(nil),   // 1: com.evrblk.grackle.corepb.PaginationToken
	(*LeaseId)(nil),           // 2: com.evrblk.grackle.corepb.LeaseId
	(*Lease)(nil),             // 3: com.evrblk.grackle.corepb.Lease
}
var file_pkg_corepb_common_proto_depIdxs = []int32{
	0, // 0: com.evrblk.grackle.corepb.PaginationToken.type:type_name -> com.evrblk.grackle.corepb.PaginationToken.Type
	2, // 1: com.evrblk.grackle.corepb.Lease.id:type_name -> com.evrblk.grackle.corepb.LeaseId
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_corepb_common_proto_init() }
func file_pkg_corepb_common_proto_init() {
	if File_pkg_corepb_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_corepb_common_proto_rawDesc), len(file_pkg_corepb_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_corepb_common_proto_goTypes,
		DependencyIndexes: file_pkg_corepb_common_proto_depIdxs,
		EnumInfos:         file_pkg_corepb_common_proto_enumTypes,
		MessageInfos:      file_pkg_corepb_common_proto_msgTypes,
	}.Build()
	File_pkg_corepb_common_proto = out.File
	file_pkg_corepb_common_proto_goTypes = nil
	file_pkg_corepb_common_proto_depIdxs = nil
}
