// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.35.0
// source: pkg/corepb/locks.proto

package corepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LockState int32

const (
	LockState_LOCK_STATE_INVALID          LockState = 0
	LockState_LOCK_STATE_UNLOCKED         LockState = 1
	LockState_LOCK_STATE_SHARED_LOCKED    LockState = 2
	LockState_LOCK_STATE_EXCLUSIVE_LOCKED LockState = 3
)

// Enum value maps for LockState.
var (
	LockState_name = map[int32]string{
		0: "LOCK_STATE_INVALID",
		1: "LOCK_STATE_UNLOCKED",
		2: "LOCK_STATE_SHARED_LOCKED",
		3: "LOCK_STATE_EXCLUSIVE_LOCKED",
	}
	LockState_value = map[string]int32{
		"LOCK_STATE_INVALID":          0,
		"LOCK_STATE_UNLOCKED":         1,
		"LOCK_STATE_SHARED_LOCKED":    2,
		"LOCK_STATE_EXCLUSIVE_LOCKED": 3,
	}
)

func (x LockState) Enum() *LockState {
	p := new(LockState)
	*p = x
	return p
}

func (x LockState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_corepb_locks_proto_enumTypes[0].Descriptor()
}

func (LockState) Type() protoreflect.EnumType {
	return &file_pkg_corepb_locks_proto_enumTypes[0]
}

func (x LockState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockState.Descriptor instead.
func (LockState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{0}
}

type AcquireLockRequest struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	LockId                       *LockId                `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	LeaseId                      uint64                 `protobuf:"fixed64,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Exclusive                    bool                   `protobuf:"varint,3,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
	Metadata                     map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Now                          int64                  `protobuf:"fixed64,5,opt,name=now,proto3" json:"now,omitempty"`
	MaxNumberOfLocksPerNamespace int64                  `protobuf:"varint,6,opt,name=max_number_of_locks_per_namespace,json=maxNumberOfLocksPerNamespace,proto3" json:"max_number_of_locks_per_namespace,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *AcquireLockRequest) Reset() {
	*x = AcquireLockRequest{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireLockRequest) ProtoMessage() {}

func (x *AcquireLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireLockRequest.ProtoReflect.Descriptor instead.
func (*AcquireLockRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{0}
}

func (x *AcquireLockRequest) GetLockId() *LockId {
	if x != nil {
		return x.LockId
	}
	return nil
}

func (x *AcquireLockRequest) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

func (x *AcquireLockRequest) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

func (x *AcquireLockRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AcquireLockRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

func (x *AcquireLockRequest) GetMaxNumberOfLocksPerNamespace() int64 {
	if x != nil {
		return x.MaxNumberOfLocksPerNamespace
	}
	return 0
}

type AcquireLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lock          *Lock                  `protobuf:"bytes,1,opt,name=lock,proto3" json:"lock,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireLockResponse) Reset() {
	*x = AcquireLockResponse{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireLockResponse) ProtoMessage() {}

func (x *AcquireLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireLockResponse.ProtoReflect.Descriptor instead.
func (*AcquireLockResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{1}
}

func (x *AcquireLockResponse) GetLock() *Lock {
	if x != nil {
		return x.Lock
	}
	return nil
}

func (x *AcquireLockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReleaseLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        *LockId                `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	LeaseId       uint64                 `protobuf:"fixed64,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Now           int64                  `protobuf:"fixed64,3,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLockRequest) Reset() {
	*x = ReleaseLockRequest{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLockRequest) ProtoMessage() {}

func (x *ReleaseLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLockRequest.ProtoReflect.Descriptor instead.
func (*ReleaseLockRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseLockRequest) GetLockId() *LockId {
	if x != nil {
		return x.LockId
	}
	return nil
}

func (x *ReleaseLockRequest) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

func (x *ReleaseLockRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

type ReleaseLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lock          *Lock                  `protobuf:"bytes,1,opt,name=lock,proto3" json:"lock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLockResponse) Reset() {
	*x = ReleaseLockResponse{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLockResponse) ProtoMessage() {}

func (x *ReleaseLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLockResponse.ProtoReflect.Descriptor instead.
func (*ReleaseLockResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseLockResponse) GetLock() *Lock {
	if x != nil {
		return x.Lock
	}
	return nil
}

type GetLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        *LockId                `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	Now           int64                  `protobuf:"fixed64,2,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLockRequest) Reset() {
	*x = GetLockRequest{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLockRequest) ProtoMessage() {}

func (x *GetLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLockRequest.ProtoReflect.Descriptor instead.
func (*GetLockRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{4}
}

func (x *GetLockRequest) GetLockId() *LockId {
	if x != nil {
		return x.LockId
	}
	return nil
}

func (x *GetLockRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

type GetLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lock          *Lock                  `protobuf:"bytes,1,opt,name=lock,proto3" json:"lock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLockResponse) Reset() {
	*x = GetLockResponse{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLockResponse) ProtoMessage() {}

func (x *GetLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLockResponse.ProtoReflect.Descriptor instead.
func (*GetLockResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{5}
}

func (x *GetLockResponse) GetLock() *Lock {
	if x != nil {
		return x.Lock
	}
	return nil
}

type DeleteLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        *LockId                `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	Now           int64                  `protobuf:"fixed64,2,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLockRequest) Reset() {
	*x = DeleteLockRequest{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLockRequest) ProtoMessage() {}

func (x *DeleteLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLockRequest.ProtoReflect.Descriptor instead.
func (*DeleteLockRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteLockRequest) GetLockId() *LockId {
	if x != nil {
		return x.LockId
	}
	return nil
}

func (x *DeleteLockRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

type DeleteLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLockResponse) Reset() {
	*x = DeleteLockResponse{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLockResponse) ProtoMessage() {}

func (x *DeleteLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLockResponse.ProtoReflect.Descriptor instead.
func (*DeleteLockResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{7}
}

type ListLocksRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId     *NamespaceId           `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	Now             int64                  `protobuf:"fixed64,2,opt,name=now,proto3" json:"now,omitempty"`
	PaginationToken *PaginationToken       `protobuf:"bytes,3,opt,name=pagination_token,json=paginationToken,proto3" json:"pagination_token,omitempty"`
	Limit           int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListLocksRequest) Reset() {
	*x = ListLocksRequest{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocksRequest) ProtoMessage() {}

func (x *ListLocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocksRequest.ProtoReflect.Descriptor instead.
func (*ListLocksRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{8}
}

func (x *ListLocksRequest) GetNamespaceId() *NamespaceId {
	if x != nil {
		return x.NamespaceId
	}
	return nil
}

func (x *ListLocksRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

func (x *ListLocksRequest) GetPaginationToken() *PaginationToken {
	if x != nil {
		return x.PaginationToken
	}
	return nil
}

func (x *ListLocksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListLocksResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Locks                   []*Lock                `protobuf:"bytes,1,rep,name=locks,proto3" json:"locks,omitempty"`
	NextPaginationToken     *PaginationToken       `protobuf:"bytes,2,opt,name=next_pagination_token,json=nextPaginationToken,proto3" json:"next_pagination_token,omitempty"`
	PreviousPaginationToken *PaginationToken       `protobuf:"bytes,3,opt,name=previous_pagination_token,json=previousPaginationToken,proto3" json:"previous_pagination_token,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListLocksResponse) Reset() {
	*x = ListLocksResponse{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocksResponse) ProtoMessage() {}

func (x *ListLocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocksResponse.ProtoReflect.Descriptor instead.
func (*ListLocksResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{9}
}

func (x *ListLocksResponse) GetLocks() []*Lock {
	if x != nil {
		return x.Locks
	}
	return nil
}

func (x *ListLocksResponse) GetNextPaginationToken() *PaginationToken {
	if x != nil {
		return x.NextPaginationToken
	}
	return nil
}

func (x *ListLocksResponse) GetPreviousPaginationToken() *PaginationToken {
	if x != nil {
		return x.PreviousPaginationToken
	}
	return nil
}

type ListLocksByLeaseIdRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LeaseId         *LeaseId               `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Now             int64                  `protobuf:"fixed64,2,opt,name=now,proto3" json:"now,omitempty"`
	PaginationToken *PaginationToken       `protobuf:"bytes,3,opt,name=pagination_token,json=paginationToken,proto3" json:"pagination_token,omitempty"`
	Limit           int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListLocksByLeaseIdRequest) Reset() {
	*x = ListLocksByLeaseIdRequest{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocksByLeaseIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocksByLeaseIdRequest) ProtoMessage() {}

func (x *ListLocksByLeaseIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocksByLeaseIdRequest.ProtoReflect.Descriptor instead.
func (*ListLocksByLeaseIdRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{10}
}

func (x *ListLocksByLeaseIdRequest) GetLeaseId() *LeaseId {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

func (x *ListLocksByLeaseIdRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

func (x *ListLocksByLeaseIdRequest) GetPaginationToken() *PaginationToken {
	if x != nil {
		return x.PaginationToken
	}
	return nil
}

func (x *ListLocksByLeaseIdRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListLocksByLeaseIdResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Locks                   []*Lock                `protobuf:"bytes,1,rep,name=locks,proto3" json:"locks,omitempty"`
	NextPaginationToken     *PaginationToken       `protobuf:"bytes,2,opt,name=next_pagination_token,json=nextPaginationToken,proto3" json:"next_pagination_token,omitempty"`
	PreviousPaginationToken *PaginationToken       `protobuf:"bytes,3,opt,name=previous_pagination_token,json=previousPaginationToken,proto3" json:"previous_pagination_token,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListLocksByLeaseIdResponse) Reset() {
	*x = ListLocksByLeaseIdResponse{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocksByLeaseIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocksByLeaseIdResponse) ProtoMessage() {}

func (x *ListLocksByLeaseIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocksByLeaseIdResponse.ProtoReflect.Descriptor instead.
func (*ListLocksByLeaseIdResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{11}
}

func (x *ListLocksByLeaseIdResponse) GetLocks() []*Lock {
	if x != nil {
		return x.Locks
	}
	return nil
}

func (x *ListLocksByLeaseIdResponse) GetNextPaginationToken() *PaginationToken {
	if x != nil {
		return x.NextPaginationToken
	}
	return nil
}

func (x *ListLocksByLeaseIdResponse) GetPreviousPaginationToken() *PaginationToken {
	if x != nil {
		return x.PreviousPaginationToken
	}
	return nil
}

type RunLocksGarbageCollectionRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Now                   int64                  `protobuf:"fixed64,1,opt,name=now,proto3" json:"now,omitempty"`
	GcRecordsPageSize     int64                  `protobuf:"varint,2,opt,name=gc_records_page_size,json=gcRecordsPageSize,proto3" json:"gc_records_page_size,omitempty"`
	GcRecordLocksPageSize int64                  `protobuf:"varint,3,opt,name=gc_record_locks_page_size,json=gcRecordLocksPageSize,proto3" json:"gc_record_locks_page_size,omitempty"`
	MaxVisitedLocks       int64                  `protobuf:"varint,4,opt,name=max_visited_locks,json=maxVisitedLocks,proto3" json:"max_visited_locks,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RunLocksGarbageCollectionRequest) Reset() {
	*x = RunLocksGarbageCollectionRequest{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunLocksGarbageCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunLocksGarbageCollectionRequest) ProtoMessage() {}

func (x *RunLocksGarbageCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunLocksGarbageCollectionRequest.ProtoReflect.Descriptor instead.
func (*RunLocksGarbageCollectionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{12}
}

func (x *RunLocksGarbageCollectionRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

func (x *RunLocksGarbageCollectionRequest) GetGcRecordsPageSize() int64 {
	if x != nil {
		return x.GcRecordsPageSize
	}
	return 0
}

func (x *RunLocksGarbageCollectionRequest) GetGcRecordLocksPageSize() int64 {
	if x != nil {
		return x.GcRecordLocksPageSize
	}
	return 0
}

func (x *RunLocksGarbageCollectionRequest) GetMaxVisitedLocks() int64 {
	if x != nil {
		return x.MaxVisitedLocks
	}
	return 0
}

type RunLocksGarbageCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunLocksGarbageCollectionResponse) Reset() {
	*x = RunLocksGarbageCollectionResponse{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunLocksGarbageCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunLocksGarbageCollectionResponse) ProtoMessage() {}

func (x *RunLocksGarbageCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunLocksGarbageCollectionResponse.ProtoReflect.Descriptor instead.
func (*RunLocksGarbageCollectionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{13}
}

type LocksDeleteNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   *NamespaceId           `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	RecordId      uint64                 `protobuf:"fixed64,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Now           int64                  `protobuf:"fixed64,3,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocksDeleteNamespaceRequest) Reset() {
	*x = LocksDeleteNamespaceRequest{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocksDeleteNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocksDeleteNamespaceRequest) ProtoMessage() {}

func (x *LocksDeleteNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocksDeleteNamespaceRequest.ProtoReflect.Descriptor instead.
func (*LocksDeleteNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{14}
}

func (x *LocksDeleteNamespaceRequest) GetNamespaceId() *NamespaceId {
	if x != nil {
		return x.NamespaceId
	}
	return nil
}

func (x *LocksDeleteNamespaceRequest) GetRecordId() uint64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *LocksDeleteNamespaceRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

type LocksDeleteNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocksDeleteNamespaceResponse) Reset() {
	*x = LocksDeleteNamespaceResponse{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocksDeleteNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocksDeleteNamespaceResponse) ProtoMessage() {}

func (x *LocksDeleteNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocksDeleteNamespaceResponse.ProtoReflect.Descriptor instead.
func (*LocksDeleteNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{15}
}

type CreateLockLeaseRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	LeaseId               *LeaseId               `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	ProcessId             string                 `protobuf:"bytes,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	TtlSeconds            int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	Now                   int64                  `protobuf:"fixed64,4,opt,name=now,proto3" json:"now,omitempty"`
	Metadata              map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MaxNumberOfLockLeases int64                  `protobuf:"varint,6,opt,name=max_number_of_lock_leases,json=maxNumberOfLockLeases,proto3" json:"max_number_of_lock_leases,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateLockLeaseRequest) Reset() {
	*x = CreateLockLeaseRequest{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLockLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLockLeaseRequest) ProtoMessage() {}

func (x *CreateLockLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLockLeaseRequest.ProtoReflect.Descriptor instead.
func (*CreateLockLeaseRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{16}
}

func (x *CreateLockLeaseRequest) GetLeaseId() *LeaseId {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

func (x *CreateLockLeaseRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *CreateLockLeaseRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *CreateLockLeaseRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

func (x *CreateLockLeaseRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateLockLeaseRequest) GetMaxNumberOfLockLeases() int64 {
	if x != nil {
		return x.MaxNumberOfLockLeases
	}
	return 0
}

type CreateLockLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLockLeaseResponse) Reset() {
	*x = CreateLockLeaseResponse{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLockLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLockLeaseResponse) ProtoMessage() {}

func (x *CreateLockLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLockLeaseResponse.ProtoReflect.Descriptor instead.
func (*CreateLockLeaseResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{17}
}

func (x *CreateLockLeaseResponse) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type RevokeLockLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       *LeaseId               `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Now           int64                  `protobuf:"fixed64,2,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeLockLeaseRequest) Reset() {
	*x = RevokeLockLeaseRequest{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeLockLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeLockLeaseRequest) ProtoMessage() {}

func (x *RevokeLockLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeLockLeaseRequest.ProtoReflect.Descriptor instead.
func (*RevokeLockLeaseRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{18}
}

func (x *RevokeLockLeaseRequest) GetLeaseId() *LeaseId {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

func (x *RevokeLockLeaseRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

type RevokeLockLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeLockLeaseResponse) Reset() {
	*x = RevokeLockLeaseResponse{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeLockLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeLockLeaseResponse) ProtoMessage() {}

func (x *RevokeLockLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeLockLeaseResponse.ProtoReflect.Descriptor instead.
func (*RevokeLockLeaseResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{19}
}

type RefreshLockLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       *LeaseId               `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	Now           int64                  `protobuf:"fixed64,3,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshLockLeaseRequest) Reset() {
	*x = RefreshLockLeaseRequest{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshLockLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshLockLeaseRequest) ProtoMessage() {}

func (x *RefreshLockLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshLockLeaseRequest.ProtoReflect.Descriptor instead.
func (*RefreshLockLeaseRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{20}
}

func (x *RefreshLockLeaseRequest) GetLeaseId() *LeaseId {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

func (x *RefreshLockLeaseRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *RefreshLockLeaseRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

type RefreshLockLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshLockLeaseResponse) Reset() {
	*x = RefreshLockLeaseResponse{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshLockLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshLockLeaseResponse) ProtoMessage() {}

func (x *RefreshLockLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshLockLeaseResponse.ProtoReflect.Descriptor instead.
func (*RefreshLockLeaseResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{21}
}

func (x *RefreshLockLeaseResponse) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type GetLockLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       *LeaseId               `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Now           int64                  `protobuf:"fixed64,2,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLockLeaseRequest) Reset() {
	*x = GetLockLeaseRequest{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLockLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLockLeaseRequest) ProtoMessage() {}

func (x *GetLockLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLockLeaseRequest.ProtoReflect.Descriptor instead.
func (*GetLockLeaseRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{22}
}

func (x *GetLockLeaseRequest) GetLeaseId() *LeaseId {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

func (x *GetLockLeaseRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

type GetLockLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLockLeaseResponse) Reset() {
	*x = GetLockLeaseResponse{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLockLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLockLeaseResponse) ProtoMessage() {}

func (x *GetLockLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLockLeaseResponse.ProtoReflect.Descriptor instead.
func (*GetLockLeaseResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{23}
}

func (x *GetLockLeaseResponse) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type ListLockLeasesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId     *NamespaceId           `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	Now             int64                  `protobuf:"fixed64,2,opt,name=now,proto3" json:"now,omitempty"`
	PaginationToken *PaginationToken       `protobuf:"bytes,3,opt,name=pagination_token,json=paginationToken,proto3" json:"pagination_token,omitempty"`
	Limit           int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListLockLeasesRequest) Reset() {
	*x = ListLockLeasesRequest{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLockLeasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLockLeasesRequest) ProtoMessage() {}

func (x *ListLockLeasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLockLeasesRequest.ProtoReflect.Descriptor instead.
func (*ListLockLeasesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{24}
}

func (x *ListLockLeasesRequest) GetNamespaceId() *NamespaceId {
	if x != nil {
		return x.NamespaceId
	}
	return nil
}

func (x *ListLockLeasesRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

func (x *ListLockLeasesRequest) GetPaginationToken() *PaginationToken {
	if x != nil {
		return x.PaginationToken
	}
	return nil
}

func (x *ListLockLeasesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListLockLeasesResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Leases                  []*Lease               `protobuf:"bytes,1,rep,name=leases,proto3" json:"leases,omitempty"`
	NextPaginationToken     *PaginationToken       `protobuf:"bytes,2,opt,name=next_pagination_token,json=nextPaginationToken,proto3" json:"next_pagination_token,omitempty"`
	PreviousPaginationToken *PaginationToken       `protobuf:"bytes,3,opt,name=previous_pagination_token,json=previousPaginationToken,proto3" json:"previous_pagination_token,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListLockLeasesResponse) Reset() {
	*x = ListLockLeasesResponse{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLockLeasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLockLeasesResponse) ProtoMessage() {}

func (x *ListLockLeasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLockLeasesResponse.ProtoReflect.Descriptor instead.
func (*ListLockLeasesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{25}
}

func (x *ListLockLeasesResponse) GetLeases() []*Lease {
	if x != nil {
		return x.Leases
	}
	return nil
}

func (x *ListLockLeasesResponse) GetNextPaginationToken() *PaginationToken {
	if x != nil {
		return x.NextPaginationToken
	}
	return nil
}

func (x *ListLockLeasesResponse) GetPreviousPaginationToken() *PaginationToken {
	if x != nil {
		return x.PreviousPaginationToken
	}
	return nil
}

type ListLockLeasesByProcessIdRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId     *NamespaceId           `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	ProcessId       string                 `protobuf:"bytes,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Now             int64                  `protobuf:"fixed64,3,opt,name=now,proto3" json:"now,omitempty"`
	PaginationToken *PaginationToken       `protobuf:"bytes,4,opt,name=pagination_token,json=paginationToken,proto3" json:"pagination_token,omitempty"`
	Limit           int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListLockLeasesByProcessIdRequest) Reset() {
	*x = ListLockLeasesByProcessIdRequest{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLockLeasesByProcessIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLockLeasesByProcessIdRequest) ProtoMessage() {}

func (x *ListLockLeasesByProcessIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLockLeasesByProcessIdRequest.ProtoReflect.Descriptor instead.
func (*ListLockLeasesByProcessIdRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{26}
}

func (x *ListLockLeasesByProcessIdRequest) GetNamespaceId() *NamespaceId {
	if x != nil {
		return x.NamespaceId
	}
	return nil
}

func (x *ListLockLeasesByProcessIdRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *ListLockLeasesByProcessIdRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

func (x *ListLockLeasesByProcessIdRequest) GetPaginationToken() *PaginationToken {
	if x != nil {
		return x.PaginationToken
	}
	return nil
}

func (x *ListLockLeasesByProcessIdRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListLockLeasesByProcessIdResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Leases                  []*Lease               `protobuf:"bytes,1,rep,name=leases,proto3" json:"leases,omitempty"`
	NextPaginationToken     *PaginationToken       `protobuf:"bytes,2,opt,name=next_pagination_token,json=nextPaginationToken,proto3" json:"next_pagination_token,omitempty"`
	PreviousPaginationToken *PaginationToken       `protobuf:"bytes,3,opt,name=previous_pagination_token,json=previousPaginationToken,proto3" json:"previous_pagination_token,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListLockLeasesByProcessIdResponse) Reset() {
	*x = ListLockLeasesByProcessIdResponse{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLockLeasesByProcessIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLockLeasesByProcessIdResponse) ProtoMessage() {}

func (x *ListLockLeasesByProcessIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLockLeasesByProcessIdResponse.ProtoReflect.Descriptor instead.
func (*ListLockLeasesByProcessIdResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{27}
}

func (x *ListLockLeasesByProcessIdResponse) GetLeases() []*Lease {
	if x != nil {
		return x.Leases
	}
	return nil
}

func (x *ListLockLeasesByProcessIdResponse) GetNextPaginationToken() *PaginationToken {
	if x != nil {
		return x.NextPaginationToken
	}
	return nil
}

func (x *ListLockLeasesByProcessIdResponse) GetPreviousPaginationToken() *PaginationToken {
	if x != nil {
		return x.PreviousPaginationToken
	}
	return nil
}

type Lock struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          *LockId                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State       LockState              `protobuf:"varint,2,opt,name=state,proto3,enum=com.evrblk.grackle.corepb.LockState" json:"state,omitempty"`
	LockedAt    int64                  `protobuf:"fixed64,3,opt,name=locked_at,json=lockedAt,proto3" json:"locked_at,omitempty"`
	LockHolders []*LockHolder          `protobuf:"bytes,4,rep,name=lock_holders,json=lockHolders,proto3" json:"lock_holders,omitempty"`
	// last_activity_at is the timestamp (ns) of the most recent activity on this
	// lock (an acquire attempt or a release). Not affected by reads.
	LastActivityAt int64 `protobuf:"fixed64,5,opt,name=last_activity_at,json=lastActivityAt,proto3" json:"last_activity_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Lock) Reset() {
	*x = Lock{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lock) ProtoMessage() {}

func (x *Lock) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lock.ProtoReflect.Descriptor instead.
func (*Lock) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{28}
}

func (x *Lock) GetId() *LockId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Lock) GetState() LockState {
	if x != nil {
		return x.State
	}
	return LockState_LOCK_STATE_INVALID
}

func (x *Lock) GetLockedAt() int64 {
	if x != nil {
		return x.LockedAt
	}
	return 0
}

func (x *Lock) GetLockHolders() []*LockHolder {
	if x != nil {
		return x.LockHolders
	}
	return nil
}

func (x *Lock) GetLastActivityAt() int64 {
	if x != nil {
		return x.LastActivityAt
	}
	return 0
}

type LockHolder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       uint64                 `protobuf:"fixed64,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	LockedAt      int64                  `protobuf:"fixed64,2,opt,name=locked_at,json=lockedAt,proto3" json:"locked_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockHolder) Reset() {
	*x = LockHolder{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockHolder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockHolder) ProtoMessage() {}

func (x *LockHolder) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockHolder.ProtoReflect.Descriptor instead.
func (*LockHolder) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{29}
}

func (x *LockHolder) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

func (x *LockHolder) GetLockedAt() int64 {
	if x != nil {
		return x.LockedAt
	}
	return 0
}

func (x *LockHolder) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type LockId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint64                 `protobuf:"fixed64,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	NamespaceId   uint64                 `protobuf:"fixed64,2,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	LockName      string                 `protobuf:"bytes,3,opt,name=lock_name,json=lockName,proto3" json:"lock_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockId) Reset() {
	*x = LockId{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockId) ProtoMessage() {}

func (x *LockId) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockId.ProtoReflect.Descriptor instead.
func (*LockId) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{30}
}

func (x *LockId) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *LockId) GetNamespaceId() uint64 {
	if x != nil {
		return x.NamespaceId
	}
	return 0
}

func (x *LockId) GetLockName() string {
	if x != nil {
		return x.LockName
	}
	return ""
}

type LocksCounter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NumberOfLocks  int64                  `protobuf:"varint,1,opt,name=number_of_locks,json=numberOfLocks,proto3" json:"number_of_locks,omitempty"`
	NumberOfLeases int64                  `protobuf:"varint,2,opt,name=number_of_leases,json=numberOfLeases,proto3" json:"number_of_leases,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocksCounter) Reset() {
	*x = LocksCounter{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocksCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocksCounter) ProtoMessage() {}

func (x *LocksCounter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocksCounter.ProtoReflect.Descriptor instead.
func (*LocksCounter) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{31}
}

func (x *LocksCounter) GetNumberOfLocks() int64 {
	if x != nil {
		return x.NumberOfLocks
	}
	return 0
}

func (x *LocksCounter) GetNumberOfLeases() int64 {
	if x != nil {
		return x.NumberOfLeases
	}
	return 0
}

type LocksGarbageCollectionRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	NamespaceId   *NamespaceId           `protobuf:"bytes,2,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocksGarbageCollectionRecord) Reset() {
	*x = LocksGarbageCollectionRecord{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocksGarbageCollectionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocksGarbageCollectionRecord) ProtoMessage() {}

func (x *LocksGarbageCollectionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocksGarbageCollectionRecord.ProtoReflect.Descriptor instead.
func (*LocksGarbageCollectionRecord) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{32}
}

func (x *LocksGarbageCollectionRecord) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LocksGarbageCollectionRecord) GetNamespaceId() *NamespaceId {
	if x != nil {
		return x.NamespaceId
	}
	return nil
}

type LockAncestor struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             *LockId                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExclusiveCount int64                  `protobuf:"varint,2,opt,name=exclusive_count,json=exclusiveCount,proto3" json:"exclusive_count,omitempty"`
	SharedCount    int64                  `protobuf:"varint,3,opt,name=shared_count,json=sharedCount,proto3" json:"shared_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LockAncestor) Reset() {
	*x = LockAncestor{}
	mi := &file_pkg_corepb_locks_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockAncestor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockAncestor) ProtoMessage() {}

func (x *LockAncestor) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_locks_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockAncestor.ProtoReflect.Descriptor instead.
func (*LockAncestor) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_locks_proto_rawDescGZIP(), []int{33}
}

func (x *LockAncestor) GetId() *LockId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *LockAncestor) GetExclusiveCount() int64 {
	if x != nil {
		return x.ExclusiveCount
	}
	return 0
}

func (x *LockAncestor) GetSharedCount() int64 {
	if x != nil {
		return x.SharedCount
	}
	return 0
}

var File_pkg_corepb_locks_proto protoreflect.FileDescriptor

const file_pkg_corepb_locks_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/corepb/locks.proto\x12\x19com.evrblk.grackle.corepb\x1a\x17pkg/corepb/common.proto\x1a\x1bpkg/corepb/namespaces.proto\"\xfa\x02\n" +
	"\x12AcquireLockRequest\x12:\n" +
	"\alock_id\x18\x01 \x01(\v2!.com.evrblk.grackle.corepb.LockIdR\x06lockId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\x06R\aleaseId\x12\x1c\n" +
	"\texclusive\x18\x03 \x01(\bR\texclusive\x12W\n" +
	"\bmetadata\x18\x04 \x03(\v2;.com.evrblk.grackle.corepb.AcquireLockRequest.MetadataEntryR\bmetadata\x12\x10\n" +
	"\x03now\x18\x05 \x01(\x10R\x03now\x12G\n" +
	"!max_number_of_locks_per_namespace\x18\x06 \x01(\x03R\x1cmaxNumberOfLocksPerNamespace\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\x13AcquireLockResponse\x123\n" +
	"\x04lock\x18\x01 \x01(\v2\x1f.com.evrblk.grackle.corepb.LockR\x04lock\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"}\n" +
	"\x12ReleaseLockRequest\x12:\n" +
	"\alock_id\x18\x01 \x01(\v2!.com.evrblk.grackle.corepb.LockIdR\x06lockId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\x06R\aleaseId\x12\x10\n" +
	"\x03now\x18\x03 \x01(\x10R\x03now\"J\n" +
	"\x13ReleaseLockResponse\x123\n" +
	"\x04lock\x18\x01 \x01(\v2\x1f.com.evrblk.grackle.corepb.LockR\x04lock\"^\n" +
	"\x0eGetLockRequest\x12:\n" +
	"\alock_id\x18\x01 \x01(\v2!.com.evrblk.grackle.corepb.LockIdR\x06lockId\x12\x10\n" +
	"\x03now\x18\x02 \x01(\x10R\x03now\"F\n" +
	"\x0fGetLockResponse\x123\n" +
	"\x04lock\x18\x01 \x01(\v2\x1f.com.evrblk.grackle.corepb.LockR\x04lock\"a\n" +
	"\x11DeleteLockRequest\x12:\n" +
	"\alock_id\x18\x01 \x01(\v2!.com.evrblk.grackle.corepb.LockIdR\x06lockId\x12\x10\n" +
	"\x03now\x18\x02 \x01(\x10R\x03now\"\x14\n" +
	"\x12DeleteLockResponse\"\xdc\x01\n" +
	"\x10ListLocksRequest\x12I\n" +
	"\fnamespace_id\x18\x01 \x01(\v2&.com.evrblk.grackle.corepb.NamespaceIdR\vnamespaceId\x12\x10\n" +
	"\x03now\x18\x02 \x01(\x10R\x03now\x12U\n" +
	"\x10pagination_token\x18\x03 \x01(\v2*.com.evrblk.grackle.corepb.PaginationTokenR\x0fpaginationToken\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x92\x02\n" +
	"\x11ListLocksResponse\x125\n" +
	"\x05locks\x18\x01 \x03(\v2\x1f.com.evrblk.grackle.corepb.LockR\x05locks\x12^\n" +
	"\x15next_pagination_token\x18\x02 \x01(\v2*.com.evrblk.grackle.corepb.PaginationTokenR\x13nextPaginationToken\x12f\n" +
	"\x19previous_pagination_token\x18\x03 \x01(\v2*.com.evrblk.grackle.corepb.PaginationTokenR\x17previousPaginationToken\"\xd9\x01\n" +
	"\x19ListLocksByLeaseIdRequest\x12=\n" +
	"\blease_id\x18\x01 \x01(\v2\".com.evrblk.grackle.corepb.LeaseIdR\aleaseId\x12\x10\n" +
	"\x03now\x18\x02 \x01(\x10R\x03now\x12U\n" +
	"\x10pagination_token\x18\x03 \x01(\v2*.com.evrblk.grackle.corepb.PaginationTokenR\x0fpaginationToken\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x9b\x02\n" +
	"\x1aListLocksByLeaseIdResponse\x125\n" +
	"\x05locks\x18\x01 \x03(\v2\x1f.com.evrblk.grackle.corepb.LockR\x05locks\x12^\n" +
	"\x15next_pagination_token\x18\x02 \x01(\v2*.com.evrblk.grackle.corepb.PaginationTokenR\x13nextPaginationToken\x12f\n" +
	"\x19previous_pagination_token\x18\x03 \x01(\v2*.com.evrblk.grackle.corepb.PaginationTokenR\x17previousPaginationToken\"\xcb\x01\n" +
	" RunLocksGarbageCollectionRequest\x12\x10\n" +
	"\x03now\x18\x01 \x01(\x10R\x03now\x12/\n" +
	"\x14gc_records_page_size\x18\x02 \x01(\x03R\x11gcRecordsPageSize\x128\n" +
	"\x19gc_record_locks_page_size\x18\x03 \x01(\x03R\x15gcRecordLocksPageSize\x12*\n" +
	"\x11max_visited_locks\x18\x04 \x01(\x03R\x0fmaxVisitedLocks\"#\n" +
	"!RunLocksGarbageCollectionResponse\"\x97\x01\n" +
	"\x1bLocksDeleteNamespaceRequest\x12I\n" +
	"\fnamespace_id\x18\x01 \x01(\v2&.com.evrblk.grackle.corepb.NamespaceIdR\vnamespaceId\x12\x1b\n" +
	"\trecord_id\x18\x02 \x01(\x06R\brecordId\x12\x10\n" +
	"\x03now\x18\x03 \x01(\x10R\x03now\"\x1e\n" +
	"\x1cLocksDeleteNamespaceResponse\"\xfd\x02\n" +
	"\x16CreateLockLeaseRequest\x12=\n" +
	"\blease_id\x18\x01 \x01(\v2\".com.evrblk.grackle.corepb.LeaseIdR\aleaseId\x12\x1d\n" +
	"\n" +
	"process_id\x18\x02 \x01(\tR\tprocessId\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\x12\x10\n" +
	"\x03now\x18\x04 \x01(\x10R\x03now\x12[\n" +
	"\bmetadata\x18\x05 \x03(\v2?.com.evrblk.grackle.corepb.CreateLockLeaseRequest.MetadataEntryR\bmetadata\x128\n" +
	"\x19max_number_of_lock_leases\x18\x06 \x01(\x03R\x15maxNumberOfLockLeases\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x17CreateLockLeaseResponse\x126\n" +
	"\x05lease\x18\x01 \x01(\v2 .com.evrblk.grackle.corepb.LeaseR\x05lease\"i\n" +
	"\x16RevokeLockLeaseRequest\x12=\n" +
	"\blease_id\x18\x01 \x01(\v2\".com.evrblk.grackle.corepb.LeaseIdR\aleaseId\x12\x10\n" +
	"\x03now\x18\x02 \x01(\x10R\x03now\"\x19\n" +
	"\x17RevokeLockLeaseResponse\"\x8b\x01\n" +
	"\x17RefreshLockLeaseRequest\x12=\n" +
	"\blease_id\x18\x01 \x01(\v2\".com.evrblk.grackle.corepb.LeaseIdR\aleaseId\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\x12\x10\n" +
	"\x03now\x18\x03 \x01(\x10R\x03now\"R\n" +
	"\x18RefreshLockLeaseResponse\x126\n" +
	"\x05lease\x18\x01 \x01(\v2 .com.evrblk.grackle.corepb.LeaseR\x05lease\"f\n" +
	"\x13GetLockLeaseRequest\x12=\n" +
	"\blease_id\x18\x01 \x01(\v2\".com.evrblk.grackle.corepb.LeaseIdR\aleaseId\x12\x10\n" +
	"\x03now\x18\x02 \x01(\x10R\x03now\"N\n" +
	"\x14GetLockLeaseResponse\x126\n" +
	"\x05lease\x18\x01 \x01(\v2 .com.evrblk.grackle.corepb.LeaseR\x05lease\"\xe1\x01\n" +
	"\x15ListLockLeasesRequest\x12I\n" +
	"\fnamespace_id\x18\x01 \x01(\v2&.com.evrblk.grackle.corepb.NamespaceIdR\vnamespaceId\x12\x10\n" +
	"\x03now\x18\x02 \x01(\x10R\x03now\x12U\n" +
	"\x10pagination_token\x18\x03 \x01(\v2*.com.evrblk.grackle.corepb.PaginationTokenR\x0fpaginationToken\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x9a\x02\n" +
	"\x16ListLockLeasesResponse\x128\n" +
	"\x06leases\x18\x01 \x03(\v2 .com.evrblk.grackle.corepb.LeaseR\x06leases\x12^\n" +
	"\x15next_pagination_token\x18\x02 \x01(\v2*.com.evrblk.grackle.corepb.PaginationTokenR\x13nextPaginationToken\x12f\n" +
	"\x19previous_pagination_token\x18\x03 \x01(\v2*.com.evrblk.grackle.corepb.PaginationTokenR\x17previousPaginationToken\"\x8b\x02\n" +
	" ListLockLeasesByProcessIdRequest\x12I\n" +
	"\fnamespace_id\x18\x01 \x01(\v2&.com.evrblk.grackle.corepb.NamespaceIdR\vnamespaceId\x12\x1d\n" +
	"\n" +
	"process_id\x18\x02 \x01(\tR\tprocessId\x12\x10\n" +
	"\x03now\x18\x03 \x01(\x10R\x03now\x12U\n" +
	"\x10pagination_token\x18\x04 \x01(\v2*.com.evrblk.grackle.corepb.PaginationTokenR\x0fpaginationToken\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\xa5\x02\n" +
	"!ListLockLeasesByProcessIdResponse\x128\n" +
	"\x06leases\x18\x01 \x03(\v2 .com.evrblk.grackle.corepb.LeaseR\x06leases\x12^\n" +
	"\x15next_pagination_token\x18\x02 \x01(\v2*.com.evrblk.grackle.corepb.PaginationTokenR\x13nextPaginationToken\x12f\n" +
	"\x19previous_pagination_token\x18\x03 \x01(\v2*.com.evrblk.grackle.corepb.PaginationTokenR\x17previousPaginationToken\"\x86\x02\n" +
	"\x04Lock\x121\n" +
	"\x02id\x18\x01 \x01(\v2!.com.evrblk.grackle.corepb.LockIdR\x02id\x12:\n" +
	"\x05state\x18\x02 \x01(\x0e2$.com.evrblk.grackle.corepb.LockStateR\x05state\x12\x1b\n" +
	"\tlocked_at\x18\x03 \x01(\x10R\blockedAt\x12H\n" +
	"\flock_holders\x18\x04 \x03(\v2%.com.evrblk.grackle.corepb.LockHolderR\vlockHolders\x12(\n" +
	"\x10last_activity_at\x18\x05 \x01(\x10R\x0elastActivityAt\"\xd2\x01\n" +
	"\n" +
	"LockHolder\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\x06R\aleaseId\x12\x1b\n" +
	"\tlocked_at\x18\x02 \x01(\x10R\blockedAt\x12O\n" +
	"\bmetadata\x18\x03 \x03(\v23.com.evrblk.grackle.corepb.LockHolder.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\x06LockId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x06R\taccountId\x12!\n" +
	"\fnamespace_id\x18\x02 \x01(\x06R\vnamespaceId\x12\x1b\n" +
	"\tlock_name\x18\x03 \x01(\tR\blockName\"`\n" +
	"\fLocksCounter\x12&\n" +
	"\x0fnumber_of_locks\x18\x01 \x01(\x03R\rnumberOfLocks\x12(\n" +
	"\x10number_of_leases\x18\x02 \x01(\x03R\x0enumberOfLeases\"y\n" +
	"\x1cLocksGarbageCollectionRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x06R\x02id\x12I\n" +
	"\fnamespace_id\x18\x02 \x01(\v2&.com.evrblk.grackle.corepb.NamespaceIdR\vnamespaceId\"\x8d\x01\n" +
	"\fLockAncestor\x121\n" +
	"\x02id\x18\x01 \x01(\v2!.com.evrblk.grackle.corepb.LockIdR\x02id\x12'\n" +
	"\x0fexclusive_count\x18\x02 \x01(\x03R\x0eexclusiveCount\x12!\n" +
	"\fshared_count\x18\x03 \x01(\x03R\vsharedCount*{\n" +
	"\tLockState\x12\x16\n" +
	"\x12LOCK_STATE_INVALID\x10\x00\x12\x17\n" +
	"\x13LOCK_STATE_UNLOCKED\x10\x01\x12\x1c\n" +
	"\x18LOCK_STATE_SHARED_LOCKED\x10\x02\x12\x1f\n" +
	"\x1bLOCK_STATE_EXCLUSIVE_LOCKED\x10\x03B&Z$github.com/evrblk/grackle/pkg/corepbb\x06proto3"

var (
	file_pkg_corepb_locks_proto_rawDescOnce sync.Once
	file_pkg_corepb_locks_proto_rawDescData []byte
)

func file_pkg_corepb_locks_proto_rawDescGZIP() []byte {
	file_pkg_corepb_locks_proto_rawDescOnce.Do(func() {
		file_pkg_corepb_locks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_corepb_locks_proto_rawDesc), len(file_pkg_corepb_locks_proto_rawDesc)))
	})
	return file_pkg_corepb_locks_proto_rawDescData
}

var file_pkg_corepb_locks_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_corepb_locks_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_pkg_corepb_locks_proto_goTypes = []any{
	(LockState)(0),                            // 0: com.evrblk.grackle.corepb.LockState
	(*AcquireLockRequest)(nil),                // 1: com.evrblk.grackle.corepb.AcquireLockRequest
	(*AcquireLockResponse)(nil),               // 2: com.evrblk.grackle.corepb.AcquireLockResponse
	(*ReleaseLockRequest)(nil),                // 3: com.evrblk.grackle.corepb.ReleaseLockRequest
	(*ReleaseLockResponse)(nil),               // 4: com.evrblk.grackle.corepb.ReleaseLockResponse
	(*GetLockRequest)(nil),                    // 5: com.evrblk.grackle.corepb.GetLockRequest
	(*GetLockResponse)(nil),                   // 6: com.evrblk.grackle.corepb.GetLockResponse
	(*DeleteLockRequest)(nil),                 // 7: com.evrblk.grackle.corepb.DeleteLockRequest
	(*DeleteLockResponse)(nil),                // 8: com.evrblk.grackle.corepb.DeleteLockResponse
	(*ListLocksRequest)(nil),                  // 9: com.evrblk.grackle.corepb.ListLocksRequest
	(*ListLocksResponse)(nil),                 // 10: com.evrblk.grackle.corepb.ListLocksResponse
	(*ListLocksByLeaseIdRequest)(nil),         // 11: com.evrblk.grackle.corepb.ListLocksByLeaseIdRequest
	(*ListLocksByLeaseIdResponse)(nil),        // 12: com.evrblk.grackle.corepb.ListLocksByLeaseIdResponse
	(*RunLocksGarbageCollectionRequest)(nil),  // 13: com.evrblk.grackle.corepb.RunLocksGarbageCollectionRequest
	(*RunLocksGarbageCollectionResponse)(nil), // 14: com.evrblk.grackle.corepb.RunLocksGarbageCollectionResponse
	(*LocksDeleteNamespaceRequest)(nil),       // 15: com.evrblk.grackle.corepb.LocksDeleteNamespaceRequest
	(*LocksDeleteNamespaceResponse)(nil),      // 16: com.evrblk.grackle.corepb.LocksDeleteNamespaceResponse
	(*CreateLockLeaseRequest)(nil),            // 17: com.evrblk.grackle.corepb.CreateLockLeaseRequest
	(*CreateLockLeaseResponse)(nil),           // 18: com.evrblk.grackle.corepb.CreateLockLeaseResponse
	(*RevokeLockLeaseRequest)(nil),            // 19: com.evrblk.grackle.corepb.RevokeLockLeaseRequest
	(*RevokeLockLeaseResponse)(nil),           // 20: com.evrblk.grackle.corepb.RevokeLockLeaseResponse
	(*RefreshLockLeaseRequest)(nil),           // 21: com.evrblk.grackle.corepb.RefreshLockLeaseRequest
	(*RefreshLockLeaseResponse)(nil),          // 22: com.evrblk.grackle.corepb.RefreshLockLeaseResponse
	(*GetLockLeaseRequest)(nil),               // 23: com.evrblk.grackle.corepb.GetLockLeaseRequest
	(*GetLockLeaseResponse)(nil),              // 24: com.evrblk.grackle.corepb.GetLockLeaseResponse
	(*ListLockLeasesRequest)(nil),             // 25: com.evrblk.grackle.corepb.ListLockLeasesRequest
	(*ListLockLeasesResponse)(nil),            // 26: com.evrblk.grackle.corepb.ListLockLeasesResponse
	(*ListLockLeasesByProcessIdRequest)(nil),  // 27: com.evrblk.grackle.corepb.ListLockLeasesByProcessIdRequest
	(*ListLockLeasesByProcessIdResponse)(nil), // 28: com.evrblk.grackle.corepb.ListLockLeasesByProcessIdResponse
	(*Lock)(nil),                              // 29: com.evrblk.grackle.corepb.Lock
	(*LockHolder)(nil),                        // 30: com.evrblk.grackle.corepb.LockHolder
	(*LockId)(nil),                            // 31: com.evrblk.grackle.corepb.LockId
	(*LocksCounter)(nil),                      // 32: com.evrblk.grackle.corepb.LocksCounter
	(*LocksGarbageCollectionRecord)(nil),      // 33: com.evrblk.grackle.corepb.LocksGarbageCollectionRecord
	(*LockAncestor)(nil),                      // 34: com.evrblk.grackle.corepb.LockAncestor
	nil,                                       // 35: com.evrblk.grackle.corepb.AcquireLockRequest.MetadataEntry
	nil,                                       // 36: com.evrblk.grackle.corepb.CreateLockLeaseRequest.MetadataEntry
	nil,                                       // 37: com.evrblk.grackle.corepb.LockHolder.MetadataEntry
	(*NamespaceId)(nil),                       // 38: com.evrblk.grackle.corepb.NamespaceId
	(*PaginationToken)(nil),                   // 39: com.evrblk.grackle.corepb.PaginationToken
	(*LeaseId)(nil),                           // 40: com.evrblk.grackle.corepb.LeaseId
	(*Lease)(nil),                             // 41: com.evrblk.grackle.corepb.Lease
}
var file_pkg_corepb_locks_proto_depIdxs = []int32{
	31, // 0: com.evrblk.grackle.corepb.AcquireLockRequest.lock_id:type_name -> com.evrblk.grackle.corepb.LockId
	35, // 1: com.evrblk.grackle.corepb.AcquireLockRequest.metadata:type_name -> com.evrblk.grackle.corepb.AcquireLockRequest.MetadataEntry
	29, // 2: com.evrblk.grackle.corepb.AcquireLockResponse.lock:type_name -> com.evrblk.grackle.corepb.Lock
	31, // 3: com.evrblk.grackle.corepb.ReleaseLockRequest.lock_id:type_name -> com.evrblk.grackle.corepb.LockId
	29, // 4: com.evrblk.grackle.corepb.ReleaseLockResponse.lock:type_name -> com.evrblk.grackle.corepb.Lock
	31, // 5: com.evrblk.grackle.corepb.GetLockRequest.lock_id:type_name -> com.evrblk.grackle.corepb.LockId
	29, // 6: com.evrblk.grackle.corepb.GetLockResponse.lock:type_name -> com.evrblk.grackle.corepb.Lock
	31, // 7: com.evrblk.grackle.corepb.DeleteLockRequest.lock_id:type_name -> com.evrblk.grackle.corepb.LockId
	38, // 8: com.evrblk.grackle.corepb.ListLocksRequest.namespace_id:type_name -> com.evrblk.grackle.corepb.NamespaceId
	39, // 9: com.evrblk.grackle.corepb.ListLocksRequest.pagination_token:type_name -> com.evrblk.grackle.corepb.PaginationToken
	29, // 10: com.evrblk.grackle.corepb.ListLocksResponse.locks:type_name -> com.evrblk.grackle.corepb.Lock
	39, // 11: com.evrblk.grackle.corepb.ListLocksResponse.next_pagination_token:type_name -> com.evrblk.grackle.corepb.PaginationToken
	39, // 12: com.evrblk.grackle.corepb.ListLocksResponse.previous_pagination_token:type_name -> com.evrblk.grackle.corepb.PaginationToken
	40, // 13: com.evrblk.grackle.corepb.ListLocksByLeaseIdRequest.lease_id:type_name -> com.evrblk.grackle.corepb.LeaseId
	39, // 14: com.evrblk.grackle.corepb.ListLocksByLeaseIdRequest.pagination_token:type_name -> com.evrblk.grackle.corepb.PaginationToken
	29, // 15: com.evrblk.grackle.corepb.ListLocksByLeaseIdResponse.locks:type_name -> com.evrblk.grackle.corepb.Lock
	39, // 16: com.evrblk.grackle.corepb.ListLocksByLeaseIdResponse.next_pagination_token:type_name -> com.evrblk.grackle.corepb.PaginationToken
	39, // 17: com.evrblk.grackle.corepb.ListLocksByLeaseIdResponse.previous_pagination_token:type_name -> com.evrblk.grackle.corepb.PaginationToken
	38, // 18: com.evrblk.grackle.corepb.LocksDeleteNamespaceRequest.namespace_id:type_name -> com.evrblk.grackle.corepb.NamespaceId
	40, // 19: com.evrblk.grackle.corepb.CreateLockLeaseRequest.lease_id:type_name -> com.evrblk.grackle.corepb.LeaseId
	36, // 20: com.evrblk.grackle.corepb.CreateLockLeaseRequest.metadata:type_name -> com.evrblk.grackle.corepb.CreateLockLeaseRequest.MetadataEntry
	41, // 21: com.evrblk.grackle.corepb.CreateLockLeaseResponse.lease:type_name -> com.evrblk.grackle.corepb.Lease
	40, // 22: com.evrblk.grackle.corepb.RevokeLockLeaseRequest.lease_id:type_name -> com.evrblk.grackle.corepb.LeaseId
	40, // 23: com.evrblk.grackle.corepb.RefreshLockLeaseRequest.lease_id:type_name -> com.evrblk.grackle.corepb.LeaseId
	41, // 24: com.evrblk.grackle.corepb.RefreshLockLeaseResponse.lease:type_name -> com.evrblk.grackle.corepb.Lease
	40, // 25: com.evrblk.grackle.corepb.GetLockLeaseRequest.lease_id:type_name -> com.evrblk.grackle.corepb.LeaseId
	41, // 26: com.evrblk.grackle.corepb.GetLockLeaseResponse.lease:type_name -> com.evrblk.grackle.corepb.Lease
	38, // 27: com.evrblk.grackle.corepb.ListLockLeasesRequest.namespace_id:type_name -> com.evrblk.grackle.corepb.NamespaceId
	39, // 28: com.evrblk.grackle.corepb.ListLockLeasesRequest.pagination_token:type_name -> com.evrblk.grackle.corepb.PaginationToken
	41, // 29: com.evrblk.grackle.corepb.ListLockLeasesResponse.leases:type_name -> com.evrblk.grackle.corepb.Lease
	39, // 30: com.evrblk.grackle.corepb.ListLockLeasesResponse.next_pagination_token:type_name -> com.evrblk.grackle.corepb.PaginationToken
	39, // 31: com.evrblk.grackle.corepb.ListLockLeasesResponse.previous_pagination_token:type_name -> com.evrblk.grackle.corepb.PaginationToken
	38, // 32: com.evrblk.grackle.corepb.ListLockLeasesByProcessIdRequest.namespace_id:type_name -> com.evrblk.grackle.corepb.NamespaceId
	39, // 33: com.evrblk.grackle.corepb.ListLockLeasesByProcessIdRequest.pagination_token:type_name -> com.evrblk.grackle.corepb.PaginationToken
	41, // 34: com.evrblk.grackle.corepb.ListLockLeasesByProcessIdResponse.leases:type_name -> com.evrblk.grackle.corepb.Lease
	39, // 35: com.evrblk.grackle.corepb.ListLockLeasesByProcessIdResponse.next_pagination_token:type_name -> com.evrblk.grackle.corepb.PaginationToken
	39, // 36: com.evrblk.grackle.corepb.ListLockLeasesByProcessIdResponse.previous_pagination_token:type_name -> com.evrblk.grackle.corepb.PaginationToken
	31, // 37: com.evrblk.grackle.corepb.Lock.id:type_name -> com.evrblk.grackle.corepb.LockId
	0,  // 38: com.evrblk.grackle.corepb.Lock.state:type_name -> com.evrblk.grackle.corepb.LockState
	30, // 39: com.evrblk.grackle.corepb.Lock.lock_holders:type_name -> com.evrblk.grackle.corepb.LockHolder
	37, // 40: com.evrblk.grackle.corepb.LockHolder.metadata:type_name -> com.evrblk.grackle.corepb.LockHolder.MetadataEntry
	38, // 41: com.evrblk.grackle.corepb.LocksGarbageCollectionRecord.namespace_id:type_name -> com.evrblk.grackle.corepb.NamespaceId
	31, // 42: com.evrblk.grackle.corepb.LockAncestor.id:type_name -> com.evrblk.grackle.corepb.LockId
	43, // [43:43] is the sub-list for method output_type
	43, // [43:43] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_pkg_corepb_locks_proto_init() }
func file_pkg_corepb_locks_proto_init() {
	if File_pkg_corepb_locks_proto != nil {
		return
	}
	file_pkg_corepb_common_proto_init()
	file_pkg_corepb_namespaces_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_corepb_locks_proto_rawDesc), len(file_pkg_corepb_locks_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_corepb_locks_proto_goTypes,
		DependencyIndexes: file_pkg_corepb_locks_proto_depIdxs,
		EnumInfos:         file_pkg_corepb_locks_proto_enumTypes,
		MessageInfos:      file_pkg_corepb_locks_proto_msgTypes,
	}.Build()
	File_pkg_corepb_locks_proto = out.File
	file_pkg_corepb_locks_proto_goTypes = nil
	file_pkg_corepb_locks_proto_depIdxs = nil
}
