// Code generated by genmarshal. DO NOT EDIT.

package corepb

import "encoding"

// AcquireLockRequest

var _ encoding.BinaryMarshaler = (*AcquireLockRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*AcquireLockRequest)(nil)

func (m *AcquireLockRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *AcquireLockRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// AcquireLockResponse

var _ encoding.BinaryMarshaler = (*AcquireLockResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*AcquireLockResponse)(nil)

func (m *AcquireLockResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *AcquireLockResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// AcquireSemaphoreRequest

var _ encoding.BinaryMarshaler = (*AcquireSemaphoreRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*AcquireSemaphoreRequest)(nil)

func (m *AcquireSemaphoreRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *AcquireSemaphoreRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// AcquireSemaphoreResponse

var _ encoding.BinaryMarshaler = (*AcquireSemaphoreResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*AcquireSemaphoreResponse)(nil)

func (m *AcquireSemaphoreResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *AcquireSemaphoreResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// AddJobsToWaitGroupRequest

var _ encoding.BinaryMarshaler = (*AddJobsToWaitGroupRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*AddJobsToWaitGroupRequest)(nil)

func (m *AddJobsToWaitGroupRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *AddJobsToWaitGroupRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// AddJobsToWaitGroupResponse

var _ encoding.BinaryMarshaler = (*AddJobsToWaitGroupResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*AddJobsToWaitGroupResponse)(nil)

func (m *AddJobsToWaitGroupResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *AddJobsToWaitGroupResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ArriveAtBarrierRequest

var _ encoding.BinaryMarshaler = (*ArriveAtBarrierRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ArriveAtBarrierRequest)(nil)

func (m *ArriveAtBarrierRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ArriveAtBarrierRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ArriveAtBarrierResponse

var _ encoding.BinaryMarshaler = (*ArriveAtBarrierResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ArriveAtBarrierResponse)(nil)

func (m *ArriveAtBarrierResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ArriveAtBarrierResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// Barrier

var _ encoding.BinaryMarshaler = (*Barrier)(nil)
var _ encoding.BinaryUnmarshaler = (*Barrier)(nil)

func (m *Barrier) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *Barrier) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// BarrierId

var _ encoding.BinaryMarshaler = (*BarrierId)(nil)
var _ encoding.BinaryUnmarshaler = (*BarrierId)(nil)

func (m *BarrierId) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *BarrierId) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// BarrierParticipant

var _ encoding.BinaryMarshaler = (*BarrierParticipant)(nil)
var _ encoding.BinaryUnmarshaler = (*BarrierParticipant)(nil)

func (m *BarrierParticipant) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *BarrierParticipant) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// BarriersCounter

var _ encoding.BinaryMarshaler = (*BarriersCounter)(nil)
var _ encoding.BinaryUnmarshaler = (*BarriersCounter)(nil)

func (m *BarriersCounter) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *BarriersCounter) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// BarriersDeleteNamespaceRequest

var _ encoding.BinaryMarshaler = (*BarriersDeleteNamespaceRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*BarriersDeleteNamespaceRequest)(nil)

func (m *BarriersDeleteNamespaceRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *BarriersDeleteNamespaceRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// BarriersDeleteNamespaceResponse

var _ encoding.BinaryMarshaler = (*BarriersDeleteNamespaceResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*BarriersDeleteNamespaceResponse)(nil)

func (m *BarriersDeleteNamespaceResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *BarriersDeleteNamespaceResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// BarriersExpirationRecord

var _ encoding.BinaryMarshaler = (*BarriersExpirationRecord)(nil)
var _ encoding.BinaryUnmarshaler = (*BarriersExpirationRecord)(nil)

func (m *BarriersExpirationRecord) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *BarriersExpirationRecord) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// BarriersGarbageCollectionRecord

var _ encoding.BinaryMarshaler = (*BarriersGarbageCollectionRecord)(nil)
var _ encoding.BinaryUnmarshaler = (*BarriersGarbageCollectionRecord)(nil)

func (m *BarriersGarbageCollectionRecord) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *BarriersGarbageCollectionRecord) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// CompleteJobsFromWaitGroupRequest

var _ encoding.BinaryMarshaler = (*CompleteJobsFromWaitGroupRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*CompleteJobsFromWaitGroupRequest)(nil)

func (m *CompleteJobsFromWaitGroupRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *CompleteJobsFromWaitGroupRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// CompleteJobsFromWaitGroupResponse

var _ encoding.BinaryMarshaler = (*CompleteJobsFromWaitGroupResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*CompleteJobsFromWaitGroupResponse)(nil)

func (m *CompleteJobsFromWaitGroupResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *CompleteJobsFromWaitGroupResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// CreateBarrierRequest

var _ encoding.BinaryMarshaler = (*CreateBarrierRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*CreateBarrierRequest)(nil)

func (m *CreateBarrierRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *CreateBarrierRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// CreateBarrierResponse

var _ encoding.BinaryMarshaler = (*CreateBarrierResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*CreateBarrierResponse)(nil)

func (m *CreateBarrierResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *CreateBarrierResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// CreateLockLeaseRequest

var _ encoding.BinaryMarshaler = (*CreateLockLeaseRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*CreateLockLeaseRequest)(nil)

func (m *CreateLockLeaseRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *CreateLockLeaseRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// CreateLockLeaseResponse

var _ encoding.BinaryMarshaler = (*CreateLockLeaseResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*CreateLockLeaseResponse)(nil)

func (m *CreateLockLeaseResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *CreateLockLeaseResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// CreateNamespaceRequest

var _ encoding.BinaryMarshaler = (*CreateNamespaceRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*CreateNamespaceRequest)(nil)

func (m *CreateNamespaceRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *CreateNamespaceRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// CreateNamespaceResponse

var _ encoding.BinaryMarshaler = (*CreateNamespaceResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*CreateNamespaceResponse)(nil)

func (m *CreateNamespaceResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *CreateNamespaceResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// CreateSemaphoreLeaseRequest

var _ encoding.BinaryMarshaler = (*CreateSemaphoreLeaseRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*CreateSemaphoreLeaseRequest)(nil)

func (m *CreateSemaphoreLeaseRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *CreateSemaphoreLeaseRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// CreateSemaphoreLeaseResponse

var _ encoding.BinaryMarshaler = (*CreateSemaphoreLeaseResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*CreateSemaphoreLeaseResponse)(nil)

func (m *CreateSemaphoreLeaseResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *CreateSemaphoreLeaseResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// CreateSemaphoreRequest

var _ encoding.BinaryMarshaler = (*CreateSemaphoreRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*CreateSemaphoreRequest)(nil)

func (m *CreateSemaphoreRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *CreateSemaphoreRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// CreateSemaphoreResponse

var _ encoding.BinaryMarshaler = (*CreateSemaphoreResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*CreateSemaphoreResponse)(nil)

func (m *CreateSemaphoreResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *CreateSemaphoreResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// CreateWaitGroupRequest

var _ encoding.BinaryMarshaler = (*CreateWaitGroupRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*CreateWaitGroupRequest)(nil)

func (m *CreateWaitGroupRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *CreateWaitGroupRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// CreateWaitGroupResponse

var _ encoding.BinaryMarshaler = (*CreateWaitGroupResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*CreateWaitGroupResponse)(nil)

func (m *CreateWaitGroupResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *CreateWaitGroupResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DeleteBarrierRequest

var _ encoding.BinaryMarshaler = (*DeleteBarrierRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*DeleteBarrierRequest)(nil)

func (m *DeleteBarrierRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DeleteBarrierRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DeleteBarrierResponse

var _ encoding.BinaryMarshaler = (*DeleteBarrierResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*DeleteBarrierResponse)(nil)

func (m *DeleteBarrierResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DeleteBarrierResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DeleteLockRequest

var _ encoding.BinaryMarshaler = (*DeleteLockRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*DeleteLockRequest)(nil)

func (m *DeleteLockRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DeleteLockRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DeleteLockResponse

var _ encoding.BinaryMarshaler = (*DeleteLockResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*DeleteLockResponse)(nil)

func (m *DeleteLockResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DeleteLockResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DeleteNamespaceRequest

var _ encoding.BinaryMarshaler = (*DeleteNamespaceRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*DeleteNamespaceRequest)(nil)

func (m *DeleteNamespaceRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DeleteNamespaceRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DeleteNamespaceResponse

var _ encoding.BinaryMarshaler = (*DeleteNamespaceResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*DeleteNamespaceResponse)(nil)

func (m *DeleteNamespaceResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DeleteNamespaceResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DeleteSemaphoreRequest

var _ encoding.BinaryMarshaler = (*DeleteSemaphoreRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*DeleteSemaphoreRequest)(nil)

func (m *DeleteSemaphoreRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DeleteSemaphoreRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DeleteSemaphoreResponse

var _ encoding.BinaryMarshaler = (*DeleteSemaphoreResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*DeleteSemaphoreResponse)(nil)

func (m *DeleteSemaphoreResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DeleteSemaphoreResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DeleteWaitGroupRequest

var _ encoding.BinaryMarshaler = (*DeleteWaitGroupRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*DeleteWaitGroupRequest)(nil)

func (m *DeleteWaitGroupRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DeleteWaitGroupRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DeleteWaitGroupResponse

var _ encoding.BinaryMarshaler = (*DeleteWaitGroupResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*DeleteWaitGroupResponse)(nil)

func (m *DeleteWaitGroupResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DeleteWaitGroupResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetBarrierByNameRequest

var _ encoding.BinaryMarshaler = (*GetBarrierByNameRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*GetBarrierByNameRequest)(nil)

func (m *GetBarrierByNameRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetBarrierByNameRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetBarrierByNameResponse

var _ encoding.BinaryMarshaler = (*GetBarrierByNameResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*GetBarrierByNameResponse)(nil)

func (m *GetBarrierByNameResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetBarrierByNameResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetBarrierRequest

var _ encoding.BinaryMarshaler = (*GetBarrierRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*GetBarrierRequest)(nil)

func (m *GetBarrierRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetBarrierRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetBarrierResponse

var _ encoding.BinaryMarshaler = (*GetBarrierResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*GetBarrierResponse)(nil)

func (m *GetBarrierResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetBarrierResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetLockLeaseRequest

var _ encoding.BinaryMarshaler = (*GetLockLeaseRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*GetLockLeaseRequest)(nil)

func (m *GetLockLeaseRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetLockLeaseRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetLockLeaseResponse

var _ encoding.BinaryMarshaler = (*GetLockLeaseResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*GetLockLeaseResponse)(nil)

func (m *GetLockLeaseResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetLockLeaseResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetLockRequest

var _ encoding.BinaryMarshaler = (*GetLockRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*GetLockRequest)(nil)

func (m *GetLockRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetLockRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetLockResponse

var _ encoding.BinaryMarshaler = (*GetLockResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*GetLockResponse)(nil)

func (m *GetLockResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetLockResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetNamespaceByNameRequest

var _ encoding.BinaryMarshaler = (*GetNamespaceByNameRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*GetNamespaceByNameRequest)(nil)

func (m *GetNamespaceByNameRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetNamespaceByNameRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetNamespaceByNameResponse

var _ encoding.BinaryMarshaler = (*GetNamespaceByNameResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*GetNamespaceByNameResponse)(nil)

func (m *GetNamespaceByNameResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetNamespaceByNameResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetNamespaceRequest

var _ encoding.BinaryMarshaler = (*GetNamespaceRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*GetNamespaceRequest)(nil)

func (m *GetNamespaceRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetNamespaceRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetNamespaceResponse

var _ encoding.BinaryMarshaler = (*GetNamespaceResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*GetNamespaceResponse)(nil)

func (m *GetNamespaceResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetNamespaceResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetSemaphoreByNameRequest

var _ encoding.BinaryMarshaler = (*GetSemaphoreByNameRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*GetSemaphoreByNameRequest)(nil)

func (m *GetSemaphoreByNameRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetSemaphoreByNameRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetSemaphoreByNameResponse

var _ encoding.BinaryMarshaler = (*GetSemaphoreByNameResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*GetSemaphoreByNameResponse)(nil)

func (m *GetSemaphoreByNameResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetSemaphoreByNameResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetSemaphoreLeaseRequest

var _ encoding.BinaryMarshaler = (*GetSemaphoreLeaseRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*GetSemaphoreLeaseRequest)(nil)

func (m *GetSemaphoreLeaseRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetSemaphoreLeaseRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetSemaphoreLeaseResponse

var _ encoding.BinaryMarshaler = (*GetSemaphoreLeaseResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*GetSemaphoreLeaseResponse)(nil)

func (m *GetSemaphoreLeaseResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetSemaphoreLeaseResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetSemaphoreRequest

var _ encoding.BinaryMarshaler = (*GetSemaphoreRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*GetSemaphoreRequest)(nil)

func (m *GetSemaphoreRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetSemaphoreRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetSemaphoreResponse

var _ encoding.BinaryMarshaler = (*GetSemaphoreResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*GetSemaphoreResponse)(nil)

func (m *GetSemaphoreResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetSemaphoreResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetWaitGroupByNameRequest

var _ encoding.BinaryMarshaler = (*GetWaitGroupByNameRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*GetWaitGroupByNameRequest)(nil)

func (m *GetWaitGroupByNameRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetWaitGroupByNameRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetWaitGroupByNameResponse

var _ encoding.BinaryMarshaler = (*GetWaitGroupByNameResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*GetWaitGroupByNameResponse)(nil)

func (m *GetWaitGroupByNameResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetWaitGroupByNameResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetWaitGroupRequest

var _ encoding.BinaryMarshaler = (*GetWaitGroupRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*GetWaitGroupRequest)(nil)

func (m *GetWaitGroupRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetWaitGroupRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetWaitGroupResponse

var _ encoding.BinaryMarshaler = (*GetWaitGroupResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*GetWaitGroupResponse)(nil)

func (m *GetWaitGroupResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetWaitGroupResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// Lease

var _ encoding.BinaryMarshaler = (*Lease)(nil)
var _ encoding.BinaryUnmarshaler = (*Lease)(nil)

func (m *Lease) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *Lease) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// LeaseId

var _ encoding.BinaryMarshaler = (*LeaseId)(nil)
var _ encoding.BinaryUnmarshaler = (*LeaseId)(nil)

func (m *LeaseId) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *LeaseId) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListBarrierParticipantsRequest

var _ encoding.BinaryMarshaler = (*ListBarrierParticipantsRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ListBarrierParticipantsRequest)(nil)

func (m *ListBarrierParticipantsRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListBarrierParticipantsRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListBarrierParticipantsResponse

var _ encoding.BinaryMarshaler = (*ListBarrierParticipantsResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ListBarrierParticipantsResponse)(nil)

func (m *ListBarrierParticipantsResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListBarrierParticipantsResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListBarriersRequest

var _ encoding.BinaryMarshaler = (*ListBarriersRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ListBarriersRequest)(nil)

func (m *ListBarriersRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListBarriersRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListBarriersResponse

var _ encoding.BinaryMarshaler = (*ListBarriersResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ListBarriersResponse)(nil)

func (m *ListBarriersResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListBarriersResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListLockLeasesByProcessIdRequest

var _ encoding.BinaryMarshaler = (*ListLockLeasesByProcessIdRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ListLockLeasesByProcessIdRequest)(nil)

func (m *ListLockLeasesByProcessIdRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListLockLeasesByProcessIdRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListLockLeasesByProcessIdResponse

var _ encoding.BinaryMarshaler = (*ListLockLeasesByProcessIdResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ListLockLeasesByProcessIdResponse)(nil)

func (m *ListLockLeasesByProcessIdResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListLockLeasesByProcessIdResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListLockLeasesRequest

var _ encoding.BinaryMarshaler = (*ListLockLeasesRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ListLockLeasesRequest)(nil)

func (m *ListLockLeasesRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListLockLeasesRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListLockLeasesResponse

var _ encoding.BinaryMarshaler = (*ListLockLeasesResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ListLockLeasesResponse)(nil)

func (m *ListLockLeasesResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListLockLeasesResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListLocksByLeaseIdRequest

var _ encoding.BinaryMarshaler = (*ListLocksByLeaseIdRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ListLocksByLeaseIdRequest)(nil)

func (m *ListLocksByLeaseIdRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListLocksByLeaseIdRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListLocksByLeaseIdResponse

var _ encoding.BinaryMarshaler = (*ListLocksByLeaseIdResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ListLocksByLeaseIdResponse)(nil)

func (m *ListLocksByLeaseIdResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListLocksByLeaseIdResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListLocksRequest

var _ encoding.BinaryMarshaler = (*ListLocksRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ListLocksRequest)(nil)

func (m *ListLocksRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListLocksRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListLocksResponse

var _ encoding.BinaryMarshaler = (*ListLocksResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ListLocksResponse)(nil)

func (m *ListLocksResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListLocksResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListNamespacesRequest

var _ encoding.BinaryMarshaler = (*ListNamespacesRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ListNamespacesRequest)(nil)

func (m *ListNamespacesRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListNamespacesRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListNamespacesResponse

var _ encoding.BinaryMarshaler = (*ListNamespacesResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ListNamespacesResponse)(nil)

func (m *ListNamespacesResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListNamespacesResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListSemaphoreHoldersRequest

var _ encoding.BinaryMarshaler = (*ListSemaphoreHoldersRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ListSemaphoreHoldersRequest)(nil)

func (m *ListSemaphoreHoldersRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListSemaphoreHoldersRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListSemaphoreHoldersResponse

var _ encoding.BinaryMarshaler = (*ListSemaphoreHoldersResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ListSemaphoreHoldersResponse)(nil)

func (m *ListSemaphoreHoldersResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListSemaphoreHoldersResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListSemaphoreLeasesByProcessIdRequest

var _ encoding.BinaryMarshaler = (*ListSemaphoreLeasesByProcessIdRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ListSemaphoreLeasesByProcessIdRequest)(nil)

func (m *ListSemaphoreLeasesByProcessIdRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListSemaphoreLeasesByProcessIdRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListSemaphoreLeasesByProcessIdResponse

var _ encoding.BinaryMarshaler = (*ListSemaphoreLeasesByProcessIdResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ListSemaphoreLeasesByProcessIdResponse)(nil)

func (m *ListSemaphoreLeasesByProcessIdResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListSemaphoreLeasesByProcessIdResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListSemaphoreLeasesRequest

var _ encoding.BinaryMarshaler = (*ListSemaphoreLeasesRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ListSemaphoreLeasesRequest)(nil)

func (m *ListSemaphoreLeasesRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListSemaphoreLeasesRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListSemaphoreLeasesResponse

var _ encoding.BinaryMarshaler = (*ListSemaphoreLeasesResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ListSemaphoreLeasesResponse)(nil)

func (m *ListSemaphoreLeasesResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListSemaphoreLeasesResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListSemaphoresByLeaseIdRequest

var _ encoding.BinaryMarshaler = (*ListSemaphoresByLeaseIdRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ListSemaphoresByLeaseIdRequest)(nil)

func (m *ListSemaphoresByLeaseIdRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListSemaphoresByLeaseIdRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListSemaphoresByLeaseIdResponse

var _ encoding.BinaryMarshaler = (*ListSemaphoresByLeaseIdResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ListSemaphoresByLeaseIdResponse)(nil)

func (m *ListSemaphoresByLeaseIdResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListSemaphoresByLeaseIdResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListSemaphoresRequest

var _ encoding.BinaryMarshaler = (*ListSemaphoresRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ListSemaphoresRequest)(nil)

func (m *ListSemaphoresRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListSemaphoresRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListSemaphoresResponse

var _ encoding.BinaryMarshaler = (*ListSemaphoresResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ListSemaphoresResponse)(nil)

func (m *ListSemaphoresResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListSemaphoresResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListWaitGroupJobsRequest

var _ encoding.BinaryMarshaler = (*ListWaitGroupJobsRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ListWaitGroupJobsRequest)(nil)

func (m *ListWaitGroupJobsRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListWaitGroupJobsRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListWaitGroupJobsResponse

var _ encoding.BinaryMarshaler = (*ListWaitGroupJobsResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ListWaitGroupJobsResponse)(nil)

func (m *ListWaitGroupJobsResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListWaitGroupJobsResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListWaitGroupsRequest

var _ encoding.BinaryMarshaler = (*ListWaitGroupsRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ListWaitGroupsRequest)(nil)

func (m *ListWaitGroupsRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListWaitGroupsRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListWaitGroupsResponse

var _ encoding.BinaryMarshaler = (*ListWaitGroupsResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ListWaitGroupsResponse)(nil)

func (m *ListWaitGroupsResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListWaitGroupsResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// Lock

var _ encoding.BinaryMarshaler = (*Lock)(nil)
var _ encoding.BinaryUnmarshaler = (*Lock)(nil)

func (m *Lock) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *Lock) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// LockAncestor

var _ encoding.BinaryMarshaler = (*LockAncestor)(nil)
var _ encoding.BinaryUnmarshaler = (*LockAncestor)(nil)

func (m *LockAncestor) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *LockAncestor) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// LockHolder

var _ encoding.BinaryMarshaler = (*LockHolder)(nil)
var _ encoding.BinaryUnmarshaler = (*LockHolder)(nil)

func (m *LockHolder) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *LockHolder) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// LockId

var _ encoding.BinaryMarshaler = (*LockId)(nil)
var _ encoding.BinaryUnmarshaler = (*LockId)(nil)

func (m *LockId) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *LockId) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// LocksCounter

var _ encoding.BinaryMarshaler = (*LocksCounter)(nil)
var _ encoding.BinaryUnmarshaler = (*LocksCounter)(nil)

func (m *LocksCounter) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *LocksCounter) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// LocksDeleteNamespaceRequest

var _ encoding.BinaryMarshaler = (*LocksDeleteNamespaceRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*LocksDeleteNamespaceRequest)(nil)

func (m *LocksDeleteNamespaceRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *LocksDeleteNamespaceRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// LocksDeleteNamespaceResponse

var _ encoding.BinaryMarshaler = (*LocksDeleteNamespaceResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*LocksDeleteNamespaceResponse)(nil)

func (m *LocksDeleteNamespaceResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *LocksDeleteNamespaceResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// LocksGarbageCollectionRecord

var _ encoding.BinaryMarshaler = (*LocksGarbageCollectionRecord)(nil)
var _ encoding.BinaryUnmarshaler = (*LocksGarbageCollectionRecord)(nil)

func (m *LocksGarbageCollectionRecord) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *LocksGarbageCollectionRecord) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// Namespace

var _ encoding.BinaryMarshaler = (*Namespace)(nil)
var _ encoding.BinaryUnmarshaler = (*Namespace)(nil)

func (m *Namespace) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *Namespace) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// NamespaceId

var _ encoding.BinaryMarshaler = (*NamespaceId)(nil)
var _ encoding.BinaryUnmarshaler = (*NamespaceId)(nil)

func (m *NamespaceId) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *NamespaceId) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// NamespacesCounter

var _ encoding.BinaryMarshaler = (*NamespacesCounter)(nil)
var _ encoding.BinaryUnmarshaler = (*NamespacesCounter)(nil)

func (m *NamespacesCounter) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *NamespacesCounter) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// PaginationToken

var _ encoding.BinaryMarshaler = (*PaginationToken)(nil)
var _ encoding.BinaryUnmarshaler = (*PaginationToken)(nil)

func (m *PaginationToken) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *PaginationToken) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RefreshLockLeaseRequest

var _ encoding.BinaryMarshaler = (*RefreshLockLeaseRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*RefreshLockLeaseRequest)(nil)

func (m *RefreshLockLeaseRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RefreshLockLeaseRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RefreshLockLeaseResponse

var _ encoding.BinaryMarshaler = (*RefreshLockLeaseResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*RefreshLockLeaseResponse)(nil)

func (m *RefreshLockLeaseResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RefreshLockLeaseResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RefreshSemaphoreLeaseRequest

var _ encoding.BinaryMarshaler = (*RefreshSemaphoreLeaseRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*RefreshSemaphoreLeaseRequest)(nil)

func (m *RefreshSemaphoreLeaseRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RefreshSemaphoreLeaseRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RefreshSemaphoreLeaseResponse

var _ encoding.BinaryMarshaler = (*RefreshSemaphoreLeaseResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*RefreshSemaphoreLeaseResponse)(nil)

func (m *RefreshSemaphoreLeaseResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RefreshSemaphoreLeaseResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ReleaseLockRequest

var _ encoding.BinaryMarshaler = (*ReleaseLockRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ReleaseLockRequest)(nil)

func (m *ReleaseLockRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ReleaseLockRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ReleaseLockResponse

var _ encoding.BinaryMarshaler = (*ReleaseLockResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ReleaseLockResponse)(nil)

func (m *ReleaseLockResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ReleaseLockResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ReleaseSemaphoreRequest

var _ encoding.BinaryMarshaler = (*ReleaseSemaphoreRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ReleaseSemaphoreRequest)(nil)

func (m *ReleaseSemaphoreRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ReleaseSemaphoreRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ReleaseSemaphoreResponse

var _ encoding.BinaryMarshaler = (*ReleaseSemaphoreResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ReleaseSemaphoreResponse)(nil)

func (m *ReleaseSemaphoreResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ReleaseSemaphoreResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RevokeLockLeaseRequest

var _ encoding.BinaryMarshaler = (*RevokeLockLeaseRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*RevokeLockLeaseRequest)(nil)

func (m *RevokeLockLeaseRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RevokeLockLeaseRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RevokeLockLeaseResponse

var _ encoding.BinaryMarshaler = (*RevokeLockLeaseResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*RevokeLockLeaseResponse)(nil)

func (m *RevokeLockLeaseResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RevokeLockLeaseResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RevokeSemaphoreLeaseRequest

var _ encoding.BinaryMarshaler = (*RevokeSemaphoreLeaseRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*RevokeSemaphoreLeaseRequest)(nil)

func (m *RevokeSemaphoreLeaseRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RevokeSemaphoreLeaseRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RevokeSemaphoreLeaseResponse

var _ encoding.BinaryMarshaler = (*RevokeSemaphoreLeaseResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*RevokeSemaphoreLeaseResponse)(nil)

func (m *RevokeSemaphoreLeaseResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RevokeSemaphoreLeaseResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RunBarriersGarbageCollectionRequest

var _ encoding.BinaryMarshaler = (*RunBarriersGarbageCollectionRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*RunBarriersGarbageCollectionRequest)(nil)

func (m *RunBarriersGarbageCollectionRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RunBarriersGarbageCollectionRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RunBarriersGarbageCollectionResponse

var _ encoding.BinaryMarshaler = (*RunBarriersGarbageCollectionResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*RunBarriersGarbageCollectionResponse)(nil)

func (m *RunBarriersGarbageCollectionResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RunBarriersGarbageCollectionResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RunLocksGarbageCollectionRequest

var _ encoding.BinaryMarshaler = (*RunLocksGarbageCollectionRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*RunLocksGarbageCollectionRequest)(nil)

func (m *RunLocksGarbageCollectionRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RunLocksGarbageCollectionRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RunLocksGarbageCollectionResponse

var _ encoding.BinaryMarshaler = (*RunLocksGarbageCollectionResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*RunLocksGarbageCollectionResponse)(nil)

func (m *RunLocksGarbageCollectionResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RunLocksGarbageCollectionResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RunSemaphoresGarbageCollectionRequest

var _ encoding.BinaryMarshaler = (*RunSemaphoresGarbageCollectionRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*RunSemaphoresGarbageCollectionRequest)(nil)

func (m *RunSemaphoresGarbageCollectionRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RunSemaphoresGarbageCollectionRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RunSemaphoresGarbageCollectionResponse

var _ encoding.BinaryMarshaler = (*RunSemaphoresGarbageCollectionResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*RunSemaphoresGarbageCollectionResponse)(nil)

func (m *RunSemaphoresGarbageCollectionResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RunSemaphoresGarbageCollectionResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RunWaitGroupsGarbageCollectionRequest

var _ encoding.BinaryMarshaler = (*RunWaitGroupsGarbageCollectionRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*RunWaitGroupsGarbageCollectionRequest)(nil)

func (m *RunWaitGroupsGarbageCollectionRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RunWaitGroupsGarbageCollectionRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RunWaitGroupsGarbageCollectionResponse

var _ encoding.BinaryMarshaler = (*RunWaitGroupsGarbageCollectionResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*RunWaitGroupsGarbageCollectionResponse)(nil)

func (m *RunWaitGroupsGarbageCollectionResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RunWaitGroupsGarbageCollectionResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// Semaphore

var _ encoding.BinaryMarshaler = (*Semaphore)(nil)
var _ encoding.BinaryUnmarshaler = (*Semaphore)(nil)

func (m *Semaphore) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *Semaphore) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// SemaphoreHolder

var _ encoding.BinaryMarshaler = (*SemaphoreHolder)(nil)
var _ encoding.BinaryUnmarshaler = (*SemaphoreHolder)(nil)

func (m *SemaphoreHolder) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *SemaphoreHolder) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// SemaphoreHolderId

var _ encoding.BinaryMarshaler = (*SemaphoreHolderId)(nil)
var _ encoding.BinaryUnmarshaler = (*SemaphoreHolderId)(nil)

func (m *SemaphoreHolderId) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *SemaphoreHolderId) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// SemaphoreId

var _ encoding.BinaryMarshaler = (*SemaphoreId)(nil)
var _ encoding.BinaryUnmarshaler = (*SemaphoreId)(nil)

func (m *SemaphoreId) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *SemaphoreId) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// SemaphoresCounter

var _ encoding.BinaryMarshaler = (*SemaphoresCounter)(nil)
var _ encoding.BinaryUnmarshaler = (*SemaphoresCounter)(nil)

func (m *SemaphoresCounter) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *SemaphoresCounter) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// SemaphoresDeleteNamespaceRequest

var _ encoding.BinaryMarshaler = (*SemaphoresDeleteNamespaceRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*SemaphoresDeleteNamespaceRequest)(nil)

func (m *SemaphoresDeleteNamespaceRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *SemaphoresDeleteNamespaceRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// SemaphoresDeleteNamespaceResponse

var _ encoding.BinaryMarshaler = (*SemaphoresDeleteNamespaceResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*SemaphoresDeleteNamespaceResponse)(nil)

func (m *SemaphoresDeleteNamespaceResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *SemaphoresDeleteNamespaceResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// SemaphoresExpirationRecord

var _ encoding.BinaryMarshaler = (*SemaphoresExpirationRecord)(nil)
var _ encoding.BinaryUnmarshaler = (*SemaphoresExpirationRecord)(nil)

func (m *SemaphoresExpirationRecord) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *SemaphoresExpirationRecord) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// SemaphoresGarbageCollectionRecord

var _ encoding.BinaryMarshaler = (*SemaphoresGarbageCollectionRecord)(nil)
var _ encoding.BinaryUnmarshaler = (*SemaphoresGarbageCollectionRecord)(nil)

func (m *SemaphoresGarbageCollectionRecord) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *SemaphoresGarbageCollectionRecord) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// UpdateBarrierRequest

var _ encoding.BinaryMarshaler = (*UpdateBarrierRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*UpdateBarrierRequest)(nil)

func (m *UpdateBarrierRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *UpdateBarrierRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// UpdateBarrierResponse

var _ encoding.BinaryMarshaler = (*UpdateBarrierResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*UpdateBarrierResponse)(nil)

func (m *UpdateBarrierResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *UpdateBarrierResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// UpdateNamespaceRequest

var _ encoding.BinaryMarshaler = (*UpdateNamespaceRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*UpdateNamespaceRequest)(nil)

func (m *UpdateNamespaceRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *UpdateNamespaceRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// UpdateNamespaceResponse

var _ encoding.BinaryMarshaler = (*UpdateNamespaceResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*UpdateNamespaceResponse)(nil)

func (m *UpdateNamespaceResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *UpdateNamespaceResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// UpdateSemaphoreRequest

var _ encoding.BinaryMarshaler = (*UpdateSemaphoreRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*UpdateSemaphoreRequest)(nil)

func (m *UpdateSemaphoreRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *UpdateSemaphoreRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// UpdateSemaphoreResponse

var _ encoding.BinaryMarshaler = (*UpdateSemaphoreResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*UpdateSemaphoreResponse)(nil)

func (m *UpdateSemaphoreResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *UpdateSemaphoreResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// WaitAtBarrierRequest

var _ encoding.BinaryMarshaler = (*WaitAtBarrierRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*WaitAtBarrierRequest)(nil)

func (m *WaitAtBarrierRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *WaitAtBarrierRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// WaitAtBarrierResponse

var _ encoding.BinaryMarshaler = (*WaitAtBarrierResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*WaitAtBarrierResponse)(nil)

func (m *WaitAtBarrierResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *WaitAtBarrierResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// WaitGroup

var _ encoding.BinaryMarshaler = (*WaitGroup)(nil)
var _ encoding.BinaryUnmarshaler = (*WaitGroup)(nil)

func (m *WaitGroup) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *WaitGroup) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// WaitGroupId

var _ encoding.BinaryMarshaler = (*WaitGroupId)(nil)
var _ encoding.BinaryUnmarshaler = (*WaitGroupId)(nil)

func (m *WaitGroupId) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *WaitGroupId) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// WaitGroupJob

var _ encoding.BinaryMarshaler = (*WaitGroupJob)(nil)
var _ encoding.BinaryUnmarshaler = (*WaitGroupJob)(nil)

func (m *WaitGroupJob) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *WaitGroupJob) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// WaitGroupJobId

var _ encoding.BinaryMarshaler = (*WaitGroupJobId)(nil)
var _ encoding.BinaryUnmarshaler = (*WaitGroupJobId)(nil)

func (m *WaitGroupJobId) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *WaitGroupJobId) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// WaitGroupsCounter

var _ encoding.BinaryMarshaler = (*WaitGroupsCounter)(nil)
var _ encoding.BinaryUnmarshaler = (*WaitGroupsCounter)(nil)

func (m *WaitGroupsCounter) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *WaitGroupsCounter) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// WaitGroupsDeleteNamespaceRequest

var _ encoding.BinaryMarshaler = (*WaitGroupsDeleteNamespaceRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*WaitGroupsDeleteNamespaceRequest)(nil)

func (m *WaitGroupsDeleteNamespaceRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *WaitGroupsDeleteNamespaceRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// WaitGroupsDeleteNamespaceResponse

var _ encoding.BinaryMarshaler = (*WaitGroupsDeleteNamespaceResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*WaitGroupsDeleteNamespaceResponse)(nil)

func (m *WaitGroupsDeleteNamespaceResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *WaitGroupsDeleteNamespaceResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// WaitGroupsExpirationRecord

var _ encoding.BinaryMarshaler = (*WaitGroupsExpirationRecord)(nil)
var _ encoding.BinaryUnmarshaler = (*WaitGroupsExpirationRecord)(nil)

func (m *WaitGroupsExpirationRecord) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *WaitGroupsExpirationRecord) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// WaitGroupsGarbageCollectionRecord

var _ encoding.BinaryMarshaler = (*WaitGroupsGarbageCollectionRecord)(nil)
var _ encoding.BinaryUnmarshaler = (*WaitGroupsGarbageCollectionRecord)(nil)

func (m *WaitGroupsGarbageCollectionRecord) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *WaitGroupsGarbageCollectionRecord) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}
