// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.35.0
// source: pkg/corepb/wait_groups.proto

package corepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WaitGroupStatus is the lifecycle state of a wait group. A wait group starts
// ACTIVE. It becomes COMPLETED once the number of completed jobs reaches the
// counter, or EXPIRED once expires_at passes while it is still active. Both
// COMPLETED and EXPIRED are terminal "finished" states after which the wait
// group is deleted by garbage collection once delete_after_finished_seconds
// has elapsed.
type WaitGroupStatus int32

const (
	WaitGroupStatus_WAIT_GROUP_STATUS_INVALID   WaitGroupStatus = 0
	WaitGroupStatus_WAIT_GROUP_STATUS_ACTIVE    WaitGroupStatus = 1
	WaitGroupStatus_WAIT_GROUP_STATUS_EXPIRED   WaitGroupStatus = 2
	WaitGroupStatus_WAIT_GROUP_STATUS_COMPLETED WaitGroupStatus = 3
)

// Enum value maps for WaitGroupStatus.
var (
	WaitGroupStatus_name = map[int32]string{
		0: "WAIT_GROUP_STATUS_INVALID",
		1: "WAIT_GROUP_STATUS_ACTIVE",
		2: "WAIT_GROUP_STATUS_EXPIRED",
		3: "WAIT_GROUP_STATUS_COMPLETED",
	}
	WaitGroupStatus_value = map[string]int32{
		"WAIT_GROUP_STATUS_INVALID":   0,
		"WAIT_GROUP_STATUS_ACTIVE":    1,
		"WAIT_GROUP_STATUS_EXPIRED":   2,
		"WAIT_GROUP_STATUS_COMPLETED": 3,
	}
)

func (x WaitGroupStatus) Enum() *WaitGroupStatus {
	p := new(WaitGroupStatus)
	*p = x
	return p
}

func (x WaitGroupStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WaitGroupStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_corepb_wait_groups_proto_enumTypes[0].Descriptor()
}

func (WaitGroupStatus) Type() protoreflect.EnumType {
	return &file_pkg_corepb_wait_groups_proto_enumTypes[0]
}

func (x WaitGroupStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WaitGroupStatus.Descriptor instead.
func (WaitGroupStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{0}
}

type CreateWaitGroupRequest struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	WaitGroupId                       *WaitGroupId           `protobuf:"bytes,1,opt,name=wait_group_id,json=waitGroupId,proto3" json:"wait_group_id,omitempty"`
	Name                              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description                       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Now                               int64                  `protobuf:"varint,4,opt,name=now,proto3" json:"now,omitempty"`
	Counter                           uint64                 `protobuf:"varint,5,opt,name=counter,proto3" json:"counter,omitempty"`
	ExpiresAt                         int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Metadata                          map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MaxNumberOfWaitGroupsPerNamespace int64                  `protobuf:"varint,8,opt,name=max_number_of_wait_groups_per_namespace,json=maxNumberOfWaitGroupsPerNamespace,proto3" json:"max_number_of_wait_groups_per_namespace,omitempty"`
	DeleteAfterFinishedSeconds        int64                  `protobuf:"varint,9,opt,name=delete_after_finished_seconds,json=deleteAfterFinishedSeconds,proto3" json:"delete_after_finished_seconds,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *CreateWaitGroupRequest) Reset() {
	*x = CreateWaitGroupRequest{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWaitGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWaitGroupRequest) ProtoMessage() {}

func (x *CreateWaitGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWaitGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateWaitGroupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWaitGroupRequest) GetWaitGroupId() *WaitGroupId {
	if x != nil {
		return x.WaitGroupId
	}
	return nil
}

func (x *CreateWaitGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWaitGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateWaitGroupRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

func (x *CreateWaitGroupRequest) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *CreateWaitGroupRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *CreateWaitGroupRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateWaitGroupRequest) GetMaxNumberOfWaitGroupsPerNamespace() int64 {
	if x != nil {
		return x.MaxNumberOfWaitGroupsPerNamespace
	}
	return 0
}

func (x *CreateWaitGroupRequest) GetDeleteAfterFinishedSeconds() int64 {
	if x != nil {
		return x.DeleteAfterFinishedSeconds
	}
	return 0
}

type CreateWaitGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaitGroup     *WaitGroup             `protobuf:"bytes,1,opt,name=wait_group,json=waitGroup,proto3" json:"wait_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWaitGroupResponse) Reset() {
	*x = CreateWaitGroupResponse{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWaitGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWaitGroupResponse) ProtoMessage() {}

func (x *CreateWaitGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWaitGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateWaitGroupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWaitGroupResponse) GetWaitGroup() *WaitGroup {
	if x != nil {
		return x.WaitGroup
	}
	return nil
}

type UpdateWaitGroupRequest struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId                *NamespaceId           `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	WaitGroupName              string                 `protobuf:"bytes,2,opt,name=wait_group_name,json=waitGroupName,proto3" json:"wait_group_name,omitempty"`
	Description                string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Now                        int64                  `protobuf:"varint,4,opt,name=now,proto3" json:"now,omitempty"`
	ExpiresAt                  int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Counter                    uint64                 `protobuf:"varint,6,opt,name=counter,proto3" json:"counter,omitempty"`
	Metadata                   map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpectedVersion            uint64                 `protobuf:"varint,8,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	DeleteAfterFinishedSeconds int64                  `protobuf:"varint,9,opt,name=delete_after_finished_seconds,json=deleteAfterFinishedSeconds,proto3" json:"delete_after_finished_seconds,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *UpdateWaitGroupRequest) Reset() {
	*x = UpdateWaitGroupRequest{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWaitGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWaitGroupRequest) ProtoMessage() {}

func (x *UpdateWaitGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWaitGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateWaitGroupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateWaitGroupRequest) GetNamespaceId() *NamespaceId {
	if x != nil {
		return x.NamespaceId
	}
	return nil
}

func (x *UpdateWaitGroupRequest) GetWaitGroupName() string {
	if x != nil {
		return x.WaitGroupName
	}
	return ""
}

func (x *UpdateWaitGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateWaitGroupRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

func (x *UpdateWaitGroupRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *UpdateWaitGroupRequest) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *UpdateWaitGroupRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateWaitGroupRequest) GetExpectedVersion() uint64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *UpdateWaitGroupRequest) GetDeleteAfterFinishedSeconds() int64 {
	if x != nil {
		return x.DeleteAfterFinishedSeconds
	}
	return 0
}

type UpdateWaitGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaitGroup     *WaitGroup             `protobuf:"bytes,1,opt,name=wait_group,json=waitGroup,proto3" json:"wait_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWaitGroupResponse) Reset() {
	*x = UpdateWaitGroupResponse{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWaitGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWaitGroupResponse) ProtoMessage() {}

func (x *UpdateWaitGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWaitGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateWaitGroupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateWaitGroupResponse) GetWaitGroup() *WaitGroup {
	if x != nil {
		return x.WaitGroup
	}
	return nil
}

type ListWaitGroupsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId     *NamespaceId           `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	PaginationToken *PaginationToken       `protobuf:"bytes,2,opt,name=pagination_token,json=paginationToken,proto3" json:"pagination_token,omitempty"`
	Limit           int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListWaitGroupsRequest) Reset() {
	*x = ListWaitGroupsRequest{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWaitGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWaitGroupsRequest) ProtoMessage() {}

func (x *ListWaitGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWaitGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListWaitGroupsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{4}
}

func (x *ListWaitGroupsRequest) GetNamespaceId() *NamespaceId {
	if x != nil {
		return x.NamespaceId
	}
	return nil
}

func (x *ListWaitGroupsRequest) GetPaginationToken() *PaginationToken {
	if x != nil {
		return x.PaginationToken
	}
	return nil
}

func (x *ListWaitGroupsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListWaitGroupsResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	WaitGroups              []*WaitGroup           `protobuf:"bytes,1,rep,name=wait_groups,json=waitGroups,proto3" json:"wait_groups,omitempty"`
	NextPaginationToken     *PaginationToken       `protobuf:"bytes,2,opt,name=next_pagination_token,json=nextPaginationToken,proto3" json:"next_pagination_token,omitempty"`
	PreviousPaginationToken *PaginationToken       `protobuf:"bytes,3,opt,name=previous_pagination_token,json=previousPaginationToken,proto3" json:"previous_pagination_token,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListWaitGroupsResponse) Reset() {
	*x = ListWaitGroupsResponse{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWaitGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWaitGroupsResponse) ProtoMessage() {}

func (x *ListWaitGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWaitGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListWaitGroupsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{5}
}

func (x *ListWaitGroupsResponse) GetWaitGroups() []*WaitGroup {
	if x != nil {
		return x.WaitGroups
	}
	return nil
}

func (x *ListWaitGroupsResponse) GetNextPaginationToken() *PaginationToken {
	if x != nil {
		return x.NextPaginationToken
	}
	return nil
}

func (x *ListWaitGroupsResponse) GetPreviousPaginationToken() *PaginationToken {
	if x != nil {
		return x.PreviousPaginationToken
	}
	return nil
}

type GetWaitGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaitGroupId   *WaitGroupId           `protobuf:"bytes,1,opt,name=wait_group_id,json=waitGroupId,proto3" json:"wait_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWaitGroupRequest) Reset() {
	*x = GetWaitGroupRequest{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWaitGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWaitGroupRequest) ProtoMessage() {}

func (x *GetWaitGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWaitGroupRequest.ProtoReflect.Descriptor instead.
func (*GetWaitGroupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{6}
}

func (x *GetWaitGroupRequest) GetWaitGroupId() *WaitGroupId {
	if x != nil {
		return x.WaitGroupId
	}
	return nil
}

type GetWaitGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaitGroup     *WaitGroup             `protobuf:"bytes,1,opt,name=wait_group,json=waitGroup,proto3" json:"wait_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWaitGroupResponse) Reset() {
	*x = GetWaitGroupResponse{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWaitGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWaitGroupResponse) ProtoMessage() {}

func (x *GetWaitGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWaitGroupResponse.ProtoReflect.Descriptor instead.
func (*GetWaitGroupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{7}
}

func (x *GetWaitGroupResponse) GetWaitGroup() *WaitGroup {
	if x != nil {
		return x.WaitGroup
	}
	return nil
}

type GetWaitGroupByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   *NamespaceId           `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	WaitGroupName string                 `protobuf:"bytes,2,opt,name=wait_group_name,json=waitGroupName,proto3" json:"wait_group_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWaitGroupByNameRequest) Reset() {
	*x = GetWaitGroupByNameRequest{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWaitGroupByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWaitGroupByNameRequest) ProtoMessage() {}

func (x *GetWaitGroupByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWaitGroupByNameRequest.ProtoReflect.Descriptor instead.
func (*GetWaitGroupByNameRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{8}
}

func (x *GetWaitGroupByNameRequest) GetNamespaceId() *NamespaceId {
	if x != nil {
		return x.NamespaceId
	}
	return nil
}

func (x *GetWaitGroupByNameRequest) GetWaitGroupName() string {
	if x != nil {
		return x.WaitGroupName
	}
	return ""
}

type GetWaitGroupByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaitGroup     *WaitGroup             `protobuf:"bytes,1,opt,name=wait_group,json=waitGroup,proto3" json:"wait_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWaitGroupByNameResponse) Reset() {
	*x = GetWaitGroupByNameResponse{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWaitGroupByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWaitGroupByNameResponse) ProtoMessage() {}

func (x *GetWaitGroupByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWaitGroupByNameResponse.ProtoReflect.Descriptor instead.
func (*GetWaitGroupByNameResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{9}
}

func (x *GetWaitGroupByNameResponse) GetWaitGroup() *WaitGroup {
	if x != nil {
		return x.WaitGroup
	}
	return nil
}

type DeleteWaitGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   *NamespaceId           `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	WaitGroupName string                 `protobuf:"bytes,2,opt,name=wait_group_name,json=waitGroupName,proto3" json:"wait_group_name,omitempty"`
	RecordId      uint64                 `protobuf:"varint,3,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWaitGroupRequest) Reset() {
	*x = DeleteWaitGroupRequest{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWaitGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWaitGroupRequest) ProtoMessage() {}

func (x *DeleteWaitGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWaitGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteWaitGroupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteWaitGroupRequest) GetNamespaceId() *NamespaceId {
	if x != nil {
		return x.NamespaceId
	}
	return nil
}

func (x *DeleteWaitGroupRequest) GetWaitGroupName() string {
	if x != nil {
		return x.WaitGroupName
	}
	return ""
}

func (x *DeleteWaitGroupRequest) GetRecordId() uint64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

type DeleteWaitGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWaitGroupResponse) Reset() {
	*x = DeleteWaitGroupResponse{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWaitGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWaitGroupResponse) ProtoMessage() {}

func (x *DeleteWaitGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWaitGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteWaitGroupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{11}
}

type CompleteJobsFromWaitGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   *NamespaceId           `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	WaitGroupName string                 `protobuf:"bytes,2,opt,name=wait_group_name,json=waitGroupName,proto3" json:"wait_group_name,omitempty"`
	Jobs          []*CompleteJobRequest  `protobuf:"bytes,3,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Now           int64                  `protobuf:"varint,4,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteJobsFromWaitGroupRequest) Reset() {
	*x = CompleteJobsFromWaitGroupRequest{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteJobsFromWaitGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteJobsFromWaitGroupRequest) ProtoMessage() {}

func (x *CompleteJobsFromWaitGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteJobsFromWaitGroupRequest.ProtoReflect.Descriptor instead.
func (*CompleteJobsFromWaitGroupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{12}
}

func (x *CompleteJobsFromWaitGroupRequest) GetNamespaceId() *NamespaceId {
	if x != nil {
		return x.NamespaceId
	}
	return nil
}

func (x *CompleteJobsFromWaitGroupRequest) GetWaitGroupName() string {
	if x != nil {
		return x.WaitGroupName
	}
	return ""
}

func (x *CompleteJobsFromWaitGroupRequest) GetJobs() []*CompleteJobRequest {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *CompleteJobsFromWaitGroupRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

type CompleteJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteJobRequest) Reset() {
	*x = CompleteJobRequest{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteJobRequest) ProtoMessage() {}

func (x *CompleteJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteJobRequest.ProtoReflect.Descriptor instead.
func (*CompleteJobRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{13}
}

func (x *CompleteJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CompleteJobRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CompleteJobsFromWaitGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaitGroup     *WaitGroup             `protobuf:"bytes,1,opt,name=wait_group,json=waitGroup,proto3" json:"wait_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteJobsFromWaitGroupResponse) Reset() {
	*x = CompleteJobsFromWaitGroupResponse{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteJobsFromWaitGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteJobsFromWaitGroupResponse) ProtoMessage() {}

func (x *CompleteJobsFromWaitGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteJobsFromWaitGroupResponse.ProtoReflect.Descriptor instead.
func (*CompleteJobsFromWaitGroupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{14}
}

func (x *CompleteJobsFromWaitGroupResponse) GetWaitGroup() *WaitGroup {
	if x != nil {
		return x.WaitGroup
	}
	return nil
}

type ListWaitGroupJobsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId     *NamespaceId           `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	WaitGroupName   string                 `protobuf:"bytes,2,opt,name=wait_group_name,json=waitGroupName,proto3" json:"wait_group_name,omitempty"`
	PaginationToken *PaginationToken       `protobuf:"bytes,3,opt,name=pagination_token,json=paginationToken,proto3" json:"pagination_token,omitempty"`
	Limit           int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListWaitGroupJobsRequest) Reset() {
	*x = ListWaitGroupJobsRequest{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWaitGroupJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWaitGroupJobsRequest) ProtoMessage() {}

func (x *ListWaitGroupJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWaitGroupJobsRequest.ProtoReflect.Descriptor instead.
func (*ListWaitGroupJobsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{15}
}

func (x *ListWaitGroupJobsRequest) GetNamespaceId() *NamespaceId {
	if x != nil {
		return x.NamespaceId
	}
	return nil
}

func (x *ListWaitGroupJobsRequest) GetWaitGroupName() string {
	if x != nil {
		return x.WaitGroupName
	}
	return ""
}

func (x *ListWaitGroupJobsRequest) GetPaginationToken() *PaginationToken {
	if x != nil {
		return x.PaginationToken
	}
	return nil
}

func (x *ListWaitGroupJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListWaitGroupJobsResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Jobs                    []*WaitGroupJob        `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	NextPaginationToken     *PaginationToken       `protobuf:"bytes,2,opt,name=next_pagination_token,json=nextPaginationToken,proto3" json:"next_pagination_token,omitempty"`
	PreviousPaginationToken *PaginationToken       `protobuf:"bytes,3,opt,name=previous_pagination_token,json=previousPaginationToken,proto3" json:"previous_pagination_token,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListWaitGroupJobsResponse) Reset() {
	*x = ListWaitGroupJobsResponse{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWaitGroupJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWaitGroupJobsResponse) ProtoMessage() {}

func (x *ListWaitGroupJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWaitGroupJobsResponse.ProtoReflect.Descriptor instead.
func (*ListWaitGroupJobsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{16}
}

func (x *ListWaitGroupJobsResponse) GetJobs() []*WaitGroupJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListWaitGroupJobsResponse) GetNextPaginationToken() *PaginationToken {
	if x != nil {
		return x.NextPaginationToken
	}
	return nil
}

func (x *ListWaitGroupJobsResponse) GetPreviousPaginationToken() *PaginationToken {
	if x != nil {
		return x.PreviousPaginationToken
	}
	return nil
}

type RunWaitGroupsGarbageCollectionRequest struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Now                        int64                  `protobuf:"varint,1,opt,name=now,proto3" json:"now,omitempty"`
	GcRecordsPageSize          int64                  `protobuf:"varint,2,opt,name=gc_records_page_size,json=gcRecordsPageSize,proto3" json:"gc_records_page_size,omitempty"`
	GcRecordWaitGroupsPageSize int64                  `protobuf:"varint,3,opt,name=gc_record_wait_groups_page_size,json=gcRecordWaitGroupsPageSize,proto3" json:"gc_record_wait_groups_page_size,omitempty"`
	MaxDeletedObjects          int64                  `protobuf:"varint,4,opt,name=max_deleted_objects,json=maxDeletedObjects,proto3" json:"max_deleted_objects,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *RunWaitGroupsGarbageCollectionRequest) Reset() {
	*x = RunWaitGroupsGarbageCollectionRequest{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunWaitGroupsGarbageCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWaitGroupsGarbageCollectionRequest) ProtoMessage() {}

func (x *RunWaitGroupsGarbageCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWaitGroupsGarbageCollectionRequest.ProtoReflect.Descriptor instead.
func (*RunWaitGroupsGarbageCollectionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{17}
}

func (x *RunWaitGroupsGarbageCollectionRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

func (x *RunWaitGroupsGarbageCollectionRequest) GetGcRecordsPageSize() int64 {
	if x != nil {
		return x.GcRecordsPageSize
	}
	return 0
}

func (x *RunWaitGroupsGarbageCollectionRequest) GetGcRecordWaitGroupsPageSize() int64 {
	if x != nil {
		return x.GcRecordWaitGroupsPageSize
	}
	return 0
}

func (x *RunWaitGroupsGarbageCollectionRequest) GetMaxDeletedObjects() int64 {
	if x != nil {
		return x.MaxDeletedObjects
	}
	return 0
}

type RunWaitGroupsGarbageCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunWaitGroupsGarbageCollectionResponse) Reset() {
	*x = RunWaitGroupsGarbageCollectionResponse{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunWaitGroupsGarbageCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWaitGroupsGarbageCollectionResponse) ProtoMessage() {}

func (x *RunWaitGroupsGarbageCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWaitGroupsGarbageCollectionResponse.ProtoReflect.Descriptor instead.
func (*RunWaitGroupsGarbageCollectionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{18}
}

type WaitGroupsDeleteNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      uint64                 `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	NamespaceId   *NamespaceId           `protobuf:"bytes,2,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	Now           int64                  `protobuf:"varint,3,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitGroupsDeleteNamespaceRequest) Reset() {
	*x = WaitGroupsDeleteNamespaceRequest{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitGroupsDeleteNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitGroupsDeleteNamespaceRequest) ProtoMessage() {}

func (x *WaitGroupsDeleteNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitGroupsDeleteNamespaceRequest.ProtoReflect.Descriptor instead.
func (*WaitGroupsDeleteNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{19}
}

func (x *WaitGroupsDeleteNamespaceRequest) GetRecordId() uint64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *WaitGroupsDeleteNamespaceRequest) GetNamespaceId() *NamespaceId {
	if x != nil {
		return x.NamespaceId
	}
	return nil
}

func (x *WaitGroupsDeleteNamespaceRequest) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

type WaitGroupsDeleteNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitGroupsDeleteNamespaceResponse) Reset() {
	*x = WaitGroupsDeleteNamespaceResponse{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitGroupsDeleteNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitGroupsDeleteNamespaceResponse) ProtoMessage() {}

func (x *WaitGroupsDeleteNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitGroupsDeleteNamespaceResponse.ProtoReflect.Descriptor instead.
func (*WaitGroupsDeleteNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{20}
}

type WaitGroup struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         *WaitGroupId           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description                string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt                  int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                  int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version                    uint64                 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	ExpiresAt                  int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Counter                    uint64                 `protobuf:"varint,8,opt,name=counter,proto3" json:"counter,omitempty"`
	CompletedJobs              uint64                 `protobuf:"varint,9,opt,name=completed_jobs,json=completedJobs,proto3" json:"completed_jobs,omitempty"`
	Metadata                   map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status                     WaitGroupStatus        `protobuf:"varint,11,opt,name=status,proto3,enum=com.evrblk.grackle.corepb.WaitGroupStatus" json:"status,omitempty"`
	DeleteAfterFinishedSeconds int64                  `protobuf:"varint,12,opt,name=delete_after_finished_seconds,json=deleteAfterFinishedSeconds,proto3" json:"delete_after_finished_seconds,omitempty"`
	// finished_at is the timestamp (ns) at which the wait group became finished
	// (either completed or expired). Zero while the wait group is still active.
	FinishedAt int64 `protobuf:"varint,13,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	// last_activity_at is the timestamp (ns) of the most recent activity on this
	// wait group (a job being reported completed). Not affected by reads.
	LastActivityAt int64 `protobuf:"varint,14,opt,name=last_activity_at,json=lastActivityAt,proto3" json:"last_activity_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WaitGroup) Reset() {
	*x = WaitGroup{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitGroup) ProtoMessage() {}

func (x *WaitGroup) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitGroup.ProtoReflect.Descriptor instead.
func (*WaitGroup) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{21}
}

func (x *WaitGroup) GetId() *WaitGroupId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *WaitGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WaitGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WaitGroup) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *WaitGroup) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *WaitGroup) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WaitGroup) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *WaitGroup) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *WaitGroup) GetCompletedJobs() uint64 {
	if x != nil {
		return x.CompletedJobs
	}
	return 0
}

func (x *WaitGroup) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WaitGroup) GetStatus() WaitGroupStatus {
	if x != nil {
		return x.Status
	}
	return WaitGroupStatus_WAIT_GROUP_STATUS_INVALID
}

func (x *WaitGroup) GetDeleteAfterFinishedSeconds() int64 {
	if x != nil {
		return x.DeleteAfterFinishedSeconds
	}
	return 0
}

func (x *WaitGroup) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *WaitGroup) GetLastActivityAt() int64 {
	if x != nil {
		return x.LastActivityAt
	}
	return 0
}

type WaitGroupJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *WaitGroupJobId        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,2,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitGroupJob) Reset() {
	*x = WaitGroupJob{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitGroupJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitGroupJob) ProtoMessage() {}

func (x *WaitGroupJob) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitGroupJob.ProtoReflect.Descriptor instead.
func (*WaitGroupJob) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{22}
}

func (x *WaitGroupJob) GetId() *WaitGroupJobId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *WaitGroupJob) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *WaitGroupJob) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type WaitGroupJobId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint64                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	NamespaceId   uint32                 `protobuf:"varint,2,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	WaitGroupId   uint64                 `protobuf:"varint,3,opt,name=wait_group_id,json=waitGroupId,proto3" json:"wait_group_id,omitempty"`
	JobId         string                 `protobuf:"bytes,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitGroupJobId) Reset() {
	*x = WaitGroupJobId{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitGroupJobId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitGroupJobId) ProtoMessage() {}

func (x *WaitGroupJobId) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitGroupJobId.ProtoReflect.Descriptor instead.
func (*WaitGroupJobId) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{23}
}

func (x *WaitGroupJobId) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *WaitGroupJobId) GetNamespaceId() uint32 {
	if x != nil {
		return x.NamespaceId
	}
	return 0
}

func (x *WaitGroupJobId) GetWaitGroupId() uint64 {
	if x != nil {
		return x.WaitGroupId
	}
	return 0
}

func (x *WaitGroupJobId) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type WaitGroupId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint64                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	NamespaceId   uint32                 `protobuf:"varint,2,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	WaitGroupId   uint64                 `protobuf:"varint,3,opt,name=wait_group_id,json=waitGroupId,proto3" json:"wait_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitGroupId) Reset() {
	*x = WaitGroupId{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitGroupId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitGroupId) ProtoMessage() {}

func (x *WaitGroupId) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitGroupId.ProtoReflect.Descriptor instead.
func (*WaitGroupId) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{24}
}

func (x *WaitGroupId) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *WaitGroupId) GetNamespaceId() uint32 {
	if x != nil {
		return x.NamespaceId
	}
	return 0
}

func (x *WaitGroupId) GetWaitGroupId() uint64 {
	if x != nil {
		return x.WaitGroupId
	}
	return 0
}

type WaitGroupsCounter struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NumberOfWaitGroups int64                  `protobuf:"varint,1,opt,name=number_of_wait_groups,json=numberOfWaitGroups,proto3" json:"number_of_wait_groups,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WaitGroupsCounter) Reset() {
	*x = WaitGroupsCounter{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitGroupsCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitGroupsCounter) ProtoMessage() {}

func (x *WaitGroupsCounter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitGroupsCounter.ProtoReflect.Descriptor instead.
func (*WaitGroupsCounter) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{25}
}

func (x *WaitGroupsCounter) GetNumberOfWaitGroups() int64 {
	if x != nil {
		return x.NumberOfWaitGroups
	}
	return 0
}

type WaitGroupsGarbageCollectionRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Record:
	//
	//	*WaitGroupsGarbageCollectionRecord_NamespaceId
	//	*WaitGroupsGarbageCollectionRecord_WaitGroupId
	Record        isWaitGroupsGarbageCollectionRecord_Record `protobuf_oneof:"record"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitGroupsGarbageCollectionRecord) Reset() {
	*x = WaitGroupsGarbageCollectionRecord{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitGroupsGarbageCollectionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitGroupsGarbageCollectionRecord) ProtoMessage() {}

func (x *WaitGroupsGarbageCollectionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitGroupsGarbageCollectionRecord.ProtoReflect.Descriptor instead.
func (*WaitGroupsGarbageCollectionRecord) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{26}
}

func (x *WaitGroupsGarbageCollectionRecord) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WaitGroupsGarbageCollectionRecord) GetRecord() isWaitGroupsGarbageCollectionRecord_Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *WaitGroupsGarbageCollectionRecord) GetNamespaceId() *NamespaceId {
	if x != nil {
		if x, ok := x.Record.(*WaitGroupsGarbageCollectionRecord_NamespaceId); ok {
			return x.NamespaceId
		}
	}
	return nil
}

func (x *WaitGroupsGarbageCollectionRecord) GetWaitGroupId() *WaitGroupId {
	if x != nil {
		if x, ok := x.Record.(*WaitGroupsGarbageCollectionRecord_WaitGroupId); ok {
			return x.WaitGroupId
		}
	}
	return nil
}

type isWaitGroupsGarbageCollectionRecord_Record interface {
	isWaitGroupsGarbageCollectionRecord_Record()
}

type WaitGroupsGarbageCollectionRecord_NamespaceId struct {
	NamespaceId *NamespaceId `protobuf:"bytes,2,opt,name=namespace_id,json=namespaceId,proto3,oneof"`
}

type WaitGroupsGarbageCollectionRecord_WaitGroupId struct {
	WaitGroupId *WaitGroupId `protobuf:"bytes,3,opt,name=wait_group_id,json=waitGroupId,proto3,oneof"`
}

func (*WaitGroupsGarbageCollectionRecord_NamespaceId) isWaitGroupsGarbageCollectionRecord_Record() {}

func (*WaitGroupsGarbageCollectionRecord_WaitGroupId) isWaitGroupsGarbageCollectionRecord_Record() {}

type WaitGroupsExpirationRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaitGroupId   *WaitGroupId           `protobuf:"bytes,1,opt,name=wait_group_id,json=waitGroupId,proto3" json:"wait_group_id,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitGroupsExpirationRecord) Reset() {
	*x = WaitGroupsExpirationRecord{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitGroupsExpirationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitGroupsExpirationRecord) ProtoMessage() {}

func (x *WaitGroupsExpirationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitGroupsExpirationRecord.ProtoReflect.Descriptor instead.
func (*WaitGroupsExpirationRecord) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{27}
}

func (x *WaitGroupsExpirationRecord) GetWaitGroupId() *WaitGroupId {
	if x != nil {
		return x.WaitGroupId
	}
	return nil
}

func (x *WaitGroupsExpirationRecord) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// WaitGroupsDeletionRecord schedules the deletion of a finished wait group.
// delete_at is the timestamp (ns) at which garbage collection should delete
// the wait group, computed as finished_at + delete_after_finished_seconds.
type WaitGroupsDeletionRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaitGroupId   *WaitGroupId           `protobuf:"bytes,1,opt,name=wait_group_id,json=waitGroupId,proto3" json:"wait_group_id,omitempty"`
	DeleteAt      int64                  `protobuf:"varint,2,opt,name=delete_at,json=deleteAt,proto3" json:"delete_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitGroupsDeletionRecord) Reset() {
	*x = WaitGroupsDeletionRecord{}
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitGroupsDeletionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitGroupsDeletionRecord) ProtoMessage() {}

func (x *WaitGroupsDeletionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_wait_groups_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitGroupsDeletionRecord.ProtoReflect.Descriptor instead.
func (*WaitGroupsDeletionRecord) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_wait_groups_proto_rawDescGZIP(), []int{28}
}

func (x *WaitGroupsDeletionRecord) GetWaitGroupId() *WaitGroupId {
	if x != nil {
		return x.WaitGroupId
	}
	return nil
}

func (x *WaitGroupsDeletionRecord) GetDeleteAt() int64 {
	if x != nil {
		return x.DeleteAt
	}
	return 0
}

var File_pkg_corepb_wait_groups_proto protoreflect.FileDescriptor

const file_pkg_corepb_wait_groups_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/corepb/wait_groups.proto\x12\x19com.evrblk.grackle.corepb\x1a\x17pkg/corepb/common.proto\x1a\x1bpkg/corepb/namespaces.proto\"\x96\x04\n" +
	"\x16CreateWaitGroupRequest\x12J\n" +
	"\rwait_group_id\x18\x01 \x01(\v2&.com.evrblk.grackle.corepb.WaitGroupIdR\vwaitGroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03now\x18\x04 \x01(\x03R\x03now\x12\x18\n" +
	"\acounter\x18\x05 \x01(\x04R\acounter\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\x12[\n" +
	"\bmetadata\x18\a \x03(\v2?.com.evrblk.grackle.corepb.CreateWaitGroupRequest.MetadataEntryR\bmetadata\x12R\n" +
	"'max_number_of_wait_groups_per_namespace\x18\b \x01(\x03R!maxNumberOfWaitGroupsPerNamespace\x12A\n" +
	"\x1ddelete_after_finished_seconds\x18\t \x01(\x03R\x1adeleteAfterFinishedSeconds\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\x17CreateWaitGroupResponse\x12C\n" +
	"\n" +
	"wait_group\x18\x01 \x01(\v2$.com.evrblk.grackle.corepb.WaitGroupR\twaitGroup\"\x80\x04\n" +
	"\x16UpdateWaitGroupRequest\x12I\n" +
	"\fnamespace_id\x18\x01 \x01(\v2&.com.evrblk.grackle.corepb.NamespaceIdR\vnamespaceId\x12&\n" +
	"\x0fwait_group_name\x18\x02 \x01(\tR\rwaitGroupName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03now\x18\x04 \x01(\x03R\x03now\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\x12\x18\n" +
	"\acounter\x18\x06 \x01(\x04R\acounter\x12[\n" +
	"\bmetadata\x18\a \x03(\v2?.com.evrblk.grackle.corepb.UpdateWaitGroupRequest.MetadataEntryR\bmetadata\x12)\n" +
	"\x10expected_version\x18\b \x01(\x04R\x0fexpectedVersion\x12A\n" +
	"\x1ddelete_after_finished_seconds\x18\t \x01(\x03R\x1adeleteAfterFinishedSeconds\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\x17UpdateWaitGroupResponse\x12C\n" +
	"\n" +
	"wait_group\x18\x01 \x01(\v2$.com.evrblk.grackle.corepb.WaitGroupR\twaitGroup\"\xcf\x01\n" +
	"\x15ListWaitGroupsRequest\x12I\n" +
	"\fnamespace_id\x18\x01 \x01(\v2&.com.evrblk.grackle.corepb.NamespaceIdR\vnamespaceId\x12U\n" +
	"\x10pagination_token\x18\x02 \x01(\v2*.com.evrblk.grackle.corepb.PaginationTokenR\x0fpaginationToken\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xa7\x02\n" +
	"\x16ListWaitGroupsResponse\x12E\n" +
	"\vwait_groups\x18\x01 \x03(\v2$.com.evrblk.grackle.corepb.WaitGroupR\n" +
	"waitGroups\x12^\n" +
	"\x15next_pagination_token\x18\x02 \x01(\v2*.com.evrblk.grackle.corepb.PaginationTokenR\x13nextPaginationToken\x12f\n" +
	"\x19previous_pagination_token\x18\x03 \x01(\v2*.com.evrblk.grackle.corepb.PaginationTokenR\x17previousPaginationToken\"a\n" +
	"\x13GetWaitGroupRequest\x12J\n" +
	"\rwait_group_id\x18\x01 \x01(\v2&.com.evrblk.grackle.corepb.WaitGroupIdR\vwaitGroupId\"[\n" +
	"\x14GetWaitGroupResponse\x12C\n" +
	"\n" +
	"wait_group\x18\x01 \x01(\v2$.com.evrblk.grackle.corepb.WaitGroupR\twaitGroup\"\x8e\x01\n" +
	"\x19GetWaitGroupByNameRequest\x12I\n" +
	"\fnamespace_id\x18\x01 \x01(\v2&.com.evrblk.grackle.corepb.NamespaceIdR\vnamespaceId\x12&\n" +
	"\x0fwait_group_name\x18\x02 \x01(\tR\rwaitGroupName\"a\n" +
	"\x1aGetWaitGroupByNameResponse\x12C\n" +
	"\n" +
	"wait_group\x18\x01 \x01(\v2$.com.evrblk.grackle.corepb.WaitGroupR\twaitGroup\"\xa8\x01\n" +
	"\x16DeleteWaitGroupRequest\x12I\n" +
	"\fnamespace_id\x18\x01 \x01(\v2&.com.evrblk.grackle.corepb.NamespaceIdR\vnamespaceId\x12&\n" +
	"\x0fwait_group_name\x18\x02 \x01(\tR\rwaitGroupName\x12\x1b\n" +
	"\trecord_id\x18\x03 \x01(\x04R\brecordId\"\x19\n" +
	"\x17DeleteWaitGroupResponse\"\xea\x01\n" +
	" CompleteJobsFromWaitGroupRequest\x12I\n" +
	"\fnamespace_id\x18\x01 \x01(\v2&.com.evrblk.grackle.corepb.NamespaceIdR\vnamespaceId\x12&\n" +
	"\x0fwait_group_name\x18\x02 \x01(\tR\rwaitGroupName\x12A\n" +
	"\x04jobs\x18\x03 \x03(\v2-.com.evrblk.grackle.corepb.CompleteJobRequestR\x04jobs\x12\x10\n" +
	"\x03now\x18\x04 \x01(\x03R\x03now\"\xc1\x01\n" +
	"\x12CompleteJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12W\n" +
	"\bmetadata\x18\x02 \x03(\v2;.com.evrblk.grackle.corepb.CompleteJobRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"!CompleteJobsFromWaitGroupResponse\x12C\n" +
	"\n" +
	"wait_group\x18\x01 \x01(\v2$.com.evrblk.grackle.corepb.WaitGroupR\twaitGroup\"\xfa\x01\n" +
	"\x18ListWaitGroupJobsRequest\x12I\n" +
	"\fnamespace_id\x18\x01 \x01(\v2&.com.evrblk.grackle.corepb.NamespaceIdR\vnamespaceId\x12&\n" +
	"\x0fwait_group_name\x18\x02 \x01(\tR\rwaitGroupName\x12U\n" +
	"\x10pagination_token\x18\x03 \x01(\v2*.com.evrblk.grackle.corepb.PaginationTokenR\x0fpaginationToken\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xa0\x02\n" +
	"\x19ListWaitGroupJobsResponse\x12;\n" +
	"\x04jobs\x18\x01 \x03(\v2'.com.evrblk.grackle.corepb.WaitGroupJobR\x04jobs\x12^\n" +
	"\x15next_pagination_token\x18\x02 \x01(\v2*.com.evrblk.grackle.corepb.PaginationTokenR\x13nextPaginationToken\x12f\n" +
	"\x19previous_pagination_token\x18\x03 \x01(\v2*.com.evrblk.grackle.corepb.PaginationTokenR\x17previousPaginationToken\"\xdf\x01\n" +
	"%RunWaitGroupsGarbageCollectionRequest\x12\x10\n" +
	"\x03now\x18\x01 \x01(\x03R\x03now\x12/\n" +
	"\x14gc_records_page_size\x18\x02 \x01(\x03R\x11gcRecordsPageSize\x12C\n" +
	"\x1fgc_record_wait_groups_page_size\x18\x03 \x01(\x03R\x1agcRecordWaitGroupsPageSize\x12.\n" +
	"\x13max_deleted_objects\x18\x04 \x01(\x03R\x11maxDeletedObjects\"(\n" +
	"&RunWaitGroupsGarbageCollectionResponse\"\x9c\x01\n" +
	" WaitGroupsDeleteNamespaceRequest\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\x04R\brecordId\x12I\n" +
	"\fnamespace_id\x18\x02 \x01(\v2&.com.evrblk.grackle.corepb.NamespaceIdR\vnamespaceId\x12\x10\n" +
	"\x03now\x18\x03 \x01(\x03R\x03now\"#\n" +
	"!WaitGroupsDeleteNamespaceResponse\"\x90\x05\n" +
	"\tWaitGroup\x126\n" +
	"\x02id\x18\x01 \x01(\v2&.com.evrblk.grackle.corepb.WaitGroupIdR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x04R\aversion\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\x12\x18\n" +
	"\acounter\x18\b \x01(\x04R\acounter\x12%\n" +
	"\x0ecompleted_jobs\x18\t \x01(\x04R\rcompletedJobs\x12N\n" +
	"\bmetadata\x18\n" +
	" \x03(\v22.com.evrblk.grackle.corepb.WaitGroup.MetadataEntryR\bmetadata\x12B\n" +
	"\x06status\x18\v \x01(\x0e2*.com.evrblk.grackle.corepb.WaitGroupStatusR\x06status\x12A\n" +
	"\x1ddelete_after_finished_seconds\x18\f \x01(\x03R\x1adeleteAfterFinishedSeconds\x12\x1f\n" +
	"\vfinished_at\x18\r \x01(\x03R\n" +
	"finishedAt\x12(\n" +
	"\x10last_activity_at\x18\x0e \x01(\x03R\x0elastActivityAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfc\x01\n" +
	"\fWaitGroupJob\x129\n" +
	"\x02id\x18\x01 \x01(\v2).com.evrblk.grackle.corepb.WaitGroupJobIdR\x02id\x12!\n" +
	"\fcompleted_at\x18\x02 \x01(\x03R\vcompletedAt\x12Q\n" +
	"\bmetadata\x18\x03 \x03(\v25.com.evrblk.grackle.corepb.WaitGroupJob.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x01\n" +
	"\x0eWaitGroupJobId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x04R\taccountId\x12!\n" +
	"\fnamespace_id\x18\x02 \x01(\rR\vnamespaceId\x12\"\n" +
	"\rwait_group_id\x18\x03 \x01(\x04R\vwaitGroupId\x12\x15\n" +
	"\x06job_id\x18\x04 \x01(\tR\x05jobId\"s\n" +
	"\vWaitGroupId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x04R\taccountId\x12!\n" +
	"\fnamespace_id\x18\x02 \x01(\rR\vnamespaceId\x12\"\n" +
	"\rwait_group_id\x18\x03 \x01(\x04R\vwaitGroupId\"F\n" +
	"\x11WaitGroupsCounter\x121\n" +
	"\x15number_of_wait_groups\x18\x01 \x01(\x03R\x12numberOfWaitGroups\"\xd8\x01\n" +
	"!WaitGroupsGarbageCollectionRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12K\n" +
	"\fnamespace_id\x18\x02 \x01(\v2&.com.evrblk.grackle.corepb.NamespaceIdH\x00R\vnamespaceId\x12L\n" +
	"\rwait_group_id\x18\x03 \x01(\v2&.com.evrblk.grackle.corepb.WaitGroupIdH\x00R\vwaitGroupIdB\b\n" +
	"\x06record\"\x87\x01\n" +
	"\x1aWaitGroupsExpirationRecord\x12J\n" +
	"\rwait_group_id\x18\x01 \x01(\v2&.com.evrblk.grackle.corepb.WaitGroupIdR\vwaitGroupId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"\x83\x01\n" +
	"\x18WaitGroupsDeletionRecord\x12J\n" +
	"\rwait_group_id\x18\x01 \x01(\v2&.com.evrblk.grackle.corepb.WaitGroupIdR\vwaitGroupId\x12\x1b\n" +
	"\tdelete_at\x18\x02 \x01(\x03R\bdeleteAt*\x8e\x01\n" +
	"\x0fWaitGroupStatus\x12\x1d\n" +
	"\x19WAIT_GROUP_STATUS_INVALID\x10\x00\x12\x1c\n" +
	"\x18WAIT_GROUP_STATUS_ACTIVE\x10\x01\x12\x1d\n" +
	"\x19WAIT_GROUP_STATUS_EXPIRED\x10\x02\x12\x1f\n" +
	"\x1bWAIT_GROUP_STATUS_COMPLETED\x10\x03B&Z$github.com/evrblk/grackle/pkg/corepbb\x06proto3"

var (
	file_pkg_corepb_wait_groups_proto_rawDescOnce sync.Once
	file_pkg_corepb_wait_groups_proto_rawDescData []byte
)

func file_pkg_corepb_wait_groups_proto_rawDescGZIP() []byte {
	file_pkg_corepb_wait_groups_proto_rawDescOnce.Do(func() {
		file_pkg_corepb_wait_groups_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_corepb_wait_groups_proto_rawDesc), len(file_pkg_corepb_wait_groups_proto_rawDesc)))
	})
	return file_pkg_corepb_wait_groups_proto_rawDescData
}

var file_pkg_corepb_wait_groups_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_corepb_wait_groups_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_pkg_corepb_wait_groups_proto_goTypes = []any{
	(WaitGroupStatus)(0),                           // 0: com.evrblk.grackle.corepb.WaitGroupStatus
	(*CreateWaitGroupRequest)(nil),                 // 1: com.evrblk.grackle.corepb.CreateWaitGroupRequest
	(*CreateWaitGroupResponse)(nil),                // 2: com.evrblk.grackle.corepb.CreateWaitGroupResponse
	(*UpdateWaitGroupRequest)(nil),                 // 3: com.evrblk.grackle.corepb.UpdateWaitGroupRequest
	(*UpdateWaitGroupResponse)(nil),                // 4: com.evrblk.grackle.corepb.UpdateWaitGroupResponse
	(*ListWaitGroupsRequest)(nil),                  // 5: com.evrblk.grackle.corepb.ListWaitGroupsRequest
	(*ListWaitGroupsResponse)(nil),                 // 6: com.evrblk.grackle.corepb.ListWaitGroupsResponse
	(*GetWaitGroupRequest)(nil),                    // 7: com.evrblk.grackle.corepb.GetWaitGroupRequest
	(*GetWaitGroupResponse)(nil),                   // 8: com.evrblk.grackle.corepb.GetWaitGroupResponse
	(*GetWaitGroupByNameRequest)(nil),              // 9: com.evrblk.grackle.corepb.GetWaitGroupByNameRequest
	(*GetWaitGroupByNameResponse)(nil),             // 10: com.evrblk.grackle.corepb.GetWaitGroupByNameResponse
	(*DeleteWaitGroupRequest)(nil),                 // 11: com.evrblk.grackle.corepb.DeleteWaitGroupRequest
	(*DeleteWaitGroupResponse)(nil),                // 12: com.evrblk.grackle.corepb.DeleteWaitGroupResponse
	(*CompleteJobsFromWaitGroupRequest)(nil),       // 13: com.evrblk.grackle.corepb.CompleteJobsFromWaitGroupRequest
	(*CompleteJobRequest)(nil),                     // 14: com.evrblk.grackle.corepb.CompleteJobRequest
	(*CompleteJobsFromWaitGroupResponse)(nil),      // 15: com.evrblk.grackle.corepb.CompleteJobsFromWaitGroupResponse
	(*ListWaitGroupJobsRequest)(nil),               // 16: com.evrblk.grackle.corepb.ListWaitGroupJobsRequest
	(*ListWaitGroupJobsResponse)(nil),              // 17: com.evrblk.grackle.corepb.ListWaitGroupJobsResponse
	(*RunWaitGroupsGarbageCollectionRequest)(nil),  // 18: com.evrblk.grackle.corepb.RunWaitGroupsGarbageCollectionRequest
	(*RunWaitGroupsGarbageCollectionResponse)(nil), // 19: com.evrblk.grackle.corepb.RunWaitGroupsGarbageCollectionResponse
	(*WaitGroupsDeleteNamespaceRequest)(nil),       // 20: com.evrblk.grackle.corepb.WaitGroupsDeleteNamespaceRequest
	(*WaitGroupsDeleteNamespaceResponse)(nil),      // 21: com.evrblk.grackle.corepb.WaitGroupsDeleteNamespaceResponse
	(*WaitGroup)(nil),                              // 22: com.evrblk.grackle.corepb.WaitGroup
	(*WaitGroupJob)(nil),                           // 23: com.evrblk.grackle.corepb.WaitGroupJob
	(*WaitGroupJobId)(nil),                         // 24: com.evrblk.grackle.corepb.WaitGroupJobId
	(*WaitGroupId)(nil),                            // 25: com.evrblk.grackle.corepb.WaitGroupId
	(*WaitGroupsCounter)(nil),                      // 26: com.evrblk.grackle.corepb.WaitGroupsCounter
	(*WaitGroupsGarbageCollectionRecord)(nil),      // 27: com.evrblk.grackle.corepb.WaitGroupsGarbageCollectionRecord
	(*WaitGroupsExpirationRecord)(nil),             // 28: com.evrblk.grackle.corepb.WaitGroupsExpirationRecord
	(*WaitGroupsDeletionRecord)(nil),               // 29: com.evrblk.grackle.corepb.WaitGroupsDeletionRecord
	nil,                                            // 30: com.evrblk.grackle.corepb.CreateWaitGroupRequest.MetadataEntry
	nil,                                            // 31: com.evrblk.grackle.corepb.UpdateWaitGroupRequest.MetadataEntry
	nil,                                            // 32: com.evrblk.grackle.corepb.CompleteJobRequest.MetadataEntry
	nil,                                            // 33: com.evrblk.grackle.corepb.WaitGroup.MetadataEntry
	nil,                                            // 34: com.evrblk.grackle.corepb.WaitGroupJob.MetadataEntry
	(*NamespaceId)(nil),                            // 35: com.evrblk.grackle.corepb.NamespaceId
	(*PaginationToken)(nil),                        // 36: com.evrblk.grackle.corepb.PaginationToken
}
var file_pkg_corepb_wait_groups_proto_depIdxs = []int32{
	25, // 0: com.evrblk.grackle.corepb.CreateWaitGroupRequest.wait_group_id:type_name -> com.evrblk.grackle.corepb.WaitGroupId
	30, // 1: com.evrblk.grackle.corepb.CreateWaitGroupRequest.metadata:type_name -> com.evrblk.grackle.corepb.CreateWaitGroupRequest.MetadataEntry
	22, // 2: com.evrblk.grackle.corepb.CreateWaitGroupResponse.wait_group:type_name -> com.evrblk.grackle.corepb.WaitGroup
	35, // 3: com.evrblk.grackle.corepb.UpdateWaitGroupRequest.namespace_id:type_name -> com.evrblk.grackle.corepb.NamespaceId
	31, // 4: com.evrblk.grackle.corepb.UpdateWaitGroupRequest.metadata:type_name -> com.evrblk.grackle.corepb.UpdateWaitGroupRequest.MetadataEntry
	22, // 5: com.evrblk.grackle.corepb.UpdateWaitGroupResponse.wait_group:type_name -> com.evrblk.grackle.corepb.WaitGroup
	35, // 6: com.evrblk.grackle.corepb.ListWaitGroupsRequest.namespace_id:type_name -> com.evrblk.grackle.corepb.NamespaceId
	36, // 7: com.evrblk.grackle.corepb.ListWaitGroupsRequest.pagination_token:type_name -> com.evrblk.grackle.corepb.PaginationToken
	22, // 8: com.evrblk.grackle.corepb.ListWaitGroupsResponse.wait_groups:type_name -> com.evrblk.grackle.corepb.WaitGroup
	36, // 9: com.evrblk.grackle.corepb.ListWaitGroupsResponse.next_pagination_token:type_name -> com.evrblk.grackle.corepb.PaginationToken
	36, // 10: com.evrblk.grackle.corepb.ListWaitGroupsResponse.previous_pagination_token:type_name -> com.evrblk.grackle.corepb.PaginationToken
	25, // 11: com.evrblk.grackle.corepb.GetWaitGroupRequest.wait_group_id:type_name -> com.evrblk.grackle.corepb.WaitGroupId
	22, // 12: com.evrblk.grackle.corepb.GetWaitGroupResponse.wait_group:type_name -> com.evrblk.grackle.corepb.WaitGroup
	35, // 13: com.evrblk.grackle.corepb.GetWaitGroupByNameRequest.namespace_id:type_name -> com.evrblk.grackle.corepb.NamespaceId
	22, // 14: com.evrblk.grackle.corepb.GetWaitGroupByNameResponse.wait_group:type_name -> com.evrblk.grackle.corepb.WaitGroup
	35, // 15: com.evrblk.grackle.corepb.DeleteWaitGroupRequest.namespace_id:type_name -> com.evrblk.grackle.corepb.NamespaceId
	35, // 16: com.evrblk.grackle.corepb.CompleteJobsFromWaitGroupRequest.namespace_id:type_name -> com.evrblk.grackle.corepb.NamespaceId
	14, // 17: com.evrblk.grackle.corepb.CompleteJobsFromWaitGroupRequest.jobs:type_name -> com.evrblk.grackle.corepb.CompleteJobRequest
	32, // 18: com.evrblk.grackle.corepb.CompleteJobRequest.metadata:type_name -> com.evrblk.grackle.corepb.CompleteJobRequest.MetadataEntry
	22, // 19: com.evrblk.grackle.corepb.CompleteJobsFromWaitGroupResponse.wait_group:type_name -> com.evrblk.grackle.corepb.WaitGroup
	35, // 20: com.evrblk.grackle.corepb.ListWaitGroupJobsRequest.namespace_id:type_name -> com.evrblk.grackle.corepb.NamespaceId
	36, // 21: com.evrblk.grackle.corepb.ListWaitGroupJobsRequest.pagination_token:type_name -> com.evrblk.grackle.corepb.PaginationToken
	23, // 22: com.evrblk.grackle.corepb.ListWaitGroupJobsResponse.jobs:type_name -> com.evrblk.grackle.corepb.WaitGroupJob
	36, // 23: com.evrblk.grackle.corepb.ListWaitGroupJobsResponse.next_pagination_token:type_name -> com.evrblk.grackle.corepb.PaginationToken
	36, // 24: com.evrblk.grackle.corepb.ListWaitGroupJobsResponse.previous_pagination_token:type_name -> com.evrblk.grackle.corepb.PaginationToken
	35, // 25: com.evrblk.grackle.corepb.WaitGroupsDeleteNamespaceRequest.namespace_id:type_name -> com.evrblk.grackle.corepb.NamespaceId
	25, // 26: com.evrblk.grackle.corepb.WaitGroup.id:type_name -> com.evrblk.grackle.corepb.WaitGroupId
	33, // 27: com.evrblk.grackle.corepb.WaitGroup.metadata:type_name -> com.evrblk.grackle.corepb.WaitGroup.MetadataEntry
	0,  // 28: com.evrblk.grackle.corepb.WaitGroup.status:type_name -> com.evrblk.grackle.corepb.WaitGroupStatus
	24, // 29: com.evrblk.grackle.corepb.WaitGroupJob.id:type_name -> com.evrblk.grackle.corepb.WaitGroupJobId
	34, // 30: com.evrblk.grackle.corepb.WaitGroupJob.metadata:type_name -> com.evrblk.grackle.corepb.WaitGroupJob.MetadataEntry
	35, // 31: com.evrblk.grackle.corepb.WaitGroupsGarbageCollectionRecord.namespace_id:type_name -> com.evrblk.grackle.corepb.NamespaceId
	25, // 32: com.evrblk.grackle.corepb.WaitGroupsGarbageCollectionRecord.wait_group_id:type_name -> com.evrblk.grackle.corepb.WaitGroupId
	25, // 33: com.evrblk.grackle.corepb.WaitGroupsExpirationRecord.wait_group_id:type_name -> com.evrblk.grackle.corepb.WaitGroupId
	25, // 34: com.evrblk.grackle.corepb.WaitGroupsDeletionRecord.wait_group_id:type_name -> com.evrblk.grackle.corepb.WaitGroupId
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_pkg_corepb_wait_groups_proto_init() }
func file_pkg_corepb_wait_groups_proto_init() {
	if File_pkg_corepb_wait_groups_proto != nil {
		return
	}
	file_pkg_corepb_common_proto_init()
	file_pkg_corepb_namespaces_proto_init()
	file_pkg_corepb_wait_groups_proto_msgTypes[26].OneofWrappers = []any{
		(*WaitGroupsGarbageCollectionRecord_NamespaceId)(nil),
		(*WaitGroupsGarbageCollectionRecord_WaitGroupId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_corepb_wait_groups_proto_rawDesc), len(file_pkg_corepb_wait_groups_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_corepb_wait_groups_proto_goTypes,
		DependencyIndexes: file_pkg_corepb_wait_groups_proto_depIdxs,
		EnumInfos:         file_pkg_corepb_wait_groups_proto_enumTypes,
		MessageInfos:      file_pkg_corepb_wait_groups_proto_msgTypes,
	}.Build()
	File_pkg_corepb_wait_groups_proto = out.File
	file_pkg_corepb_wait_groups_proto_goTypes = nil
	file_pkg_corepb_wait_groups_proto_depIdxs = nil
}
