// Code generated by `monstera code generate`. DO NOT EDIT.

package coreapis

import (
	"fmt"
	corepb "github.com/evrblk/grackle/pkg/corepb"
	monstera "github.com/evrblk/monstera"
	monsterax "github.com/evrblk/monstera/x"
	prometheus "github.com/prometheus/client_golang/prometheus"
	"io"
	"time"
)

var (
	monsteraCoreMethodDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Help:                            "Monstera core method duration",
		Name:                            "monstera_core_method_duration_seconds",
		NativeHistogramBucketFactor:     1.1,
		NativeHistogramMaxBucketNumber:  100,
		NativeHistogramMinResetDuration: time.Hour,
	}, []string{"core", "method", "shard", "replica"})
	monsteraCoreMethodCount = prometheus.NewCounterVec(prometheus.CounterOpts{
		Help: "Monstera core method count",
		Name: "monstera_core_method_count",
	}, []string{"core", "method", "shard", "replica"})
)

type GrackleLocksCoreAdapter struct {
	shardId   string
	replicaId string

	grackleLocksCore GrackleLocksCoreApi
}

var _ monstera.ApplicationCore = &GrackleLocksCoreAdapter{}

func NewGrackleLocksCoreAdapter(shardId string, replicaId string, grackleLocksCore GrackleLocksCoreApi) *GrackleLocksCoreAdapter {
	return &GrackleLocksCoreAdapter{
		grackleLocksCore: grackleLocksCore,
		replicaId:        replicaId,
		shardId:          shardId,
	}
}

func (a *GrackleLocksCoreAdapter) Snapshot() monstera.ApplicationCoreSnapshot {
	defer monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleLocks", "Snapshot", a.shardId, a.replicaId), time.Now())
	monsteraCoreMethodCount.WithLabelValues("GrackleLocks", "Snapshot", a.shardId, a.replicaId).Inc()

	return a.grackleLocksCore.Snapshot()
}

func (a *GrackleLocksCoreAdapter) Restore(r io.ReadCloser) error {
	defer monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleLocks", "Restore", a.shardId, a.replicaId), time.Now())
	monsteraCoreMethodCount.WithLabelValues("GrackleLocks", "Restore", a.shardId, a.replicaId).Inc()

	return a.grackleLocksCore.Restore(r)
}

func (a *GrackleLocksCoreAdapter) Close() {
	a.grackleLocksCore.Close()
}

func (a *GrackleLocksCoreAdapter) Update(appRequestBytes []byte) (*monstera.UpdateResponse, error) {
	response := &monstera.UpdateResponse{}
	appResponse := &monsterax.Response{}
	appRequest := &monsterax.Request{}

	err := appRequest.UnmarshalVT(appRequestBytes)
	if err != nil {
		return nil, err
	}

	t1 := time.Now()

	switch appRequest.MethodNumber {
	case 1:
		payload := corepb.AcquireLockRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleLocksCore.AcquireLock(&AcquireLockRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleLocks", "AcquireLock", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleLocks", "AcquireLock", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 2:
		payload := corepb.ReleaseLockRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleLocksCore.ReleaseLock(&ReleaseLockRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleLocks", "ReleaseLock", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleLocks", "ReleaseLock", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 3:
		payload := corepb.DeleteLockRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleLocksCore.DeleteLock(&DeleteLockRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleLocks", "DeleteLock", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleLocks", "DeleteLock", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 4:
		payload := corepb.GetLockRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleLocksCore.GetLock(&GetLockRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleLocks", "GetLock", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleLocks", "GetLock", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 5:
		payload := corepb.RunLocksGarbageCollectionRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleLocksCore.RunLocksGarbageCollection(&RunLocksGarbageCollectionRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleLocks", "RunLocksGarbageCollection", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleLocks", "RunLocksGarbageCollection", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 6:
		payload := corepb.LocksDeleteNamespaceRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleLocksCore.LocksDeleteNamespace(&LocksDeleteNamespaceRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleLocks", "LocksDeleteNamespace", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleLocks", "LocksDeleteNamespace", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 7:
		payload := corepb.CreateLockLeaseRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleLocksCore.CreateLockLease(&CreateLockLeaseRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleLocks", "CreateLockLease", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleLocks", "CreateLockLease", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 8:
		payload := corepb.RefreshLockLeaseRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleLocksCore.RefreshLockLease(&RefreshLockLeaseRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleLocks", "RefreshLockLease", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleLocks", "RefreshLockLease", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 9:
		payload := corepb.RevokeLockLeaseRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleLocksCore.RevokeLockLease(&RevokeLockLeaseRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleLocks", "RevokeLockLease", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleLocks", "RevokeLockLease", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	default:
		fmt.Errorf("no matching handlers")
	}

	appResponseBytes, err := appResponse.MarshalVT()
	if err != nil {
		return nil, err
	}
	response.Data = appResponseBytes

	return response, nil
}

func (a *GrackleLocksCoreAdapter) Read(appRequestBytes []byte) (*monstera.ReadResponse, error) {
	response := &monstera.ReadResponse{}
	appResponse := &monsterax.Response{}
	appRequest := &monsterax.Request{}

	err := appRequest.UnmarshalVT(appRequestBytes)
	if err != nil {
		return nil, err
	}

	t1 := time.Now()

	switch appRequest.MethodNumber {
	case 1:
		payload := corepb.ListLocksRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleLocksCore.ListLocks(&ListLocksRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleLocks", "ListLocks", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleLocks", "ListLocks", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 2:
		payload := corepb.ListLocksByLeaseIdRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleLocksCore.ListLocksByLeaseId(&ListLocksByLeaseIdRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleLocks", "ListLocksByLeaseId", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleLocks", "ListLocksByLeaseId", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 3:
		payload := corepb.ListLockLeasesRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleLocksCore.ListLockLeases(&ListLockLeasesRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleLocks", "ListLockLeases", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleLocks", "ListLockLeases", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 4:
		payload := corepb.ListLockLeasesByProcessIdRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleLocksCore.ListLockLeasesByProcessId(&ListLockLeasesByProcessIdRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleLocks", "ListLockLeasesByProcessId", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleLocks", "ListLockLeasesByProcessId", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 5:
		payload := corepb.GetLockLeaseRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleLocksCore.GetLockLease(&GetLockLeaseRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleLocks", "GetLockLease", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleLocks", "GetLockLease", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	default:
		panic("no matching handlers")
	}

	appResponseBytes, err := appResponse.MarshalVT()
	if err != nil {
		return nil, err
	}
	response.Data = appResponseBytes

	return response, nil
}

type GrackleSemaphoresCoreAdapter struct {
	shardId   string
	replicaId string

	grackleSemaphoresCore GrackleSemaphoresCoreApi
}

var _ monstera.ApplicationCore = &GrackleSemaphoresCoreAdapter{}

func NewGrackleSemaphoresCoreAdapter(shardId string, replicaId string, grackleSemaphoresCore GrackleSemaphoresCoreApi) *GrackleSemaphoresCoreAdapter {
	return &GrackleSemaphoresCoreAdapter{
		grackleSemaphoresCore: grackleSemaphoresCore,
		replicaId:             replicaId,
		shardId:               shardId,
	}
}

func (a *GrackleSemaphoresCoreAdapter) Snapshot() monstera.ApplicationCoreSnapshot {
	defer monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "Snapshot", a.shardId, a.replicaId), time.Now())
	monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "Snapshot", a.shardId, a.replicaId).Inc()

	return a.grackleSemaphoresCore.Snapshot()
}

func (a *GrackleSemaphoresCoreAdapter) Restore(r io.ReadCloser) error {
	defer monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "Restore", a.shardId, a.replicaId), time.Now())
	monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "Restore", a.shardId, a.replicaId).Inc()

	return a.grackleSemaphoresCore.Restore(r)
}

func (a *GrackleSemaphoresCoreAdapter) Close() {
	a.grackleSemaphoresCore.Close()
}

func (a *GrackleSemaphoresCoreAdapter) Update(appRequestBytes []byte) (*monstera.UpdateResponse, error) {
	response := &monstera.UpdateResponse{}
	appResponse := &monsterax.Response{}
	appRequest := &monsterax.Request{}

	err := appRequest.UnmarshalVT(appRequestBytes)
	if err != nil {
		return nil, err
	}

	t1 := time.Now()

	switch appRequest.MethodNumber {
	case 1:
		payload := corepb.AcquireSemaphoreRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleSemaphoresCore.AcquireSemaphore(&AcquireSemaphoreRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "AcquireSemaphore", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "AcquireSemaphore", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 2:
		payload := corepb.ReleaseSemaphoreRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleSemaphoresCore.ReleaseSemaphore(&ReleaseSemaphoreRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "ReleaseSemaphore", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "ReleaseSemaphore", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 3:
		payload := corepb.CreateSemaphoreRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleSemaphoresCore.CreateSemaphore(&CreateSemaphoreRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "CreateSemaphore", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "CreateSemaphore", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 4:
		payload := corepb.UpdateSemaphoreRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleSemaphoresCore.UpdateSemaphore(&UpdateSemaphoreRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "UpdateSemaphore", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "UpdateSemaphore", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 5:
		payload := corepb.DeleteSemaphoreRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleSemaphoresCore.DeleteSemaphore(&DeleteSemaphoreRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "DeleteSemaphore", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "DeleteSemaphore", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 6:
		payload := corepb.RunSemaphoresGarbageCollectionRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleSemaphoresCore.RunSemaphoresGarbageCollection(&RunSemaphoresGarbageCollectionRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "RunSemaphoresGarbageCollection", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "RunSemaphoresGarbageCollection", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 7:
		payload := corepb.SemaphoresDeleteNamespaceRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleSemaphoresCore.SemaphoresDeleteNamespace(&SemaphoresDeleteNamespaceRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "SemaphoresDeleteNamespace", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "SemaphoresDeleteNamespace", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 8:
		payload := corepb.CreateSemaphoreLeaseRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleSemaphoresCore.CreateSemaphoreLease(&CreateSemaphoreLeaseRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "CreateSemaphoreLease", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "CreateSemaphoreLease", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 9:
		payload := corepb.RevokeSemaphoreLeaseRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleSemaphoresCore.RevokeSemaphoreLease(&RevokeSemaphoreLeaseRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "RevokeSemaphoreLease", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "RevokeSemaphoreLease", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 10:
		payload := corepb.RefreshSemaphoreLeaseRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleSemaphoresCore.RefreshSemaphoreLease(&RefreshSemaphoreLeaseRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "RefreshSemaphoreLease", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "RefreshSemaphoreLease", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	default:
		fmt.Errorf("no matching handlers")
	}

	appResponseBytes, err := appResponse.MarshalVT()
	if err != nil {
		return nil, err
	}
	response.Data = appResponseBytes

	return response, nil
}

func (a *GrackleSemaphoresCoreAdapter) Read(appRequestBytes []byte) (*monstera.ReadResponse, error) {
	response := &monstera.ReadResponse{}
	appResponse := &monsterax.Response{}
	appRequest := &monsterax.Request{}

	err := appRequest.UnmarshalVT(appRequestBytes)
	if err != nil {
		return nil, err
	}

	t1 := time.Now()

	switch appRequest.MethodNumber {
	case 1:
		payload := corepb.GetSemaphoreRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleSemaphoresCore.GetSemaphore(&GetSemaphoreRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "GetSemaphore", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "GetSemaphore", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 2:
		payload := corepb.GetSemaphoreByNameRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleSemaphoresCore.GetSemaphoreByName(&GetSemaphoreByNameRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "GetSemaphoreByName", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "GetSemaphoreByName", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 3:
		payload := corepb.ListSemaphoresRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleSemaphoresCore.ListSemaphores(&ListSemaphoresRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "ListSemaphores", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "ListSemaphores", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 4:
		payload := corepb.ListSemaphoresByLeaseIdRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleSemaphoresCore.ListSemaphoresByLeaseId(&ListSemaphoresByLeaseIdRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "ListSemaphoresByLeaseId", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "ListSemaphoresByLeaseId", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 5:
		payload := corepb.ListSemaphoreHoldersRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleSemaphoresCore.ListSemaphoreHolders(&ListSemaphoreHoldersRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "ListSemaphoreHolders", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "ListSemaphoreHolders", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 6:
		payload := corepb.ListSemaphoreLeasesRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleSemaphoresCore.ListSemaphoreLeases(&ListSemaphoreLeasesRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "ListSemaphoreLeases", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "ListSemaphoreLeases", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 7:
		payload := corepb.ListSemaphoreLeasesByProcessIdRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleSemaphoresCore.ListSemaphoreLeasesByProcessId(&ListSemaphoreLeasesByProcessIdRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "ListSemaphoreLeasesByProcessId", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "ListSemaphoreLeasesByProcessId", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 8:
		payload := corepb.GetSemaphoreLeaseRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleSemaphoresCore.GetSemaphoreLease(&GetSemaphoreLeaseRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleSemaphores", "GetSemaphoreLease", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleSemaphores", "GetSemaphoreLease", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	default:
		panic("no matching handlers")
	}

	appResponseBytes, err := appResponse.MarshalVT()
	if err != nil {
		return nil, err
	}
	response.Data = appResponseBytes

	return response, nil
}

type GrackleNamespacesCoreAdapter struct {
	shardId   string
	replicaId string

	grackleNamespacesCore GrackleNamespacesCoreApi
}

var _ monstera.ApplicationCore = &GrackleNamespacesCoreAdapter{}

func NewGrackleNamespacesCoreAdapter(shardId string, replicaId string, grackleNamespacesCore GrackleNamespacesCoreApi) *GrackleNamespacesCoreAdapter {
	return &GrackleNamespacesCoreAdapter{
		grackleNamespacesCore: grackleNamespacesCore,
		replicaId:             replicaId,
		shardId:               shardId,
	}
}

func (a *GrackleNamespacesCoreAdapter) Snapshot() monstera.ApplicationCoreSnapshot {
	defer monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleNamespaces", "Snapshot", a.shardId, a.replicaId), time.Now())
	monsteraCoreMethodCount.WithLabelValues("GrackleNamespaces", "Snapshot", a.shardId, a.replicaId).Inc()

	return a.grackleNamespacesCore.Snapshot()
}

func (a *GrackleNamespacesCoreAdapter) Restore(r io.ReadCloser) error {
	defer monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleNamespaces", "Restore", a.shardId, a.replicaId), time.Now())
	monsteraCoreMethodCount.WithLabelValues("GrackleNamespaces", "Restore", a.shardId, a.replicaId).Inc()

	return a.grackleNamespacesCore.Restore(r)
}

func (a *GrackleNamespacesCoreAdapter) Close() {
	a.grackleNamespacesCore.Close()
}

func (a *GrackleNamespacesCoreAdapter) Update(appRequestBytes []byte) (*monstera.UpdateResponse, error) {
	response := &monstera.UpdateResponse{}
	appResponse := &monsterax.Response{}
	appRequest := &monsterax.Request{}

	err := appRequest.UnmarshalVT(appRequestBytes)
	if err != nil {
		return nil, err
	}

	t1 := time.Now()

	switch appRequest.MethodNumber {
	case 1:
		payload := corepb.CreateNamespaceRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleNamespacesCore.CreateNamespace(&CreateNamespaceRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleNamespaces", "CreateNamespace", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleNamespaces", "CreateNamespace", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 2:
		payload := corepb.UpdateNamespaceRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleNamespacesCore.UpdateNamespace(&UpdateNamespaceRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleNamespaces", "UpdateNamespace", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleNamespaces", "UpdateNamespace", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 3:
		payload := corepb.DeleteNamespaceRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleNamespacesCore.DeleteNamespace(&DeleteNamespaceRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleNamespaces", "DeleteNamespace", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleNamespaces", "DeleteNamespace", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	default:
		fmt.Errorf("no matching handlers")
	}

	appResponseBytes, err := appResponse.MarshalVT()
	if err != nil {
		return nil, err
	}
	response.Data = appResponseBytes

	return response, nil
}

func (a *GrackleNamespacesCoreAdapter) Read(appRequestBytes []byte) (*monstera.ReadResponse, error) {
	response := &monstera.ReadResponse{}
	appResponse := &monsterax.Response{}
	appRequest := &monsterax.Request{}

	err := appRequest.UnmarshalVT(appRequestBytes)
	if err != nil {
		return nil, err
	}

	t1 := time.Now()

	switch appRequest.MethodNumber {
	case 1:
		payload := corepb.GetNamespaceRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleNamespacesCore.GetNamespace(&GetNamespaceRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleNamespaces", "GetNamespace", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleNamespaces", "GetNamespace", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 2:
		payload := corepb.GetNamespaceByNameRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleNamespacesCore.GetNamespaceByName(&GetNamespaceByNameRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleNamespaces", "GetNamespaceByName", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleNamespaces", "GetNamespaceByName", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 3:
		payload := corepb.ListNamespacesRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleNamespacesCore.ListNamespaces(&ListNamespacesRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleNamespaces", "ListNamespaces", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleNamespaces", "ListNamespaces", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	default:
		panic("no matching handlers")
	}

	appResponseBytes, err := appResponse.MarshalVT()
	if err != nil {
		return nil, err
	}
	response.Data = appResponseBytes

	return response, nil
}

type GrackleWaitGroupsCoreAdapter struct {
	shardId   string
	replicaId string

	grackleWaitGroupsCore GrackleWaitGroupsCoreApi
}

var _ monstera.ApplicationCore = &GrackleWaitGroupsCoreAdapter{}

func NewGrackleWaitGroupsCoreAdapter(shardId string, replicaId string, grackleWaitGroupsCore GrackleWaitGroupsCoreApi) *GrackleWaitGroupsCoreAdapter {
	return &GrackleWaitGroupsCoreAdapter{
		grackleWaitGroupsCore: grackleWaitGroupsCore,
		replicaId:             replicaId,
		shardId:               shardId,
	}
}

func (a *GrackleWaitGroupsCoreAdapter) Snapshot() monstera.ApplicationCoreSnapshot {
	defer monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleWaitGroups", "Snapshot", a.shardId, a.replicaId), time.Now())
	monsteraCoreMethodCount.WithLabelValues("GrackleWaitGroups", "Snapshot", a.shardId, a.replicaId).Inc()

	return a.grackleWaitGroupsCore.Snapshot()
}

func (a *GrackleWaitGroupsCoreAdapter) Restore(r io.ReadCloser) error {
	defer monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleWaitGroups", "Restore", a.shardId, a.replicaId), time.Now())
	monsteraCoreMethodCount.WithLabelValues("GrackleWaitGroups", "Restore", a.shardId, a.replicaId).Inc()

	return a.grackleWaitGroupsCore.Restore(r)
}

func (a *GrackleWaitGroupsCoreAdapter) Close() {
	a.grackleWaitGroupsCore.Close()
}

func (a *GrackleWaitGroupsCoreAdapter) Update(appRequestBytes []byte) (*monstera.UpdateResponse, error) {
	response := &monstera.UpdateResponse{}
	appResponse := &monsterax.Response{}
	appRequest := &monsterax.Request{}

	err := appRequest.UnmarshalVT(appRequestBytes)
	if err != nil {
		return nil, err
	}

	t1 := time.Now()

	switch appRequest.MethodNumber {
	case 1:
		payload := corepb.AddJobsToWaitGroupRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleWaitGroupsCore.AddJobsToWaitGroup(&AddJobsToWaitGroupRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleWaitGroups", "AddJobsToWaitGroup", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleWaitGroups", "AddJobsToWaitGroup", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 2:
		payload := corepb.CompleteJobsFromWaitGroupRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleWaitGroupsCore.CompleteJobsFromWaitGroup(&CompleteJobsFromWaitGroupRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleWaitGroups", "CompleteJobsFromWaitGroup", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleWaitGroups", "CompleteJobsFromWaitGroup", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 3:
		payload := corepb.CreateWaitGroupRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleWaitGroupsCore.CreateWaitGroup(&CreateWaitGroupRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleWaitGroups", "CreateWaitGroup", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleWaitGroups", "CreateWaitGroup", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 4:
		payload := corepb.DeleteWaitGroupRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleWaitGroupsCore.DeleteWaitGroup(&DeleteWaitGroupRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleWaitGroups", "DeleteWaitGroup", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleWaitGroups", "DeleteWaitGroup", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 5:
		payload := corepb.RunWaitGroupsGarbageCollectionRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleWaitGroupsCore.RunWaitGroupsGarbageCollection(&RunWaitGroupsGarbageCollectionRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleWaitGroups", "RunWaitGroupsGarbageCollection", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleWaitGroups", "RunWaitGroupsGarbageCollection", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 6:
		payload := corepb.WaitGroupsDeleteNamespaceRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleWaitGroupsCore.WaitGroupsDeleteNamespace(&WaitGroupsDeleteNamespaceRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleWaitGroups", "WaitGroupsDeleteNamespace", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleWaitGroups", "WaitGroupsDeleteNamespace", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	default:
		fmt.Errorf("no matching handlers")
	}

	appResponseBytes, err := appResponse.MarshalVT()
	if err != nil {
		return nil, err
	}
	response.Data = appResponseBytes

	return response, nil
}

func (a *GrackleWaitGroupsCoreAdapter) Read(appRequestBytes []byte) (*monstera.ReadResponse, error) {
	response := &monstera.ReadResponse{}
	appResponse := &monsterax.Response{}
	appRequest := &monsterax.Request{}

	err := appRequest.UnmarshalVT(appRequestBytes)
	if err != nil {
		return nil, err
	}

	t1 := time.Now()

	switch appRequest.MethodNumber {
	case 1:
		payload := corepb.GetWaitGroupRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleWaitGroupsCore.GetWaitGroup(&GetWaitGroupRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleWaitGroups", "GetWaitGroup", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleWaitGroups", "GetWaitGroup", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 2:
		payload := corepb.GetWaitGroupByNameRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleWaitGroupsCore.GetWaitGroupByName(&GetWaitGroupByNameRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleWaitGroups", "GetWaitGroupByName", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleWaitGroups", "GetWaitGroupByName", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 3:
		payload := corepb.ListWaitGroupsRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleWaitGroupsCore.ListWaitGroups(&ListWaitGroupsRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleWaitGroups", "ListWaitGroups", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleWaitGroups", "ListWaitGroups", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 4:
		payload := corepb.ListWaitGroupJobsRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleWaitGroupsCore.ListWaitGroupJobs(&ListWaitGroupJobsRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleWaitGroups", "ListWaitGroupJobs", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleWaitGroups", "ListWaitGroupJobs", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	default:
		panic("no matching handlers")
	}

	appResponseBytes, err := appResponse.MarshalVT()
	if err != nil {
		return nil, err
	}
	response.Data = appResponseBytes

	return response, nil
}

type GrackleBarriersCoreAdapter struct {
	shardId   string
	replicaId string

	grackleBarriersCore GrackleBarriersCoreApi
}

var _ monstera.ApplicationCore = &GrackleBarriersCoreAdapter{}

func NewGrackleBarriersCoreAdapter(shardId string, replicaId string, grackleBarriersCore GrackleBarriersCoreApi) *GrackleBarriersCoreAdapter {
	return &GrackleBarriersCoreAdapter{
		grackleBarriersCore: grackleBarriersCore,
		replicaId:           replicaId,
		shardId:             shardId,
	}
}

func (a *GrackleBarriersCoreAdapter) Snapshot() monstera.ApplicationCoreSnapshot {
	defer monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleBarriers", "Snapshot", a.shardId, a.replicaId), time.Now())
	monsteraCoreMethodCount.WithLabelValues("GrackleBarriers", "Snapshot", a.shardId, a.replicaId).Inc()

	return a.grackleBarriersCore.Snapshot()
}

func (a *GrackleBarriersCoreAdapter) Restore(r io.ReadCloser) error {
	defer monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleBarriers", "Restore", a.shardId, a.replicaId), time.Now())
	monsteraCoreMethodCount.WithLabelValues("GrackleBarriers", "Restore", a.shardId, a.replicaId).Inc()

	return a.grackleBarriersCore.Restore(r)
}

func (a *GrackleBarriersCoreAdapter) Close() {
	a.grackleBarriersCore.Close()
}

func (a *GrackleBarriersCoreAdapter) Update(appRequestBytes []byte) (*monstera.UpdateResponse, error) {
	response := &monstera.UpdateResponse{}
	appResponse := &monsterax.Response{}
	appRequest := &monsterax.Request{}

	err := appRequest.UnmarshalVT(appRequestBytes)
	if err != nil {
		return nil, err
	}

	t1 := time.Now()

	switch appRequest.MethodNumber {
	case 1:
		payload := corepb.CreateBarrierRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleBarriersCore.CreateBarrier(&CreateBarrierRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleBarriers", "CreateBarrier", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleBarriers", "CreateBarrier", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 2:
		payload := corepb.DeleteBarrierRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleBarriersCore.DeleteBarrier(&DeleteBarrierRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleBarriers", "DeleteBarrier", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleBarriers", "DeleteBarrier", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 3:
		payload := corepb.UpdateBarrierRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleBarriersCore.UpdateBarrier(&UpdateBarrierRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleBarriers", "UpdateBarrier", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleBarriers", "UpdateBarrier", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 4:
		payload := corepb.ArriveAtBarrierRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleBarriersCore.ArriveAtBarrier(&ArriveAtBarrierRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleBarriers", "ArriveAtBarrier", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleBarriers", "ArriveAtBarrier", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 5:
		payload := corepb.RunBarriersGarbageCollectionRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleBarriersCore.RunBarriersGarbageCollection(&RunBarriersGarbageCollectionRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleBarriers", "RunBarriersGarbageCollection", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleBarriers", "RunBarriersGarbageCollection", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 6:
		payload := corepb.BarriersDeleteNamespaceRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleBarriersCore.BarriersDeleteNamespace(&BarriersDeleteNamespaceRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleBarriers", "BarriersDeleteNamespace", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleBarriers", "BarriersDeleteNamespace", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	default:
		fmt.Errorf("no matching handlers")
	}

	appResponseBytes, err := appResponse.MarshalVT()
	if err != nil {
		return nil, err
	}
	response.Data = appResponseBytes

	return response, nil
}

func (a *GrackleBarriersCoreAdapter) Read(appRequestBytes []byte) (*monstera.ReadResponse, error) {
	response := &monstera.ReadResponse{}
	appResponse := &monsterax.Response{}
	appRequest := &monsterax.Request{}

	err := appRequest.UnmarshalVT(appRequestBytes)
	if err != nil {
		return nil, err
	}

	t1 := time.Now()

	switch appRequest.MethodNumber {
	case 1:
		payload := corepb.GetBarrierRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleBarriersCore.GetBarrier(&GetBarrierRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleBarriers", "GetBarrier", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleBarriers", "GetBarrier", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 2:
		payload := corepb.GetBarrierByNameRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleBarriersCore.GetBarrierByName(&GetBarrierByNameRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleBarriers", "GetBarrierByName", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleBarriers", "GetBarrierByName", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 3:
		payload := corepb.ListBarriersRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleBarriersCore.ListBarriers(&ListBarriersRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleBarriers", "ListBarriers", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleBarriers", "ListBarriers", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	case 4:
		payload := corepb.ListBarrierParticipantsRequest{}
		err := payload.UnmarshalBinary(appRequest.Data)
		if err != nil {
			return nil, err
		}
		methodResponse, err := a.grackleBarriersCore.ListBarrierParticipants(&ListBarrierParticipantsRequest{Payload: &payload})
		if err != nil {
			return nil, err
		}
		monsterax.MeasureSince(monsteraCoreMethodDuration.WithLabelValues("GrackleBarriers", "ListBarrierParticipants", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("GrackleBarriers", "ListBarrierParticipants", a.shardId, a.replicaId).Inc()
		appResponse.Error = methodResponse.ApplicationError
		methodResponseBytes, err := methodResponse.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		response.Data = methodResponseBytes
	default:
		panic("no matching handlers")
	}

	appResponseBytes, err := appResponse.MarshalVT()
	if err != nil {
		return nil, err
	}
	response.Data = appResponseBytes

	return response, nil
}
