// Code generated by `monstera code generate`. DO NOT EDIT.

package coreapis

import (
	"context"
	corepb "github.com/evrblk/grackle/pkg/corepb"
	monstera "github.com/evrblk/monstera"
	mrpc "github.com/evrblk/monstera/rpc"
	"io"
	"log/slog"
)

type GetLockRequest = mrpc.ReadRequest[*corepb.GetLockRequest]
type GetLockResponse = mrpc.ReadResponse[*corepb.GetLockResponse]
type ListLocksRequest = mrpc.ReadRequest[*corepb.ListLocksRequest]
type ListLocksResponse = mrpc.ReadResponse[*corepb.ListLocksResponse]
type ListLocksByLeaseIdRequest = mrpc.ReadRequest[*corepb.ListLocksByLeaseIdRequest]
type ListLocksByLeaseIdResponse = mrpc.ReadResponse[*corepb.ListLocksByLeaseIdResponse]
type ListLockLeasesRequest = mrpc.ReadRequest[*corepb.ListLockLeasesRequest]
type ListLockLeasesResponse = mrpc.ReadResponse[*corepb.ListLockLeasesResponse]
type ListLockLeasesByProcessIdRequest = mrpc.ReadRequest[*corepb.ListLockLeasesByProcessIdRequest]
type ListLockLeasesByProcessIdResponse = mrpc.ReadResponse[*corepb.ListLockLeasesByProcessIdResponse]
type GetLockLeaseRequest = mrpc.ReadRequest[*corepb.GetLockLeaseRequest]
type GetLockLeaseResponse = mrpc.ReadResponse[*corepb.GetLockLeaseResponse]
type AcquireLockRequest = mrpc.UpdateRequest[*corepb.AcquireLockRequest]
type AcquireLockResponse = mrpc.UpdateResponse[*corepb.AcquireLockResponse]
type ReleaseLockRequest = mrpc.UpdateRequest[*corepb.ReleaseLockRequest]
type ReleaseLockResponse = mrpc.UpdateResponse[*corepb.ReleaseLockResponse]
type DeleteLockRequest = mrpc.UpdateRequest[*corepb.DeleteLockRequest]
type DeleteLockResponse = mrpc.UpdateResponse[*corepb.DeleteLockResponse]
type RunLocksGarbageCollectionRequest = mrpc.UpdateUnshardedRequest[*corepb.RunLocksGarbageCollectionRequest]
type RunLocksGarbageCollectionResponse = mrpc.UpdateResponse[*corepb.RunLocksGarbageCollectionResponse]
type LocksDeleteNamespaceRequest = mrpc.UpdateRequest[*corepb.LocksDeleteNamespaceRequest]
type LocksDeleteNamespaceResponse = mrpc.UpdateResponse[*corepb.LocksDeleteNamespaceResponse]
type CreateLockLeaseRequest = mrpc.UpdateRequest[*corepb.CreateLockLeaseRequest]
type CreateLockLeaseResponse = mrpc.UpdateResponse[*corepb.CreateLockLeaseResponse]
type RefreshLockLeaseRequest = mrpc.UpdateRequest[*corepb.RefreshLockLeaseRequest]
type RefreshLockLeaseResponse = mrpc.UpdateResponse[*corepb.RefreshLockLeaseResponse]
type RevokeLockLeaseRequest = mrpc.UpdateRequest[*corepb.RevokeLockLeaseRequest]
type RevokeLockLeaseResponse = mrpc.UpdateResponse[*corepb.RevokeLockLeaseResponse]
type GetSemaphoreRequest = mrpc.ReadRequest[*corepb.GetSemaphoreRequest]
type GetSemaphoreResponse = mrpc.ReadResponse[*corepb.GetSemaphoreResponse]
type GetSemaphoreByNameRequest = mrpc.ReadRequest[*corepb.GetSemaphoreByNameRequest]
type GetSemaphoreByNameResponse = mrpc.ReadResponse[*corepb.GetSemaphoreByNameResponse]
type ListSemaphoresRequest = mrpc.ReadRequest[*corepb.ListSemaphoresRequest]
type ListSemaphoresResponse = mrpc.ReadResponse[*corepb.ListSemaphoresResponse]
type ListSemaphoresByLeaseIdRequest = mrpc.ReadRequest[*corepb.ListSemaphoresByLeaseIdRequest]
type ListSemaphoresByLeaseIdResponse = mrpc.ReadResponse[*corepb.ListSemaphoresByLeaseIdResponse]
type ListSemaphoreHoldersRequest = mrpc.ReadRequest[*corepb.ListSemaphoreHoldersRequest]
type ListSemaphoreHoldersResponse = mrpc.ReadResponse[*corepb.ListSemaphoreHoldersResponse]
type ListSemaphoreLeasesRequest = mrpc.ReadRequest[*corepb.ListSemaphoreLeasesRequest]
type ListSemaphoreLeasesResponse = mrpc.ReadResponse[*corepb.ListSemaphoreLeasesResponse]
type ListSemaphoreLeasesByProcessIdRequest = mrpc.ReadRequest[*corepb.ListSemaphoreLeasesByProcessIdRequest]
type ListSemaphoreLeasesByProcessIdResponse = mrpc.ReadResponse[*corepb.ListSemaphoreLeasesByProcessIdResponse]
type GetSemaphoreLeaseRequest = mrpc.ReadRequest[*corepb.GetSemaphoreLeaseRequest]
type GetSemaphoreLeaseResponse = mrpc.ReadResponse[*corepb.GetSemaphoreLeaseResponse]
type AcquireSemaphoreRequest = mrpc.UpdateRequest[*corepb.AcquireSemaphoreRequest]
type AcquireSemaphoreResponse = mrpc.UpdateResponse[*corepb.AcquireSemaphoreResponse]
type ReleaseSemaphoreRequest = mrpc.UpdateRequest[*corepb.ReleaseSemaphoreRequest]
type ReleaseSemaphoreResponse = mrpc.UpdateResponse[*corepb.ReleaseSemaphoreResponse]
type CreateSemaphoreRequest = mrpc.UpdateRequest[*corepb.CreateSemaphoreRequest]
type CreateSemaphoreResponse = mrpc.UpdateResponse[*corepb.CreateSemaphoreResponse]
type UpdateSemaphoreRequest = mrpc.UpdateRequest[*corepb.UpdateSemaphoreRequest]
type UpdateSemaphoreResponse = mrpc.UpdateResponse[*corepb.UpdateSemaphoreResponse]
type DeleteSemaphoreRequest = mrpc.UpdateRequest[*corepb.DeleteSemaphoreRequest]
type DeleteSemaphoreResponse = mrpc.UpdateResponse[*corepb.DeleteSemaphoreResponse]
type RunSemaphoresGarbageCollectionRequest = mrpc.UpdateUnshardedRequest[*corepb.RunSemaphoresGarbageCollectionRequest]
type RunSemaphoresGarbageCollectionResponse = mrpc.UpdateResponse[*corepb.RunSemaphoresGarbageCollectionResponse]
type SemaphoresDeleteNamespaceRequest = mrpc.UpdateRequest[*corepb.SemaphoresDeleteNamespaceRequest]
type SemaphoresDeleteNamespaceResponse = mrpc.UpdateResponse[*corepb.SemaphoresDeleteNamespaceResponse]
type CreateSemaphoreLeaseRequest = mrpc.UpdateRequest[*corepb.CreateSemaphoreLeaseRequest]
type CreateSemaphoreLeaseResponse = mrpc.UpdateResponse[*corepb.CreateSemaphoreLeaseResponse]
type RevokeSemaphoreLeaseRequest = mrpc.UpdateRequest[*corepb.RevokeSemaphoreLeaseRequest]
type RevokeSemaphoreLeaseResponse = mrpc.UpdateResponse[*corepb.RevokeSemaphoreLeaseResponse]
type RefreshSemaphoreLeaseRequest = mrpc.UpdateRequest[*corepb.RefreshSemaphoreLeaseRequest]
type RefreshSemaphoreLeaseResponse = mrpc.UpdateResponse[*corepb.RefreshSemaphoreLeaseResponse]
type GetNamespaceRequest = mrpc.ReadRequest[*corepb.GetNamespaceRequest]
type GetNamespaceResponse = mrpc.ReadResponse[*corepb.GetNamespaceResponse]
type GetNamespaceByNameRequest = mrpc.ReadRequest[*corepb.GetNamespaceByNameRequest]
type GetNamespaceByNameResponse = mrpc.ReadResponse[*corepb.GetNamespaceByNameResponse]
type ListNamespacesRequest = mrpc.ReadRequest[*corepb.ListNamespacesRequest]
type ListNamespacesResponse = mrpc.ReadResponse[*corepb.ListNamespacesResponse]
type CreateNamespaceRequest = mrpc.UpdateRequest[*corepb.CreateNamespaceRequest]
type CreateNamespaceResponse = mrpc.UpdateResponse[*corepb.CreateNamespaceResponse]
type UpdateNamespaceRequest = mrpc.UpdateRequest[*corepb.UpdateNamespaceRequest]
type UpdateNamespaceResponse = mrpc.UpdateResponse[*corepb.UpdateNamespaceResponse]
type DeleteNamespaceRequest = mrpc.UpdateRequest[*corepb.DeleteNamespaceRequest]
type DeleteNamespaceResponse = mrpc.UpdateResponse[*corepb.DeleteNamespaceResponse]
type GetWaitGroupRequest = mrpc.ReadRequest[*corepb.GetWaitGroupRequest]
type GetWaitGroupResponse = mrpc.ReadResponse[*corepb.GetWaitGroupResponse]
type GetWaitGroupByNameRequest = mrpc.ReadRequest[*corepb.GetWaitGroupByNameRequest]
type GetWaitGroupByNameResponse = mrpc.ReadResponse[*corepb.GetWaitGroupByNameResponse]
type ListWaitGroupsRequest = mrpc.ReadRequest[*corepb.ListWaitGroupsRequest]
type ListWaitGroupsResponse = mrpc.ReadResponse[*corepb.ListWaitGroupsResponse]
type ListWaitGroupCompletedJobsRequest = mrpc.ReadRequest[*corepb.ListWaitGroupCompletedJobsRequest]
type ListWaitGroupCompletedJobsResponse = mrpc.ReadResponse[*corepb.ListWaitGroupCompletedJobsResponse]
type UpdateWaitGroupRequest = mrpc.UpdateRequest[*corepb.UpdateWaitGroupRequest]
type UpdateWaitGroupResponse = mrpc.UpdateResponse[*corepb.UpdateWaitGroupResponse]
type CompleteJobsFromWaitGroupRequest = mrpc.UpdateRequest[*corepb.CompleteJobsFromWaitGroupRequest]
type CompleteJobsFromWaitGroupResponse = mrpc.UpdateResponse[*corepb.CompleteJobsFromWaitGroupResponse]
type CreateWaitGroupRequest = mrpc.UpdateRequest[*corepb.CreateWaitGroupRequest]
type CreateWaitGroupResponse = mrpc.UpdateResponse[*corepb.CreateWaitGroupResponse]
type DeleteWaitGroupRequest = mrpc.UpdateRequest[*corepb.DeleteWaitGroupRequest]
type DeleteWaitGroupResponse = mrpc.UpdateResponse[*corepb.DeleteWaitGroupResponse]
type RunWaitGroupsGarbageCollectionRequest = mrpc.UpdateUnshardedRequest[*corepb.RunWaitGroupsGarbageCollectionRequest]
type RunWaitGroupsGarbageCollectionResponse = mrpc.UpdateResponse[*corepb.RunWaitGroupsGarbageCollectionResponse]
type WaitGroupsDeleteNamespaceRequest = mrpc.UpdateRequest[*corepb.WaitGroupsDeleteNamespaceRequest]
type WaitGroupsDeleteNamespaceResponse = mrpc.UpdateResponse[*corepb.WaitGroupsDeleteNamespaceResponse]
type GetBarrierRequest = mrpc.ReadRequest[*corepb.GetBarrierRequest]
type GetBarrierResponse = mrpc.ReadResponse[*corepb.GetBarrierResponse]
type GetBarrierByNameRequest = mrpc.ReadRequest[*corepb.GetBarrierByNameRequest]
type GetBarrierByNameResponse = mrpc.ReadResponse[*corepb.GetBarrierByNameResponse]
type ListBarriersRequest = mrpc.ReadRequest[*corepb.ListBarriersRequest]
type ListBarriersResponse = mrpc.ReadResponse[*corepb.ListBarriersResponse]
type ListBarrierParticipantsRequest = mrpc.ReadRequest[*corepb.ListBarrierParticipantsRequest]
type ListBarrierParticipantsResponse = mrpc.ReadResponse[*corepb.ListBarrierParticipantsResponse]
type CreateBarrierRequest = mrpc.UpdateRequest[*corepb.CreateBarrierRequest]
type CreateBarrierResponse = mrpc.UpdateResponse[*corepb.CreateBarrierResponse]
type DeleteBarrierRequest = mrpc.UpdateRequest[*corepb.DeleteBarrierRequest]
type DeleteBarrierResponse = mrpc.UpdateResponse[*corepb.DeleteBarrierResponse]
type UpdateBarrierRequest = mrpc.UpdateRequest[*corepb.UpdateBarrierRequest]
type UpdateBarrierResponse = mrpc.UpdateResponse[*corepb.UpdateBarrierResponse]
type ArriveAtBarrierRequest = mrpc.UpdateRequest[*corepb.ArriveAtBarrierRequest]
type ArriveAtBarrierResponse = mrpc.UpdateResponse[*corepb.ArriveAtBarrierResponse]
type RunBarriersGarbageCollectionRequest = mrpc.UpdateUnshardedRequest[*corepb.RunBarriersGarbageCollectionRequest]
type RunBarriersGarbageCollectionResponse = mrpc.UpdateResponse[*corepb.RunBarriersGarbageCollectionResponse]
type BarriersDeleteNamespaceRequest = mrpc.UpdateRequest[*corepb.BarriersDeleteNamespaceRequest]
type BarriersDeleteNamespaceResponse = mrpc.UpdateResponse[*corepb.BarriersDeleteNamespaceResponse]

type GrackleClientApi interface {
	GetLock(ctx context.Context, req *corepb.GetLockRequest, opts ...mrpc.CallOption) (*corepb.GetLockResponse, error)
	ListLocks(ctx context.Context, req *corepb.ListLocksRequest, opts ...mrpc.CallOption) (*corepb.ListLocksResponse, error)
	ListLocksByLeaseId(ctx context.Context, req *corepb.ListLocksByLeaseIdRequest, opts ...mrpc.CallOption) (*corepb.ListLocksByLeaseIdResponse, error)
	ListLockLeases(ctx context.Context, req *corepb.ListLockLeasesRequest, opts ...mrpc.CallOption) (*corepb.ListLockLeasesResponse, error)
	ListLockLeasesByProcessId(ctx context.Context, req *corepb.ListLockLeasesByProcessIdRequest, opts ...mrpc.CallOption) (*corepb.ListLockLeasesByProcessIdResponse, error)
	GetLockLease(ctx context.Context, req *corepb.GetLockLeaseRequest, opts ...mrpc.CallOption) (*corepb.GetLockLeaseResponse, error)
	AcquireLock(ctx context.Context, req *corepb.AcquireLockRequest, opts ...mrpc.CallOption) (*corepb.AcquireLockResponse, error)
	ReleaseLock(ctx context.Context, req *corepb.ReleaseLockRequest, opts ...mrpc.CallOption) (*corepb.ReleaseLockResponse, error)
	DeleteLock(ctx context.Context, req *corepb.DeleteLockRequest, opts ...mrpc.CallOption) (*corepb.DeleteLockResponse, error)
	RunLocksGarbageCollection(ctx context.Context, req *corepb.RunLocksGarbageCollectionRequest, shardId string, opts ...mrpc.CallOption) (*corepb.RunLocksGarbageCollectionResponse, error)
	LocksDeleteNamespace(ctx context.Context, req *corepb.LocksDeleteNamespaceRequest, opts ...mrpc.CallOption) (*corepb.LocksDeleteNamespaceResponse, error)
	CreateLockLease(ctx context.Context, req *corepb.CreateLockLeaseRequest, opts ...mrpc.CallOption) (*corepb.CreateLockLeaseResponse, error)
	RefreshLockLease(ctx context.Context, req *corepb.RefreshLockLeaseRequest, opts ...mrpc.CallOption) (*corepb.RefreshLockLeaseResponse, error)
	RevokeLockLease(ctx context.Context, req *corepb.RevokeLockLeaseRequest, opts ...mrpc.CallOption) (*corepb.RevokeLockLeaseResponse, error)

	GetSemaphore(ctx context.Context, req *corepb.GetSemaphoreRequest, opts ...mrpc.CallOption) (*corepb.GetSemaphoreResponse, error)
	GetSemaphoreByName(ctx context.Context, req *corepb.GetSemaphoreByNameRequest, opts ...mrpc.CallOption) (*corepb.GetSemaphoreByNameResponse, error)
	ListSemaphores(ctx context.Context, req *corepb.ListSemaphoresRequest, opts ...mrpc.CallOption) (*corepb.ListSemaphoresResponse, error)
	ListSemaphoresByLeaseId(ctx context.Context, req *corepb.ListSemaphoresByLeaseIdRequest, opts ...mrpc.CallOption) (*corepb.ListSemaphoresByLeaseIdResponse, error)
	ListSemaphoreHolders(ctx context.Context, req *corepb.ListSemaphoreHoldersRequest, opts ...mrpc.CallOption) (*corepb.ListSemaphoreHoldersResponse, error)
	ListSemaphoreLeases(ctx context.Context, req *corepb.ListSemaphoreLeasesRequest, opts ...mrpc.CallOption) (*corepb.ListSemaphoreLeasesResponse, error)
	ListSemaphoreLeasesByProcessId(ctx context.Context, req *corepb.ListSemaphoreLeasesByProcessIdRequest, opts ...mrpc.CallOption) (*corepb.ListSemaphoreLeasesByProcessIdResponse, error)
	GetSemaphoreLease(ctx context.Context, req *corepb.GetSemaphoreLeaseRequest, opts ...mrpc.CallOption) (*corepb.GetSemaphoreLeaseResponse, error)
	AcquireSemaphore(ctx context.Context, req *corepb.AcquireSemaphoreRequest, opts ...mrpc.CallOption) (*corepb.AcquireSemaphoreResponse, error)
	ReleaseSemaphore(ctx context.Context, req *corepb.ReleaseSemaphoreRequest, opts ...mrpc.CallOption) (*corepb.ReleaseSemaphoreResponse, error)
	CreateSemaphore(ctx context.Context, req *corepb.CreateSemaphoreRequest, opts ...mrpc.CallOption) (*corepb.CreateSemaphoreResponse, error)
	UpdateSemaphore(ctx context.Context, req *corepb.UpdateSemaphoreRequest, opts ...mrpc.CallOption) (*corepb.UpdateSemaphoreResponse, error)
	DeleteSemaphore(ctx context.Context, req *corepb.DeleteSemaphoreRequest, opts ...mrpc.CallOption) (*corepb.DeleteSemaphoreResponse, error)
	RunSemaphoresGarbageCollection(ctx context.Context, req *corepb.RunSemaphoresGarbageCollectionRequest, shardId string, opts ...mrpc.CallOption) (*corepb.RunSemaphoresGarbageCollectionResponse, error)
	SemaphoresDeleteNamespace(ctx context.Context, req *corepb.SemaphoresDeleteNamespaceRequest, opts ...mrpc.CallOption) (*corepb.SemaphoresDeleteNamespaceResponse, error)
	CreateSemaphoreLease(ctx context.Context, req *corepb.CreateSemaphoreLeaseRequest, opts ...mrpc.CallOption) (*corepb.CreateSemaphoreLeaseResponse, error)
	RevokeSemaphoreLease(ctx context.Context, req *corepb.RevokeSemaphoreLeaseRequest, opts ...mrpc.CallOption) (*corepb.RevokeSemaphoreLeaseResponse, error)
	RefreshSemaphoreLease(ctx context.Context, req *corepb.RefreshSemaphoreLeaseRequest, opts ...mrpc.CallOption) (*corepb.RefreshSemaphoreLeaseResponse, error)

	GetNamespace(ctx context.Context, req *corepb.GetNamespaceRequest, opts ...mrpc.CallOption) (*corepb.GetNamespaceResponse, error)
	GetNamespaceByName(ctx context.Context, req *corepb.GetNamespaceByNameRequest, opts ...mrpc.CallOption) (*corepb.GetNamespaceByNameResponse, error)
	ListNamespaces(ctx context.Context, req *corepb.ListNamespacesRequest, opts ...mrpc.CallOption) (*corepb.ListNamespacesResponse, error)
	CreateNamespace(ctx context.Context, req *corepb.CreateNamespaceRequest, opts ...mrpc.CallOption) (*corepb.CreateNamespaceResponse, error)
	UpdateNamespace(ctx context.Context, req *corepb.UpdateNamespaceRequest, opts ...mrpc.CallOption) (*corepb.UpdateNamespaceResponse, error)
	DeleteNamespace(ctx context.Context, req *corepb.DeleteNamespaceRequest, opts ...mrpc.CallOption) (*corepb.DeleteNamespaceResponse, error)

	GetWaitGroup(ctx context.Context, req *corepb.GetWaitGroupRequest, opts ...mrpc.CallOption) (*corepb.GetWaitGroupResponse, error)
	GetWaitGroupByName(ctx context.Context, req *corepb.GetWaitGroupByNameRequest, opts ...mrpc.CallOption) (*corepb.GetWaitGroupByNameResponse, error)
	ListWaitGroups(ctx context.Context, req *corepb.ListWaitGroupsRequest, opts ...mrpc.CallOption) (*corepb.ListWaitGroupsResponse, error)
	ListWaitGroupCompletedJobs(ctx context.Context, req *corepb.ListWaitGroupCompletedJobsRequest, opts ...mrpc.CallOption) (*corepb.ListWaitGroupCompletedJobsResponse, error)
	UpdateWaitGroup(ctx context.Context, req *corepb.UpdateWaitGroupRequest, opts ...mrpc.CallOption) (*corepb.UpdateWaitGroupResponse, error)
	CompleteJobsFromWaitGroup(ctx context.Context, req *corepb.CompleteJobsFromWaitGroupRequest, opts ...mrpc.CallOption) (*corepb.CompleteJobsFromWaitGroupResponse, error)
	CreateWaitGroup(ctx context.Context, req *corepb.CreateWaitGroupRequest, opts ...mrpc.CallOption) (*corepb.CreateWaitGroupResponse, error)
	DeleteWaitGroup(ctx context.Context, req *corepb.DeleteWaitGroupRequest, opts ...mrpc.CallOption) (*corepb.DeleteWaitGroupResponse, error)
	RunWaitGroupsGarbageCollection(ctx context.Context, req *corepb.RunWaitGroupsGarbageCollectionRequest, shardId string, opts ...mrpc.CallOption) (*corepb.RunWaitGroupsGarbageCollectionResponse, error)
	WaitGroupsDeleteNamespace(ctx context.Context, req *corepb.WaitGroupsDeleteNamespaceRequest, opts ...mrpc.CallOption) (*corepb.WaitGroupsDeleteNamespaceResponse, error)

	GetBarrier(ctx context.Context, req *corepb.GetBarrierRequest, opts ...mrpc.CallOption) (*corepb.GetBarrierResponse, error)
	GetBarrierByName(ctx context.Context, req *corepb.GetBarrierByNameRequest, opts ...mrpc.CallOption) (*corepb.GetBarrierByNameResponse, error)
	ListBarriers(ctx context.Context, req *corepb.ListBarriersRequest, opts ...mrpc.CallOption) (*corepb.ListBarriersResponse, error)
	ListBarrierParticipants(ctx context.Context, req *corepb.ListBarrierParticipantsRequest, opts ...mrpc.CallOption) (*corepb.ListBarrierParticipantsResponse, error)
	CreateBarrier(ctx context.Context, req *corepb.CreateBarrierRequest, opts ...mrpc.CallOption) (*corepb.CreateBarrierResponse, error)
	DeleteBarrier(ctx context.Context, req *corepb.DeleteBarrierRequest, opts ...mrpc.CallOption) (*corepb.DeleteBarrierResponse, error)
	UpdateBarrier(ctx context.Context, req *corepb.UpdateBarrierRequest, opts ...mrpc.CallOption) (*corepb.UpdateBarrierResponse, error)
	ArriveAtBarrier(ctx context.Context, req *corepb.ArriveAtBarrierRequest, opts ...mrpc.CallOption) (*corepb.ArriveAtBarrierResponse, error)
	RunBarriersGarbageCollection(ctx context.Context, req *corepb.RunBarriersGarbageCollectionRequest, shardId string, opts ...mrpc.CallOption) (*corepb.RunBarriersGarbageCollectionResponse, error)
	BarriersDeleteNamespace(ctx context.Context, req *corepb.BarriersDeleteNamespaceRequest, opts ...mrpc.CallOption) (*corepb.BarriersDeleteNamespaceResponse, error)

	ListShards(applicationName string) ([]string, error)
}
type GrackleLocksCoreApi interface {
	Snapshot() monstera.ApplicationCoreSnapshot
	Restore(readers ...io.ReadCloser) error
	Close()
	GetLock(req *GetLockRequest, log *slog.Logger) (*GetLockResponse, error)
	ListLocks(req *ListLocksRequest, log *slog.Logger) (*ListLocksResponse, error)
	ListLocksByLeaseId(req *ListLocksByLeaseIdRequest, log *slog.Logger) (*ListLocksByLeaseIdResponse, error)
	ListLockLeases(req *ListLockLeasesRequest, log *slog.Logger) (*ListLockLeasesResponse, error)
	ListLockLeasesByProcessId(req *ListLockLeasesByProcessIdRequest, log *slog.Logger) (*ListLockLeasesByProcessIdResponse, error)
	GetLockLease(req *GetLockLeaseRequest, log *slog.Logger) (*GetLockLeaseResponse, error)
	AcquireLock(req *AcquireLockRequest, log *slog.Logger) (*AcquireLockResponse, error)
	ReleaseLock(req *ReleaseLockRequest, log *slog.Logger) (*ReleaseLockResponse, error)
	DeleteLock(req *DeleteLockRequest, log *slog.Logger) (*DeleteLockResponse, error)
	RunLocksGarbageCollection(req *RunLocksGarbageCollectionRequest, log *slog.Logger) (*RunLocksGarbageCollectionResponse, error)
	LocksDeleteNamespace(req *LocksDeleteNamespaceRequest, log *slog.Logger) (*LocksDeleteNamespaceResponse, error)
	CreateLockLease(req *CreateLockLeaseRequest, log *slog.Logger) (*CreateLockLeaseResponse, error)
	RefreshLockLease(req *RefreshLockLeaseRequest, log *slog.Logger) (*RefreshLockLeaseResponse, error)
	RevokeLockLease(req *RevokeLockLeaseRequest, log *slog.Logger) (*RevokeLockLeaseResponse, error)
}

type GrackleSemaphoresCoreApi interface {
	Snapshot() monstera.ApplicationCoreSnapshot
	Restore(readers ...io.ReadCloser) error
	Close()
	GetSemaphore(req *GetSemaphoreRequest, log *slog.Logger) (*GetSemaphoreResponse, error)
	GetSemaphoreByName(req *GetSemaphoreByNameRequest, log *slog.Logger) (*GetSemaphoreByNameResponse, error)
	ListSemaphores(req *ListSemaphoresRequest, log *slog.Logger) (*ListSemaphoresResponse, error)
	ListSemaphoresByLeaseId(req *ListSemaphoresByLeaseIdRequest, log *slog.Logger) (*ListSemaphoresByLeaseIdResponse, error)
	ListSemaphoreHolders(req *ListSemaphoreHoldersRequest, log *slog.Logger) (*ListSemaphoreHoldersResponse, error)
	ListSemaphoreLeases(req *ListSemaphoreLeasesRequest, log *slog.Logger) (*ListSemaphoreLeasesResponse, error)
	ListSemaphoreLeasesByProcessId(req *ListSemaphoreLeasesByProcessIdRequest, log *slog.Logger) (*ListSemaphoreLeasesByProcessIdResponse, error)
	GetSemaphoreLease(req *GetSemaphoreLeaseRequest, log *slog.Logger) (*GetSemaphoreLeaseResponse, error)
	AcquireSemaphore(req *AcquireSemaphoreRequest, log *slog.Logger) (*AcquireSemaphoreResponse, error)
	ReleaseSemaphore(req *ReleaseSemaphoreRequest, log *slog.Logger) (*ReleaseSemaphoreResponse, error)
	CreateSemaphore(req *CreateSemaphoreRequest, log *slog.Logger) (*CreateSemaphoreResponse, error)
	UpdateSemaphore(req *UpdateSemaphoreRequest, log *slog.Logger) (*UpdateSemaphoreResponse, error)
	DeleteSemaphore(req *DeleteSemaphoreRequest, log *slog.Logger) (*DeleteSemaphoreResponse, error)
	RunSemaphoresGarbageCollection(req *RunSemaphoresGarbageCollectionRequest, log *slog.Logger) (*RunSemaphoresGarbageCollectionResponse, error)
	SemaphoresDeleteNamespace(req *SemaphoresDeleteNamespaceRequest, log *slog.Logger) (*SemaphoresDeleteNamespaceResponse, error)
	CreateSemaphoreLease(req *CreateSemaphoreLeaseRequest, log *slog.Logger) (*CreateSemaphoreLeaseResponse, error)
	RevokeSemaphoreLease(req *RevokeSemaphoreLeaseRequest, log *slog.Logger) (*RevokeSemaphoreLeaseResponse, error)
	RefreshSemaphoreLease(req *RefreshSemaphoreLeaseRequest, log *slog.Logger) (*RefreshSemaphoreLeaseResponse, error)
}

type GrackleNamespacesCoreApi interface {
	Snapshot() monstera.ApplicationCoreSnapshot
	Restore(readers ...io.ReadCloser) error
	Close()
	GetNamespace(req *GetNamespaceRequest, log *slog.Logger) (*GetNamespaceResponse, error)
	GetNamespaceByName(req *GetNamespaceByNameRequest, log *slog.Logger) (*GetNamespaceByNameResponse, error)
	ListNamespaces(req *ListNamespacesRequest, log *slog.Logger) (*ListNamespacesResponse, error)
	CreateNamespace(req *CreateNamespaceRequest, log *slog.Logger) (*CreateNamespaceResponse, error)
	UpdateNamespace(req *UpdateNamespaceRequest, log *slog.Logger) (*UpdateNamespaceResponse, error)
	DeleteNamespace(req *DeleteNamespaceRequest, log *slog.Logger) (*DeleteNamespaceResponse, error)
}

type GrackleWaitGroupsCoreApi interface {
	Snapshot() monstera.ApplicationCoreSnapshot
	Restore(readers ...io.ReadCloser) error
	Close()
	GetWaitGroup(req *GetWaitGroupRequest, log *slog.Logger) (*GetWaitGroupResponse, error)
	GetWaitGroupByName(req *GetWaitGroupByNameRequest, log *slog.Logger) (*GetWaitGroupByNameResponse, error)
	ListWaitGroups(req *ListWaitGroupsRequest, log *slog.Logger) (*ListWaitGroupsResponse, error)
	ListWaitGroupCompletedJobs(req *ListWaitGroupCompletedJobsRequest, log *slog.Logger) (*ListWaitGroupCompletedJobsResponse, error)
	UpdateWaitGroup(req *UpdateWaitGroupRequest, log *slog.Logger) (*UpdateWaitGroupResponse, error)
	CompleteJobsFromWaitGroup(req *CompleteJobsFromWaitGroupRequest, log *slog.Logger) (*CompleteJobsFromWaitGroupResponse, error)
	CreateWaitGroup(req *CreateWaitGroupRequest, log *slog.Logger) (*CreateWaitGroupResponse, error)
	DeleteWaitGroup(req *DeleteWaitGroupRequest, log *slog.Logger) (*DeleteWaitGroupResponse, error)
	RunWaitGroupsGarbageCollection(req *RunWaitGroupsGarbageCollectionRequest, log *slog.Logger) (*RunWaitGroupsGarbageCollectionResponse, error)
	WaitGroupsDeleteNamespace(req *WaitGroupsDeleteNamespaceRequest, log *slog.Logger) (*WaitGroupsDeleteNamespaceResponse, error)
}

type GrackleBarriersCoreApi interface {
	Snapshot() monstera.ApplicationCoreSnapshot
	Restore(readers ...io.ReadCloser) error
	Close()
	GetBarrier(req *GetBarrierRequest, log *slog.Logger) (*GetBarrierResponse, error)
	GetBarrierByName(req *GetBarrierByNameRequest, log *slog.Logger) (*GetBarrierByNameResponse, error)
	ListBarriers(req *ListBarriersRequest, log *slog.Logger) (*ListBarriersResponse, error)
	ListBarrierParticipants(req *ListBarrierParticipantsRequest, log *slog.Logger) (*ListBarrierParticipantsResponse, error)
	CreateBarrier(req *CreateBarrierRequest, log *slog.Logger) (*CreateBarrierResponse, error)
	DeleteBarrier(req *DeleteBarrierRequest, log *slog.Logger) (*DeleteBarrierResponse, error)
	UpdateBarrier(req *UpdateBarrierRequest, log *slog.Logger) (*UpdateBarrierResponse, error)
	ArriveAtBarrier(req *ArriveAtBarrierRequest, log *slog.Logger) (*ArriveAtBarrierResponse, error)
	RunBarriersGarbageCollection(req *RunBarriersGarbageCollectionRequest, log *slog.Logger) (*RunBarriersGarbageCollectionResponse, error)
	BarriersDeleteNamespace(req *BarriersDeleteNamespaceRequest, log *slog.Logger) (*BarriersDeleteNamespaceResponse, error)
}
