// Code generated by `monstera code generate`. DO NOT EDIT.

package coreapis

import (
	monstera "github.com/evrblk/monstera"
	mrpc "github.com/evrblk/monstera/rpc"
	"io"
	"log/slog"
)

type GrackleLocksValidatingCore struct {
	core GrackleLocksCoreApi
}

var _ GrackleLocksCoreApi = &GrackleLocksValidatingCore{}

func NewGrackleLocksValidatingCore(core GrackleLocksCoreApi) *GrackleLocksValidatingCore {
	return &GrackleLocksValidatingCore{core: core}
}

func (v *GrackleLocksValidatingCore) Snapshot() monstera.ApplicationCoreSnapshot {
	return v.core.Snapshot()
}

func (v *GrackleLocksValidatingCore) Restore(readers ...io.ReadCloser) error {
	return v.core.Restore(readers...)
}

func (v *GrackleLocksValidatingCore) Close() {
	v.core.Close()
}

func (v *GrackleLocksValidatingCore) GetLock(req *GetLockRequest, log *slog.Logger) (*GetLockResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetLockResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetLock(req, log)
}

func (v *GrackleLocksValidatingCore) ListLocks(req *ListLocksRequest, log *slog.Logger) (*ListLocksResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListLocksResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListLocks(req, log)
}

func (v *GrackleLocksValidatingCore) ListLocksByLeaseId(req *ListLocksByLeaseIdRequest, log *slog.Logger) (*ListLocksByLeaseIdResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListLocksByLeaseIdResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListLocksByLeaseId(req, log)
}

func (v *GrackleLocksValidatingCore) ListLockLeases(req *ListLockLeasesRequest, log *slog.Logger) (*ListLockLeasesResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListLockLeasesResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListLockLeases(req, log)
}

func (v *GrackleLocksValidatingCore) ListLockLeasesByProcessId(req *ListLockLeasesByProcessIdRequest, log *slog.Logger) (*ListLockLeasesByProcessIdResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListLockLeasesByProcessIdResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListLockLeasesByProcessId(req, log)
}

func (v *GrackleLocksValidatingCore) GetLockLease(req *GetLockLeaseRequest, log *slog.Logger) (*GetLockLeaseResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetLockLeaseResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetLockLease(req, log)
}

func (v *GrackleLocksValidatingCore) AcquireLock(req *AcquireLockRequest, log *slog.Logger) (*AcquireLockResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &AcquireLockResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.AcquireLock(req, log)
}

func (v *GrackleLocksValidatingCore) ReleaseLock(req *ReleaseLockRequest, log *slog.Logger) (*ReleaseLockResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ReleaseLockResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ReleaseLock(req, log)
}

func (v *GrackleLocksValidatingCore) DeleteLock(req *DeleteLockRequest, log *slog.Logger) (*DeleteLockResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &DeleteLockResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.DeleteLock(req, log)
}

func (v *GrackleLocksValidatingCore) RunLocksGarbageCollection(req *RunLocksGarbageCollectionRequest, log *slog.Logger) (*RunLocksGarbageCollectionResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &RunLocksGarbageCollectionResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.RunLocksGarbageCollection(req, log)
}

func (v *GrackleLocksValidatingCore) LocksDeleteNamespace(req *LocksDeleteNamespaceRequest, log *slog.Logger) (*LocksDeleteNamespaceResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &LocksDeleteNamespaceResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.LocksDeleteNamespace(req, log)
}

func (v *GrackleLocksValidatingCore) CreateLockLease(req *CreateLockLeaseRequest, log *slog.Logger) (*CreateLockLeaseResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &CreateLockLeaseResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.CreateLockLease(req, log)
}

func (v *GrackleLocksValidatingCore) RefreshLockLease(req *RefreshLockLeaseRequest, log *slog.Logger) (*RefreshLockLeaseResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &RefreshLockLeaseResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.RefreshLockLease(req, log)
}

func (v *GrackleLocksValidatingCore) RevokeLockLease(req *RevokeLockLeaseRequest, log *slog.Logger) (*RevokeLockLeaseResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &RevokeLockLeaseResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.RevokeLockLease(req, log)
}

type GrackleSemaphoresValidatingCore struct {
	core GrackleSemaphoresCoreApi
}

var _ GrackleSemaphoresCoreApi = &GrackleSemaphoresValidatingCore{}

func NewGrackleSemaphoresValidatingCore(core GrackleSemaphoresCoreApi) *GrackleSemaphoresValidatingCore {
	return &GrackleSemaphoresValidatingCore{core: core}
}

func (v *GrackleSemaphoresValidatingCore) Snapshot() monstera.ApplicationCoreSnapshot {
	return v.core.Snapshot()
}

func (v *GrackleSemaphoresValidatingCore) Restore(readers ...io.ReadCloser) error {
	return v.core.Restore(readers...)
}

func (v *GrackleSemaphoresValidatingCore) Close() {
	v.core.Close()
}

func (v *GrackleSemaphoresValidatingCore) GetSemaphore(req *GetSemaphoreRequest, log *slog.Logger) (*GetSemaphoreResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetSemaphoreResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetSemaphore(req, log)
}

func (v *GrackleSemaphoresValidatingCore) GetSemaphoreByName(req *GetSemaphoreByNameRequest, log *slog.Logger) (*GetSemaphoreByNameResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetSemaphoreByNameResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetSemaphoreByName(req, log)
}

func (v *GrackleSemaphoresValidatingCore) ListSemaphores(req *ListSemaphoresRequest, log *slog.Logger) (*ListSemaphoresResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListSemaphoresResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListSemaphores(req, log)
}

func (v *GrackleSemaphoresValidatingCore) ListSemaphoresByLeaseId(req *ListSemaphoresByLeaseIdRequest, log *slog.Logger) (*ListSemaphoresByLeaseIdResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListSemaphoresByLeaseIdResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListSemaphoresByLeaseId(req, log)
}

func (v *GrackleSemaphoresValidatingCore) ListSemaphoreHolders(req *ListSemaphoreHoldersRequest, log *slog.Logger) (*ListSemaphoreHoldersResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListSemaphoreHoldersResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListSemaphoreHolders(req, log)
}

func (v *GrackleSemaphoresValidatingCore) ListSemaphoreLeases(req *ListSemaphoreLeasesRequest, log *slog.Logger) (*ListSemaphoreLeasesResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListSemaphoreLeasesResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListSemaphoreLeases(req, log)
}

func (v *GrackleSemaphoresValidatingCore) ListSemaphoreLeasesByProcessId(req *ListSemaphoreLeasesByProcessIdRequest, log *slog.Logger) (*ListSemaphoreLeasesByProcessIdResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListSemaphoreLeasesByProcessIdResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListSemaphoreLeasesByProcessId(req, log)
}

func (v *GrackleSemaphoresValidatingCore) GetSemaphoreLease(req *GetSemaphoreLeaseRequest, log *slog.Logger) (*GetSemaphoreLeaseResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetSemaphoreLeaseResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetSemaphoreLease(req, log)
}

func (v *GrackleSemaphoresValidatingCore) AcquireSemaphore(req *AcquireSemaphoreRequest, log *slog.Logger) (*AcquireSemaphoreResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &AcquireSemaphoreResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.AcquireSemaphore(req, log)
}

func (v *GrackleSemaphoresValidatingCore) ReleaseSemaphore(req *ReleaseSemaphoreRequest, log *slog.Logger) (*ReleaseSemaphoreResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ReleaseSemaphoreResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ReleaseSemaphore(req, log)
}

func (v *GrackleSemaphoresValidatingCore) CreateSemaphore(req *CreateSemaphoreRequest, log *slog.Logger) (*CreateSemaphoreResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &CreateSemaphoreResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.CreateSemaphore(req, log)
}

func (v *GrackleSemaphoresValidatingCore) UpdateSemaphore(req *UpdateSemaphoreRequest, log *slog.Logger) (*UpdateSemaphoreResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &UpdateSemaphoreResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.UpdateSemaphore(req, log)
}

func (v *GrackleSemaphoresValidatingCore) DeleteSemaphore(req *DeleteSemaphoreRequest, log *slog.Logger) (*DeleteSemaphoreResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &DeleteSemaphoreResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.DeleteSemaphore(req, log)
}

func (v *GrackleSemaphoresValidatingCore) RunSemaphoresGarbageCollection(req *RunSemaphoresGarbageCollectionRequest, log *slog.Logger) (*RunSemaphoresGarbageCollectionResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &RunSemaphoresGarbageCollectionResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.RunSemaphoresGarbageCollection(req, log)
}

func (v *GrackleSemaphoresValidatingCore) SemaphoresDeleteNamespace(req *SemaphoresDeleteNamespaceRequest, log *slog.Logger) (*SemaphoresDeleteNamespaceResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &SemaphoresDeleteNamespaceResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.SemaphoresDeleteNamespace(req, log)
}

func (v *GrackleSemaphoresValidatingCore) CreateSemaphoreLease(req *CreateSemaphoreLeaseRequest, log *slog.Logger) (*CreateSemaphoreLeaseResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &CreateSemaphoreLeaseResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.CreateSemaphoreLease(req, log)
}

func (v *GrackleSemaphoresValidatingCore) RevokeSemaphoreLease(req *RevokeSemaphoreLeaseRequest, log *slog.Logger) (*RevokeSemaphoreLeaseResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &RevokeSemaphoreLeaseResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.RevokeSemaphoreLease(req, log)
}

func (v *GrackleSemaphoresValidatingCore) RefreshSemaphoreLease(req *RefreshSemaphoreLeaseRequest, log *slog.Logger) (*RefreshSemaphoreLeaseResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &RefreshSemaphoreLeaseResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.RefreshSemaphoreLease(req, log)
}

type GrackleNamespacesValidatingCore struct {
	core GrackleNamespacesCoreApi
}

var _ GrackleNamespacesCoreApi = &GrackleNamespacesValidatingCore{}

func NewGrackleNamespacesValidatingCore(core GrackleNamespacesCoreApi) *GrackleNamespacesValidatingCore {
	return &GrackleNamespacesValidatingCore{core: core}
}

func (v *GrackleNamespacesValidatingCore) Snapshot() monstera.ApplicationCoreSnapshot {
	return v.core.Snapshot()
}

func (v *GrackleNamespacesValidatingCore) Restore(readers ...io.ReadCloser) error {
	return v.core.Restore(readers...)
}

func (v *GrackleNamespacesValidatingCore) Close() {
	v.core.Close()
}

func (v *GrackleNamespacesValidatingCore) GetNamespace(req *GetNamespaceRequest, log *slog.Logger) (*GetNamespaceResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetNamespaceResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetNamespace(req, log)
}

func (v *GrackleNamespacesValidatingCore) GetNamespaceByName(req *GetNamespaceByNameRequest, log *slog.Logger) (*GetNamespaceByNameResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetNamespaceByNameResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetNamespaceByName(req, log)
}

func (v *GrackleNamespacesValidatingCore) ListNamespaces(req *ListNamespacesRequest, log *slog.Logger) (*ListNamespacesResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListNamespacesResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListNamespaces(req, log)
}

func (v *GrackleNamespacesValidatingCore) CreateNamespace(req *CreateNamespaceRequest, log *slog.Logger) (*CreateNamespaceResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &CreateNamespaceResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.CreateNamespace(req, log)
}

func (v *GrackleNamespacesValidatingCore) UpdateNamespace(req *UpdateNamespaceRequest, log *slog.Logger) (*UpdateNamespaceResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &UpdateNamespaceResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.UpdateNamespace(req, log)
}

func (v *GrackleNamespacesValidatingCore) DeleteNamespace(req *DeleteNamespaceRequest, log *slog.Logger) (*DeleteNamespaceResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &DeleteNamespaceResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.DeleteNamespace(req, log)
}

type GrackleWaitGroupsValidatingCore struct {
	core GrackleWaitGroupsCoreApi
}

var _ GrackleWaitGroupsCoreApi = &GrackleWaitGroupsValidatingCore{}

func NewGrackleWaitGroupsValidatingCore(core GrackleWaitGroupsCoreApi) *GrackleWaitGroupsValidatingCore {
	return &GrackleWaitGroupsValidatingCore{core: core}
}

func (v *GrackleWaitGroupsValidatingCore) Snapshot() monstera.ApplicationCoreSnapshot {
	return v.core.Snapshot()
}

func (v *GrackleWaitGroupsValidatingCore) Restore(readers ...io.ReadCloser) error {
	return v.core.Restore(readers...)
}

func (v *GrackleWaitGroupsValidatingCore) Close() {
	v.core.Close()
}

func (v *GrackleWaitGroupsValidatingCore) GetWaitGroup(req *GetWaitGroupRequest, log *slog.Logger) (*GetWaitGroupResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetWaitGroupResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetWaitGroup(req, log)
}

func (v *GrackleWaitGroupsValidatingCore) GetWaitGroupByName(req *GetWaitGroupByNameRequest, log *slog.Logger) (*GetWaitGroupByNameResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetWaitGroupByNameResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetWaitGroupByName(req, log)
}

func (v *GrackleWaitGroupsValidatingCore) ListWaitGroups(req *ListWaitGroupsRequest, log *slog.Logger) (*ListWaitGroupsResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListWaitGroupsResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListWaitGroups(req, log)
}

func (v *GrackleWaitGroupsValidatingCore) ListWaitGroupCompletedJobs(req *ListWaitGroupCompletedJobsRequest, log *slog.Logger) (*ListWaitGroupCompletedJobsResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListWaitGroupCompletedJobsResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListWaitGroupCompletedJobs(req, log)
}

func (v *GrackleWaitGroupsValidatingCore) UpdateWaitGroup(req *UpdateWaitGroupRequest, log *slog.Logger) (*UpdateWaitGroupResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &UpdateWaitGroupResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.UpdateWaitGroup(req, log)
}

func (v *GrackleWaitGroupsValidatingCore) CompleteJobsFromWaitGroup(req *CompleteJobsFromWaitGroupRequest, log *slog.Logger) (*CompleteJobsFromWaitGroupResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &CompleteJobsFromWaitGroupResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.CompleteJobsFromWaitGroup(req, log)
}

func (v *GrackleWaitGroupsValidatingCore) CreateWaitGroup(req *CreateWaitGroupRequest, log *slog.Logger) (*CreateWaitGroupResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &CreateWaitGroupResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.CreateWaitGroup(req, log)
}

func (v *GrackleWaitGroupsValidatingCore) DeleteWaitGroup(req *DeleteWaitGroupRequest, log *slog.Logger) (*DeleteWaitGroupResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &DeleteWaitGroupResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.DeleteWaitGroup(req, log)
}

func (v *GrackleWaitGroupsValidatingCore) RunWaitGroupsGarbageCollection(req *RunWaitGroupsGarbageCollectionRequest, log *slog.Logger) (*RunWaitGroupsGarbageCollectionResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &RunWaitGroupsGarbageCollectionResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.RunWaitGroupsGarbageCollection(req, log)
}

func (v *GrackleWaitGroupsValidatingCore) WaitGroupsDeleteNamespace(req *WaitGroupsDeleteNamespaceRequest, log *slog.Logger) (*WaitGroupsDeleteNamespaceResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &WaitGroupsDeleteNamespaceResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.WaitGroupsDeleteNamespace(req, log)
}

type GrackleBarriersValidatingCore struct {
	core GrackleBarriersCoreApi
}

var _ GrackleBarriersCoreApi = &GrackleBarriersValidatingCore{}

func NewGrackleBarriersValidatingCore(core GrackleBarriersCoreApi) *GrackleBarriersValidatingCore {
	return &GrackleBarriersValidatingCore{core: core}
}

func (v *GrackleBarriersValidatingCore) Snapshot() monstera.ApplicationCoreSnapshot {
	return v.core.Snapshot()
}

func (v *GrackleBarriersValidatingCore) Restore(readers ...io.ReadCloser) error {
	return v.core.Restore(readers...)
}

func (v *GrackleBarriersValidatingCore) Close() {
	v.core.Close()
}

func (v *GrackleBarriersValidatingCore) GetBarrier(req *GetBarrierRequest, log *slog.Logger) (*GetBarrierResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetBarrierResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetBarrier(req, log)
}

func (v *GrackleBarriersValidatingCore) GetBarrierByName(req *GetBarrierByNameRequest, log *slog.Logger) (*GetBarrierByNameResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetBarrierByNameResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetBarrierByName(req, log)
}

func (v *GrackleBarriersValidatingCore) ListBarriers(req *ListBarriersRequest, log *slog.Logger) (*ListBarriersResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListBarriersResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListBarriers(req, log)
}

func (v *GrackleBarriersValidatingCore) ListBarrierParticipants(req *ListBarrierParticipantsRequest, log *slog.Logger) (*ListBarrierParticipantsResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListBarrierParticipantsResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListBarrierParticipants(req, log)
}

func (v *GrackleBarriersValidatingCore) CreateBarrier(req *CreateBarrierRequest, log *slog.Logger) (*CreateBarrierResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &CreateBarrierResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.CreateBarrier(req, log)
}

func (v *GrackleBarriersValidatingCore) DeleteBarrier(req *DeleteBarrierRequest, log *slog.Logger) (*DeleteBarrierResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &DeleteBarrierResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.DeleteBarrier(req, log)
}

func (v *GrackleBarriersValidatingCore) UpdateBarrier(req *UpdateBarrierRequest, log *slog.Logger) (*UpdateBarrierResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &UpdateBarrierResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.UpdateBarrier(req, log)
}

func (v *GrackleBarriersValidatingCore) ArriveAtBarrier(req *ArriveAtBarrierRequest, log *slog.Logger) (*ArriveAtBarrierResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ArriveAtBarrierResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ArriveAtBarrier(req, log)
}

func (v *GrackleBarriersValidatingCore) RunBarriersGarbageCollection(req *RunBarriersGarbageCollectionRequest, log *slog.Logger) (*RunBarriersGarbageCollectionResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &RunBarriersGarbageCollectionResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.RunBarriersGarbageCollection(req, log)
}

func (v *GrackleBarriersValidatingCore) BarriersDeleteNamespace(req *BarriersDeleteNamespaceRequest, log *slog.Logger) (*BarriersDeleteNamespaceResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &BarriersDeleteNamespaceResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.BarriersDeleteNamespace(req, log)
}
